### ISSUE TITLE
[1.11.2-1.0.4] was clicking on items in the item filter of an export cable

### ISSUE THREAD

**Issue by kreezxil** [PrinceOfAmber/Storage-Network#10]
client crash report: https://pastebin.com/K8FE50xC

**Comment by PrinceOfAmber** [comment]
Thanks for reporting the bugs and being so patient

**Comment by PrinceOfAmber** [comment]
Check out the latest fixes, and report anything else you find :) https://minecraft.curseforge.com/projects/simple-storage-network/files/2435492
