### ISSUE TITLE
Client side crash when right-clicking remote

### ISSUE THREAD

**Issue by kwpugh** [PrinceOfAmber/Storage-Network#100]
Forge: 2759
Mod: SimpleStorageNetwork-1.12.2-1.3.0.jar

Crash report: https://gist.github.com/kwpugh/33f7c74219c34e1a3a1092c5c34a1c73

Desc: when right-clicking an advanced remote, client crashes

**Comment by VaiN474** [comment]
same issue here, same error

**Comment by Math321** [comment]
Same issue for me.

**Comment by CharCharthemonkey** [comment]
same for me even without the remote 
[crash-2018-09-06_23.29.21-client.txt](https://github.com/PrinceOfAmber/Storage-Network/files/2359733/crash-2018-09-06_23.29.21-client.txt)

**Comment by Partonetrain** [comment]
@CharCharthemonkey that's a different error on an older verson (1.2.8), and it was fixed. https://github.com/PrinceOfAmber/Storage-Network/issues/88

**Comment by QuibblingAsh42** [comment]
Do you need additional error reports?  Just got to the point where I could build a network, and it's happening for me, too.  I'm on 1.2.9.

**Comment by QuibblingAsh42** [comment]
Just rolled back to 1.2.8 on both server and client, and experiencing no issues.

**Comment by Partonetrain** [comment]
I think this is the same issue as #93 , and @KTev says it's not resolved in 1.3.0

**Comment by CharCharthemonkey** [comment]
i can confirm in 128 129 and 130 it crashes tho someone told me to update forge to latest version so that might of fixed it but cause of a seperate issue i didnt test if it fixed it

**Comment by CharCharthemonkey** [comment]
i refernce #104 for version 130 of the mod

**Comment by PrinceOfAmber** [comment]
Pretty certain this fixes it. open a new issue for anything else 

https://minecraft.curseforge.com/projects/simple-storage-network/files/2617829
