### ISSUE TITLE
Better With Mods Compatibility/Duplication Issue

### ISSUE THREAD

**Issue by ChosenArchitect** [PrinceOfAmber/Storage-Network#102]
**Mod Version:** SimpleStorageNetwork-1.12.2-1.2.9
**Pack:** Bounds vr. 2.7
**Issue:** The crafting feature that Better With Mods add to create planks from wood logs and thus get bark. When _shift clicking_ causes the axes to duplicate to some outrageous numbers.

![2018-09-10_11 11 32](https://user-images.githubusercontent.com/35053440/45310143-21ab7880-b4eb-11e8-8f99-80c6336b46a1.png)

**Comment by PrinceOfAmber** [comment]
I think this was fixed in 1.3.0 it sounds very familiar.

Also 1.4.0 is out now which changes many things. ALso suggest you use FastBench with it. Does this still happen in new versions? https://minecraft.curseforge.com/projects/simple-storage-network/files/2617829
