### ISSUE TITLE
render crash when using simple storage networks

### ISSUE THREAD

**Issue by CharCharthemonkey** [PrinceOfAmber/Storage-Network#104]
as the title says its a render crash when using simple storage and something else but i dont see anything else causing it info please?
[crash-2018-09-12_22.31.38-client.txt](https://github.com/PrinceOfAmber/Storage-Network/files/2377605/crash-2018-09-12_22.31.38-client.txt)

**Comment by PrinceOfAmber** [comment]
somehow my tooltips cause a crash so fix is on the way

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2617829
