### ISSUE TITLE
Importing Filters Deletes Stacks of Items from Storage

### ISSUE THREAD

**Issue by sweetsosweet** [PrinceOfAmber/Storage-Network#109]
I have connected a Storage Link Cable to an inventory, in this case one was a vanilla double chest, and one was a [Better Crates](https://minecraft.curseforge.com/projects/better-crates?gameCategorySlug=mc-mods&projectID=298223) Obsidian Chest. When I click import filter on the storage link cable, it will delete all except 1 item in a stack. EG: Inventory has 1 stack (64) + 35 iron ingots. If I import filter the inventory now has 1 single iron ingot + 35 iron ingots. If I combine into 36 iron ingots then import filter again, I will have only 1 iron ingot. :( This is repeatable. I was importing filters for multiple storage and it has deleted most of my stuff.......

[Video](https://www.dropbox.com/s/kfu1koa3iqiqdbr/2018-09-21%2019-57-45.flv?dl=0)

Mod Version: SimpleStorageNetwork-1.12.2-1.4.0
Forge Version: forge-14.23.4.2760

**Comment by PrinceOfAmber** [comment]
Yep youre right thanks for the report. fix in the next version
