### ISSUE TITLE
Thaumic Insanity just updated, now server crashes when I try to access my network

### ISSUE THREAD

**Issue by webwraith** [PrinceOfAmber/Storage-Network#113]
As the title says, whenever I load my game and try to access my network, the server crashes and closes with the following error: https://paste.dimdev.org/igoxukejun.mccrash

Thankfully, I can just not use the system, since, of course, everything is in normal chests and crates, but it's a pity, because it's a fantastic early storage system

**Comment by PrinceOfAmber** [comment]
Thanks for the report newer versions will have a fix.
For reference crash log references version SimpleStorageNetwork-1.12.2-1.2.9.jar
