### ISSUE TITLE
A crash occurred when clicking the X button

### ISSUE THREAD

**Issue by wohaopa** [PrinceOfAmber/Storage-Network#115]
> ---- Minecraft Crash Report ----
> // Shall we play a game?
> 
> Time: 10/4/18 12:44 PM
> Description: Updating screen events
> 
> java.lang.NoSuchMethodError: mrriegel.storagenetwork.jei.JeiHooks.setJeiTextInternal(Ljava/lang/String;)V
> 	at mrriegel.storagenetwork.jei.JeiHooks.setFilterText(JeiHooks.java:29)
> 	at mrriegel.storagenetwork.gui.GuiContainerStorageInventory.clearSearch(GuiContainerStorageInventory.java:396)
> 	at mrriegel.storagenetwork.gui.GuiContainerStorageInventory.func_146284_a(GuiContainerStorageInventory.java:384)
> 	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
> 	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:323)
> 	at mrriegel.storagenetwork.gui.GuiContainerStorageInventory.func_73864_a(GuiContainerStorageInventory.java:402)
> 	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
> 	at mrriegel.storagenetwork.gui.GuiContainerStorageInventory.func_146274_d(GuiContainerStorageInventory.java:458)
> 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at mrriegel.storagenetwork.jei.JeiHooks.setFilterText(JeiHooks.java:29)
> 	at mrriegel.storagenetwork.gui.GuiContainerStorageInventory.clearSearch(GuiContainerStorageInventory.java:396)
> 	at mrriegel.storagenetwork.gui.GuiContainerStorageInventory.func_146284_a(GuiContainerStorageInventory.java:384)
> 	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
> 	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:323)
> 	at mrriegel.storagenetwork.gui.GuiContainerStorageInventory.func_73864_a(GuiContainerStorageInventory.java:402)
> 	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
> 	at mrriegel.storagenetwork.gui.GuiContainerStorageInventory.func_146274_d(GuiContainerStorageInventory.java:458)
> 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
> 
> -- Affected screen --
> Details:
> 	Screen name: mrriegel.storagenetwork.block.request.GuiRequest
> 
> -- Affected level --
> Details:
> 	Level name: MpServer
> 	All players: 1 total; [EntityPlayerSP['wohaopa'/131, l='MpServer', x=-24.87, y=4.69, z=-478.88]]
> 	Chunk stats: MultiplayerChunkCache: 575, 575
> 	Level seed: 0
> 	Level generator: ID 01 - flat, ver 0. Features enabled: false
> 	Level generator options: 
> 	Level spawn location: World: (-33,4,-463), Chunk: (at 15,0,1 in -3,-29; contains blocks -48,0,-464 to -33,255,-449), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
> 	Level time: 58367 game time, 26651 day time
> 	Level dimension: 0
> 	Level storage version: 0x00000 - Unknown?
> 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
> 	Forced entities: 50 total; [EntitySlime['史莱姆'/6006361, l='MpServer', x=53.84, y=5.00, z=-424.40], EntitySlime['史莱姆'/6379494, l='MpServer', x=-47.08, y=4.00, z=-489.09], EntitySlime['史莱姆'/5921105, l='MpServer', x=18.29, y=4.00, z=-484.74], EntitySlime['史莱姆'/6373744, l='MpServer', x=18.61, y=5.18, z=-518.99], EntityZombie['僵尸'/5622599, l='MpServer', x=-15.31, y=4.00, z=-506.43], EntityCreeper['爬行者'/5622595, l='MpServer', x=-26.15, y=4.00, z=-498.42], EntitySlime['史莱姆'/5957452, l='MpServer', x=48.97, y=5.10, z=-480.29], EntitySheep['羊'/23, l='MpServer', x=-99.42, y=4.00, z=-486.60], EntityCow['牛'/26, l='MpServer', x=-102.92, y=4.00, z=-474.12], EntitySlime['史莱姆'/6393339, l='MpServer', x=-63.66, y=4.00, z=-407.05], EntitySlime['史莱姆'/6369916, l='MpServer', x=-57.66, y=4.53, z=-431.98], EntityHorse['马'/31, l='MpServer', x=-83.02, y=4.00, z=-515.15], EntityCow['牛'/32, l='MpServer', x=-82.31, y=4.00, z=-511.91], EntitySlime['史莱姆'/6277500, l='MpServer', x=13.27, y=4.52, z=-494.39], EntityItem['item.item.arrow'/5887613, l='MpServer', x=3.98, y=4.00, z=-438.15], EntityCow['牛'/37, l='MpServer', x=-78.48, y=4.00, z=-516.62], EntityCow['牛'/38, l='MpServer', x=-72.92, y=4.00, z=-516.83], EntitySlime['史莱姆'/6355782, l='MpServer', x=-57.15, y=4.00, z=-500.70], EntityItem['item.item.bone'/5887614, l='MpServer', x=2.66, y=4.00, z=-437.61], EntitySlime['史莱姆'/6262901, l='MpServer', x=-61.83, y=4.95, z=-539.62], EntitySlime['史莱姆'/6361677, l='MpServer', x=41.84, y=4.00, z=-516.61], EntitySlime['史莱姆'/6071027, l='MpServer', x=-74.60, y=4.00, z=-467.22], EntitySlime['史莱姆'/6357460, l='MpServer', x=-11.76, y=5.02, z=-511.93], EntityItem['item.item.rottenFlesh'/5909357, l='MpServer', x=-64.40, y=4.00, z=-432.91], EntitySlime['史莱姆'/5900131, l='MpServer', x=-10.11, y=4.95, z=-499.67], EntitySlime['史莱姆'/6283238, l='MpServer', x=-8.98, y=4.00, z=-513.02], EntityChicken['鸡'/58, l='MpServer', x=-32.78, y=4.00, z=-402.00], EntityItem['item.item.rottenFlesh'/5914470, l='MpServer', x=-11.70, y=4.00, z=-500.96], EntitySlime['史莱姆'/6292829, l='MpServer', x=-58.82, y=5.08, z=-505.86], EntitySlime['史莱姆'/6383452, l='MpServer', x=45.46, y=4.00, z=-449.27], EntitySlime['史莱姆'/2842351, l='MpServer', x=-16.67, y=4.72, z=-494.10], EntitySlime['史莱姆'/6302628, l='MpServer', x=-56.79, y=5.08, z=-486.11], EntitySlime['史莱姆'/6412331, l='MpServer', x=-63.75, y=4.00, z=-428.42], EntitySlime['史莱姆'/2574955, l='MpServer', x=-18.48, y=4.00, z=-473.13], EntitySlime['史莱姆'/5923734, l='MpServer', x=-29.24, y=4.00, z=-514.52], EntitySheep['羊'/77, l='MpServer', x=-20.02, y=4.00, z=-400.84], EntitySlime['史莱姆'/6393262, l='MpServer', x=24.68, y=4.67, z=-519.19], EntitySlime['史莱姆'/6346544, l='MpServer', x=-69.23, y=4.00, z=-536.77], EntityPig['猪'/86, l='MpServer', x=-7.84, y=4.00, z=-401.52], EntityItem['item.item.arrow'/5878671, l='MpServer', x=-32.00, y=4.00, z=-482.22], EntitySlime['史莱姆'/6118919, l='MpServer', x=41.29, y=5.17, z=-527.16], EntitySlime['史莱姆'/6357437, l='MpServer', x=-50.81, y=4.00, z=-496.41], EntityPlayerSP['wohaopa'/131, l='MpServer', x=-24.87, y=4.69, z=-478.88], EntitySlime['史莱姆'/5940025, l='MpServer', x=0.12, y=4.72, z=-518.32], EntitySlime['史莱姆'/6380930, l='MpServer', x=29.45, y=4.92, z=-522.81], EntitySlime['史莱姆'/6321291, l='MpServer', x=15.33, y=4.00, z=-509.50], EntitySlime['史莱姆'/5790124, l='MpServer', x=-59.35, y=4.00, z=-509.25], EntitySlime['史莱姆'/6383643, l='MpServer', x=49.68, y=4.00, z=-417.70], EntitySlime['史莱姆'/6080034, l='MpServer', x=-56.53, y=4.80, z=-480.13], EntitySlime['史莱姆'/6219936, l='MpServer', x=-52.45, y=4.34, z=-494.50]]
> 	Retry entities: 0 total; []
> 	Server brand: fml,forge
> 	Server type: Integrated singleplayer server
> Stacktrace:
> 	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
> 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_181, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 330882816 bytes (315 MB) / 687865856 bytes (656 MB) up to 4294967296 bytes (4096 MB)
> 	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.42 Powered by Forge 14.23.4.2759 5 mods loaded, 5 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State     | ID             | Version      | Source                                | Signature                                |
> 	|:--------- |:-------------- |:------------ |:------------------------------------- |:---------------------------------------- |
> 	| UCHIJAAAA | minecraft      | 1.12.2       | minecraft.jar                         | None                                     |
> 	| UCHIJAAAA | mcp            | 9.42         | minecraft.jar                         | None                                     |
> 	| UCHIJAAAA | FML            | 8.0.99.99    | forge-1.12.2-14.23.4.2759.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJAAAA | forge          | 14.23.4.2759 | forge-1.12.2-14.23.4.2759.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJAAAA | storagenetwork | 1.4.0        | SimpleStorageNetwork-1.12.2-1.4.0.jar | None                                     |
> 
> 	Loaded coremods (and transformers): 
> 	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.82' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
> 	Launched Version: HMCL 3.2.104
> 	LWJGL: 2.9.4
> 	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.82, NVIDIA Corporation
> 	GL Caps: Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> 	Type: Client (map_client.txt)
> 	Resource Packs: Minecraft-Mod-Language-Modpack.zip
> 	Current Language: 简体中文 (中国)
> 	Profiler Position: N/A (disabled)
> 	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

**Comment by PrinceOfAmber** [comment]
Yep there was a change in JEI so certain versions dont play well together, they have to be matching APIs for this issue, upgrade to newest JEI

Resolved in newer versions of both mods, More info in report here https://github.com/PrinceOfAmber/Storage-Network/issues/94
https://github.com/PrinceOfAmber/Storage-Network/issues/88
