### ISSUE TITLE
[1.12.2-1.5.2] Massing crafting w/ remote deletes all but one item

### ISSUE THREAD

**Issue by kreezxil** [PrinceOfAmber/Storage-Network#119]
Minecraft version & Mod Version:
1.12.2-14.23.5.2772
1.12.2-1.5.2

Single player or Server:
Server and Single

Describe problem (what you were doing / what happened):
My players are reporting that when they use the storage remote to mass craft items that all but the last item that can be created is deleted.

Crash log (if any):
None that I know of, I'll test this personally to see if I can generate some data for you.

![image](https://user-images.githubusercontent.com/3880072/47301285-2c762480-d5e4-11e8-89b4-dcbd1e0c39c4.png)
![image](https://user-images.githubusercontent.com/3880072/47301324-3e57c780-d5e4-11e8-98d7-2af1dab9a0cf.png)

**Comment by PrinceOfAmber** [comment]
Did you have FastBench installed? Some changes were added for performance, so things act differenlty with and without . https://minecraft.curseforge.com/projects/fastworkbench

First ill do a test with fastbench. recorded using https://www.screentogif.com/
Forge  2705

![with fastbench](https://user-images.githubusercontent.com/621529/47699183-4fe63400-dbcf-11e8-84b1-93d596292cb9.gif)

**Comment by PrinceOfAmber** [comment]
Yep when i uninstalled fastbench i see this bug, not just logs either.  and not just the remote.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2633942
