### ISSUE TITLE
1.12-1.0.5 crashes dedicated server Forge 1.12 build 2382

### ISSUE THREAD

**Issue by kreezxil** [PrinceOfAmber/Storage-Network#12]
Notes:
     on startup

crash report:
https://gist.github.com/94b4bdf74830ee34b3a25207419b17ec

fml server latest:
https://gist.github.com/67e62c0f4553f625896a945ab1b5a60d

possibly related: #11

**Comment by PrinceOfAmber** [comment]
Yep as seen here  https://github.com/PrinceOfAmber/Storage-Network/issues/11 forge deleted the old registry system and made a new one. you may see issues with tons of mods until they update. my updates are coming soon

**Comment by PrinceOfAmber** [comment]
Thanks for all the logs!  https://minecraft.curseforge.com/projects/simple-storage-network/files/2443586
