### ISSUE TITLE
Clicking the clear search button crashes

### ISSUE THREAD

**Issue by Muddr** [PrinceOfAmber/Storage-Network#120]
Minecraft version & Mod Version:
MC: 1.12.2
Mod: 1.5.2

Single player or Server:
Tested Single.

Describe problem (what you were doing / what happened):
Clicking the `X (Clear Search)` button crashes game if JEI isn't installed.  

Crash log (if any):
https://pastebin.com/hQbPRmN6

I wouldn't assume that a mod is installed if it isn't marked as a dependency

**Comment by PrinceOfAmber** [comment]
Somehow the mod thought you had JEI installed when you didnt, oops :D

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2633942
