### ISSUE TITLE
Crash involving OreDict

### ISSUE THREAD

**Issue by Muddr** [PrinceOfAmber/Storage-Network#121]
Minecraft version & Mod Version:
MC: 1.12.2
Mod: 1.5.2

Single player or Server:
Tested Single.

Describe problem (what you were doing / what happened):
Trying to access `Storage Request Table` with the following setup will cause game to crash. 

Chest Inventory
![2018-10-24_20 27 23](https://user-images.githubusercontent.com/1361860/47468958-58ec9500-d7cc-11e8-91ac-9be5846a5666.png)

Storage Link Cable Settings
![2018-10-24_20 27 38](https://user-images.githubusercontent.com/1361860/47468979-74f03680-d7cc-11e8-846a-0ca9e4c885cb.png)

Crash log (if any):
https://pastebin.com/7VEU5mL8

**Comment by PrinceOfAmber** [comment]
Fix on the way in 1.5.3.

Bug was because somehow it got a hold of an Empty itemstack (basically an empty slot) and tried to look up ore dict data.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2633942
