### ISSUE TITLE
Recipe Killer. After crafting some hoppers, the recipe is gone. Even with vanilla crafting table.

### ISSUE THREAD

**Issue by Knito58** [PrinceOfAmber/Storage-Network#13]
MC 1.12
Forge 14.21.1.2389
Simple Storage Network 1.12-1.0.6
Survival Single Player

I missed some recipes from time to time and didn't realize it was due to the Storage Request Table of this mod. Now I can re-do the necessary steps to reproduce vanishing recipes.

Let's make the hopper recipe vanishing:

1. Have some chests and some iron bars in the storage.
2. Fill the hopper recipe into the Storage Request Table's grid using JEI's plus sign.
3. Craft hoppers until the result slot of the request table stays empty.
4. Now go to any other crafting device: None of them can craft any hopper any more. Even the vanilla crafting table will now refuse to craft a hopper. The Storage Request Table will also not know anything about crafting hoppers any more.

To re-enable the hopper recipe I have to start from scratch. "Save and Quit to Title" will not be enough if I re-enter the world with "Singleplayer". In fact, I have to "Quit Game" and restart the launcher.

Of course, this feature not only works with the hopper recipe, but also with others, like the vanilla repeater.

**Comment by Knito58** [comment]
1. Not "bars" - meaning iron ingots instead.

**Comment by revdave33** [comment]
I experienced this as well.

**Comment by PrinceOfAmber** [comment]
I will check this out

**Comment by PrinceOfAmber** [comment]
I put a fix out. https://minecraft.curseforge.com/projects/simple-storage-network/files/2446097

But please let me know if this somehow doesnt fix it, or it happens again and i will take another look

**Comment by Knito58** [comment]
So I was lucky to be able to see the bug because of the amount of ingredients I had?
I'll try this out and report any issues.
Thank you very much.

**Comment by Knito58** [comment]
Uh oh - something new! Seems to be a new issue. Weird.

**Comment by PrinceOfAmber** [comment]
"Uh oh - something new! Seems to be a new issue. Weird."

Whats this?
