### ISSUE TITLE
Importer Disappears

### ISSUE THREAD

**Issue by revdave33** [PrinceOfAmber/Storage-Network#14]
MC 1.12
Forge 14.21.1.2389
Simple Storage Network 1.12-1.0.6
Survival Single Player

I craft some of the importers to use to dump things into my network. In placing the importer, they disappear. Gone, gone, gone.

Even logging out, and starting over again does not restore them. They simply disappear.

**Comment by PrinceOfAmber** [comment]
Thanks im looking into it.

**Comment by PrinceOfAmber** [comment]
Hey im just trying to replicate this bug but it seems like the importer works for me. I am going to record  and upload an unlisted youtube video to show what im doing... Maybe im doing it differnetly than you?

in the meantime... I might need more clarification of the steps you are taking. Or maybe a modlist in case something else is conflicting?  Maybe your network is more complex than that test one i did?
