### ISSUE TITLE
Ingredients Killer. Negates ingredients which are in the player's inventory.

### ISSUE THREAD

**Issue by Knito58** [PrinceOfAmber/Storage-Network#16]
Tried to craft two keys for storage drawers with the Storage Request Table.
First I made the "upgrade template" which gives 2 of them. This should have been enough to craft two keys.
I let the templates stay in the inventory and used JEI to put the recipe for the "drawer key" in. This recipe needs two additional gold ingots and one gold nugget.
After crafting the key, the second leftover template was gone.
Ok. I need two keys, a drawer key and a quantifier key. To have the quantifier key I first have to craft another drawer key.
Again I crafted two templates. Then I separeated the two templates in the inventory to sse if the negation only happens stack-wise.
Crafting the second key also ate both of the templates, although they were in different slots.

**Comment by PrinceOfAmber** [comment]
Yep, i just also made this happen with vanilla items.

1. have iron in the network
2. have zero chest sin network.
3 have two stacks of size 1 of chests in your inventory
4 have request table recipe empty
5 search JEI for hopper, use + sign

Actual result: 5 iron for recipe goes into slots, middle recipe slot is empty where chest SHOULD be.  But at the same time one of the two chests from my inventory is deleted


expected result: hopper recipe is fully filled, one of the chests is in grid and one remains.

**Comment by Knito58** [comment]
Yay! Looks clean now. I'm not very clear how the request Table should react when the ingredients are in the player's inventory and not in storage but this seems to work way more correctly than before. Sometimes I have a strange feeling as if something went wrong but I believe I'm hyper-sensitive now. I believe its complicated to set up the rules for each ingredient which may arrive in the RT from different places - or not.

Greetings, Konitor
