### ISSUE TITLE
Crash when placing request table.

### ISSUE THREAD

**Issue by Knito58** [PrinceOfAmber/Storage-Network#17]
I'm very sorry to have to report this. I made a second base 6500m away from the starting base. When the game crashed when I first placed the RT, I thought: "Silly me - place the controller first!"

So did I. I let the RT where it was, connected everything and wanted to start crafting. The RT didn't react to the use-command (right-click) anymore and was stuck. I picked it up using a pickaxe and replaced it.

The game crashed. Here's the crash report:

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.94.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  AstralCore (astralsorcery-1.5.8.jar)
  LoadingPlugin (RandomThings-MC1.12-4.0.1.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  CXLibraryCore (cxlibrary-1.12-1.5.0.jar)
  LoadingPlugin (Quark-r1.2-99.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 7/6/17 2:51 PM
Description: Exception ticking world

java.lang.NullPointerException: Null string not allowed
	at java.util.Objects.requireNonNull(Objects.java:228)
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:137)
	at mrriegel.storagenetwork.request.TileRequest.func_189515_b(TileRequest.java:42)
	at mrriegel.storagenetwork.tile.TileConnectable.func_189518_D_(TileConnectable.java:46)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:287)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:249)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:226)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:228)
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:137)
	at mrriegel.storagenetwork.request.TileRequest.func_189515_b(TileRequest.java:42)
	at mrriegel.storagenetwork.tile.TileConnectable.func_189518_D_(TileConnectable.java:46)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:287)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:249)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:226)

-- Affected level --
Details:
	Level name: Farmerama
	All players: 1 total; [EntityPlayerMP['Konitor'/80, l='Farmerama', x=-178.87, y=72.00, z=6610.78]]
	Chunk stats: ServerChunkCache: 1345 Drop: 0
	Level seed: 894667602
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (176,64,256), Chunk: (at 0,4,0 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3252304 game time, 2983516677 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 77838 (now: false), thunder time: 108189 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1494106344 bytes (1424 MB) / 3505172480 bytes (3342 MB) up to 5315035136 bytes (5068 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.40 Powered by Forge 14.21.1.2395 81 mods loaded, 81 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2395.jar) 
	UCHIJAAAA	forge{14.21.1.2395} [Minecraft Forge] (forge-1.12-14.21.1.2395.jar) 
	UCHIJAAAA	aroma1997core{1.3.0.0.b94} [Aroma1997Core] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCHIJAAAA	actuallyadditions{1.12-r113} [Actually Additions] (ActuallyAdditions-1.12-r113.jar) 
	UCHIJAAAA	aroma1997corehelper{1.3.0.0.b94} [Aroma1997Core|Helper] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCHIJAAAA	aroma1997sdimension{1.3.0.0.b37} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar) 
	UCHIJAAAA	astralsorcery{1.5.8} [Astral Sorcery] (astralsorcery-1.5.8.jar) 
	UCHIJAAAA	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UCHIJAAAA	atmlib{1.2.0} [ATM Lib] (atmlib-1.2.0.jar) 
	UCHIJAAAA	quark{r1.2-99} [Quark] (Quark-r1.2-99.jar) 
	UCHIJAAAA	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar) 
	UCHIJAAAA	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UCHIJAAAA	bookshelf{2.0.412} [Bookshelf] (Bookshelf-1.12-2.0.0.412.jar) 
	UCHIJAAAA	calculations{1.1.0} [Calculations] (Calculations-1.12-1.1.0.jar) 
	UCHIJAAAA	chameleon{1.12-4.1.0} [Chameleon] (Chameleon-1.12-4.1.0.jar) 
	UCHIJAAAA	codechickenlib{3.1.0.278} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.0.278-universal.jar) 
	UCHIJAAAA	redstoneflux{2.0.0} [Redstone Flux] (RedstoneFlux-1.12-2.0.0.1-universal.jar) 
	UCHIJAAAA	cofhcore{4.3.0} [CoFH Core] (CoFHCore-1.12-4.3.0.5-universal.jar) 
	UCHIJAAAA	cofhworld{1.0.0} [CoFH World] (CoFHWorld-1.12-1.0.0.5-universal.jar) 
	UCHIJAAAA	cxlibrary{1.5.0} [CXLibrary] (cxlibrary-1.12-1.5.0.jar) 
	UCHIJAAAA	jei{4.7.1.71} [Just Enough Items] (jei_1.12-4.7.1.71.jar) 
	UCHIJAAAA	darkutils{1.6.158} [Dark Utilities] (DarkUtils-1.12-1.6.158.jar) 
	UCHIJAAAA	forestry{5.4.3.128} [Forestry] (forestry_1.12-5.4.3.128.jar) 
	UCHIJAAAA	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCHIJAAAA	refinedstorage{1.5.7} [Refined Storage] (refinedstorage-1.5.7.jar) 
	UCHIJAAAA	growablecells{1.1.0} [Growable Cells] (Growable Cells-1.12-2.2.0.jar) 
	UCHIJAAAA	intwheel{1.2.7} [Interaction Wheel] (intwheel-1.12-1.2.7.jar) 
	UCHIJAAAA	inventorytweaks{1.63+dev.94.3cdd29e} [Inventory Tweaks] (InventoryTweaks-1.63+dev.94.jar) 
	UCHIJAAAA	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCHIJAAAA	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCHIJAAAA	llor{1.1.4-mc1.12} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.4-mc1.12.jar) 
	UCHIJAAAA	lostcities{0.0.15beta} [The Lost Cities] (lostcities-1.12-0.0.15beta.jar) 
	UCHIJAAAA	morefurnaces{1.10.1} [More Furnaces] (MoreFurnaces-1.12-1.10.1.jar) 
	UCHIJAAAA	shetiphiancore{3.5.0.1} [ShetiPhian-Core] (shetiphiancore-1.12.0-3.5.0.1.jar) 
	UCHIJAAAA	multistorage{1.4.0.1} [Multi-Storage] (multistorage-1.12.0-1.4.0.1.jar) 
	UCHIJAAAA	mysticalagriculture{1.6.1} [Mystical Agriculture] (mysticalagriculture[1.12]-1.6.1.jar) 
	UCHIJAAAA	neat{1.4-15} [Neat] (Neat 1.4-15.jar) 
	UCHIJAAAA	notenoughwands{1.5.8} [Not Enough Wands] (notenoughwands-1.12-1.5.8.jar) 
	UCHIJAAAA	notes{1.1.1} [Notes] (Notes-1.12-1.1.1.jar) 
	UCHIJAAAA	omegacraft{1.0.0} [Omega Craft] (Omega Craft 2.2.1 - 1.12.jar) 
	UCHIJAAAA	packetfilter{1.6.3} [Packet Filter] (packetfilter-1.6.3.jar) 
	UCHIJAAAA	petbat{1.4.7} [Pet Bat] (PetBat-1.12.jar) 
	UCHIJAAAA	platforms{1.4.0.1} [Platforms] (platforms-1.12.0-1.4.0.1.jar) 
	UCHIJAAAA	reborncore{3.2.3.83} [Reborn Core] (RebornCore-1.12-3.2.3.83-universal.jar) 
	UCHIJAAAA	quantumstorage{4.3.4} [QuantumStorage] (QuantumStorage-1.12-4.3.4.jar) 
	UCHIJAAAA	randomthings{4.0.1} [Random Things] (RandomThings-MC1.12-4.0.1.jar) 
	UCHIJAAAA	refinedrelocation{4.1.4} [Refined Relocation] (RefinedRelocation_1.12-4.1.4.jar) 
	UCHIJAAAA	rftools{6.10} [RFTools] (rftools-1.12-6.10beta3.jar) 
	UCHIJAAAA	roots{0.024} [Roots 2] (roots-2-0.024.jar) 
	UCHIJAAAA	ayanokeikorftl{0.0.4} [Rotten Flesh To Leather Mod] (RottenFleshToLeather [0.0.4].jar) 
	UCHIJAAAA	scannable{1.4.0.5} [Scannable] (Scannable-MC1.12-1.4.0.5.jar) 
	UCHIJAAAA	icc{0.2.1} [Simple Item Collector Chest] (Simple Item Collector Chest-0.2.1.jar) 
	UCHIJAAAA	simplevoidworld{1.2.0.1} [SimpleVoidWorld] (Simple-Void-World-1.12-1.2.0.1-universal.jar) 
	UCHIJAAAA	simplegrinder{4.015.A112} [Simple Grinder] (SimpleGrinder-4.050.R112.jar) 
	UCHIJAAAA	storagenetwork{1.0.0} [Simple Storage Network] (SimpleStorageNetwork-1.12-1.0.8.jar) 
	UCHIJAAAA	simplyhaxentitydump{1.12} [Simply Hax Entity Dump] (SimplyHax-1.12.jar) 
	UCHIJAAAA	simplyhaxflying{1.12} [Simply Hax Flying] (SimplyHax-1.12.jar) 
	UCHIJAAAA	storagedrawers{1.12-5.1.3} [Storage Drawers] (StorageDrawers-1.12-5.1.3.jar) 
	UCHIJAAAA	superminer_core{2.5.33.325} [SuperMiner] (SuperMiner-2.5.33.325.jar) 
	UCHIJAAAA	superminer_captivator{[1.12]-2.5.33.325} [SuperMiner Captivator] (SuperMiner-2.5.33.325.jar) 
	UCHIJAAAA	superminer_cropinator{[1.12]-2.5.33.325} [SuperMiner Copinator] (SuperMiner-2.5.33.325.jar) 
	UCHIJAAAA	superminer_excavator{[1.12]-2.5.33.325} [SuperMiner Excavator] (SuperMiner-2.5.33.325.jar) 
	UCHIJAAAA	superminer_illuminator{[1.12]-2.5.33.325} [SuperMiner Illuminator] (SuperMiner-2.5.33.325.jar) 
	UCHIJAAAA	superminer_lumbinator{[1.12]-2.5.33.325} [SuperMiner Lumbinator] (SuperMiner-2.5.33.325.jar) 
	UCHIJAAAA	superminer_shaftanator{[1.12]-2.5.33.325} [SuperMiner Shaftanator] (SuperMiner-2.5.33.325.jar) 
	UCHIJAAAA	superminer_substitutor{[1.12]-2.5.33.325} [SuperMiner Substitutor] (SuperMiner-2.5.33.325.jar) 
	UCHIJAAAA	superminer_veinator{[1.12]-2.5.33.325} [SuperMiner Veinator] (SuperMiner-2.5.33.325.jar) 
	UCHIJAAAA	theoneprobe{1.4.11} [The One Probe] (theoneprobe-1.12-1.4.11.jar) 
	UCHIJAAAA	thermalfoundation{2.3.0} [Thermal Foundation] (ThermalFoundation-1.12-2.3.0.3-universal.jar) 
	UCHIJAAAA	thermaldynamics{2.3.0} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.0.4-universal.jar) 
	UCHIJAAAA	thermalexpansion{5.3.0} [Thermal Expansion] (ThermalExpansion-1.12-5.3.0.4-universal.jar) 
	UCHIJAAAA	vtweaks{1.4.11.3} [V-Tweaks] (VTweaks-1.12-1.4.11.3.jar) 
	UCHIJAAAA	waterpower{@MODVERSION@} [WaterPower] (WaterPower-1.12-0.5.2.jar) 
	UCHIJAAAA	wearablebackpacks{3.0.3} [Wearable Backpacks] (WearableBackpacks-1.12-3.0.3.jar) 
	UCHIJAAAA	witherskelefix{2.2.2} [Wither Skeleton Tweaks] (Wither Skeleton Tweaks-1.12-2.2.2.jar) 
	UCHIJAAAA	wts{1.1.0} [What's That Slot] (WTS-1.1.0.jar) 
	UCHIJAAAA	xnet{1.3.4.3} [XNet] (xnet-1.12-1.3.4.3.jar) 
	UCHIJAAAA	yukarilib{1.3.0-beta} [YukariLib] (YukariLib-1.12-1.3.0-b0.jar) 
	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.94.jar)
  invtweaks.forge.asm.ContainerTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  shetiphian.asm.ClassTransformer
CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  
AstralCore (astralsorcery-1.5.8.jar)
  
LoadingPlugin (RandomThings-MC1.12-4.0.1.jar)
  lumien.randomthings.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.5.0.jar)
  
CXLibraryCore (cxlibrary-1.12-1.5.0.jar)
  cubex2.cxlibrary.CoreModTransformer
LoadingPlugin (Quark-r1.2-99.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.2.3.83
		Runtime Debofucsation 1
		RenderEngine: 0
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Konitor'/80, l='Farmerama', x=-178.87, y=72.00, z=6610.78]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by Knito58** [comment]
Upps - the world cannot be loaded anymore. Crashing now when loading the world.

The crash report ist slightly diffent and now shows TileConnectable Line 18 instead of Line 46 as above.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.94.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  AstralCore (astralsorcery-1.5.8.jar)
  LoadingPlugin (RandomThings-MC1.12-4.0.1.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  CXLibraryCore (cxlibrary-1.12-1.5.0.jar)
  LoadingPlugin (Quark-r1.2-99.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 7/6/17 3:05 PM
Description: Exception ticking world

java.lang.NullPointerException: Null string not allowed
	at java.util.Objects.requireNonNull(Objects.java:228)
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:137)
	at mrriegel.storagenetwork.request.TileRequest.func_189515_b(TileRequest.java:42)
	at mrriegel.storagenetwork.tile.TileConnectable.func_189517_E_(TileConnectable.java:18)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:156)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:226)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:228)
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:137)
	at mrriegel.storagenetwork.request.TileRequest.func_189515_b(TileRequest.java:42)
	at mrriegel.storagenetwork.tile.TileConnectable.func_189517_E_(TileConnectable.java:18)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:156)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:226)

**Comment by Knito58** [comment]
... No backup. Sigh...

**Comment by PrinceOfAmber** [comment]
Sorry i will get a fix out in a few hours

**Comment by PrinceOfAmber** [comment]
Hey sorry i didn't get to this right away.

Fix is out 

https://minecraft.curseforge.com/projects/simple-storage-network/files/2447410

 so your old world is fine as well as any future ones.

**Comment by Knito58** [comment]
Yay! World can be loaded again. Thank you very much!
