### ISSUE TITLE
crash when automating ore processing with SN and TE(1.12)

### ISSUE THREAD

**Issue by SDUBZ** [PrinceOfAmber/Storage-Network#18]
Forge: 1.12-2405
TD:-1.12-2.3.1.6
TE: -1.12-5.3.1.6-universal
SN:1.12-1.0.10
crash report:
https://github.com/CoFH/Feedback/files/1133791/crash-2017-07-09_23.48.02-server.txt 

as quoted by other mod dev here https://github.com/CoFH/Feedback/issues/358#event-1155818936
SN cables trying to query a duct for a value it doesn't have.

**Comment by PrinceOfAmber** [comment]
Sorry this took a while, working on it now

**Comment by PrinceOfAmber** [comment]
Without fixing anything, ore processing seems to work at least on a basic level with the furnace.  Even so based on the crash log i can put in some safety tests to stop this happening in more strange situations

![2017-07-15_21 04 51](https://user-images.githubusercontent.com/621529/28244488-45044a5a-69a1-11e7-8dc2-2928fab058bc.png)

**Comment by PrinceOfAmber** [comment]
New build should help , check it out. make a new issue if anything else happens :)  https://minecraft.curseforge.com/projects/simple-storage-network/files/2451418
