### ISSUE TITLE
Request Table Compatibility with Storage Drawers

### ISSUE THREAD

**Issue by aelfwyne** [PrinceOfAmber/Storage-Network#19]
Minecraft 1.11.2
Storage-Network 1.0.5

Connecting the Simple Storage Network to a Storage Drawers controller works, but is buggy.

1) Many items in storage drawers simply do not show up in the Request Table. There are many "blank spaces" that are probably where these items go, but I'm not sure. All I know is they do not show up. No rhyme or reason to what items fail to show - they can be vanilla or modded. Also seems to happen with basic drawers as well as compacting drawers.

2) If a storage drawer has, say, 1000 items in it, removing 1 stack will make the entire item entry disappear from the Request Table. If you add the stack back, then it will reappear. Makes it very difficult to remove more than 1 stack.

**Comment by PrinceOfAmber** [comment]
What version of storate drawers were you using? Looks like it had a bunch of updates recently. ill test everything out with 5.2.8    https://minecraft.curseforge.com/projects/storage-drawers/files/2448797

**Comment by PrinceOfAmber** [comment]
Ok got it all fixed up. Please make new issue if anything else comes up.  https://minecraft.curseforge.com/projects/simple-storage-network/files/2451418

**Comment by aelfwyne** [comment]
Thanks for following up! I got busy with work and didn't get a chance to check the issue again until today. Will test in game this weekend.
