### ISSUE TITLE
Simple Storage Network Crash

### ISSUE THREAD

**Issue by knoxhack** [PrinceOfAmber/Storage-Network#195]
Describe the bug
Simple Storage Network crashes anytime you try to use it.

To Reproduce

Create any simple storage network and connect a storage request table or connect a storage remote, then attempt to interact with said network

Desktop (please complete the following information):

OS: Win10, 64bit
Modpack (please complete the following information):

Version: Mystical Skies v1.7.1

Crash Report: https://paste.dimdev.org/dehosuxigu.mccrash

**Comment by knoxhack** [comment]
https://github.com/NFINIT-Development/mystical-skies/issues/67

**Comment by Lothrazar** [comment]
You can fix this by either deleting | FastWorkbench-1.12.2-1.6.1.jar  or updating to version 1.7.0 or higher
