### ISSUE TITLE
'Move Items' is always enabled

### ISSUE THREAD

**Issue by Spongman** [PrinceOfAmber/Storage-Network#196]
Minecraft version & Mod Version: SimpleStorageNetwork-1.12.2-1.7.6

Single player or Server: single

Describe problem (what you were doing / what happened):

in JEI, the 'Move Items' button is always enabled, regardless of whether or not the items to be moved are in the storage network.

here's a vanilla Crafting Table in JEI: 
![image](https://user-images.githubusercontent.com/1088194/59993549-7dbc3500-9605-11e9-9acd-0b8df62e2db5.png)

see how JEI highlights the missing items and the 'Move Items' button is disabled. this is extremely useful when crafting as it immediately shows me that i need to find/craft those ingredients first.

here's the Storage Request Table:
![image](https://user-images.githubusercontent.com/1088194/59993579-a0e6e480-9605-11e9-9b9d-4c42ffccc997.png)

notice how the 'Move Items' button is enabled, even though the storage network is completely empty.

----

interestingly, the 'Smelting' tab also has an enabled 'Move Items' button, even though the storage network isn't a smelting device. is this a separate bug.

![image](https://user-images.githubusercontent.com/1088194/59993781-53b74280-9606-11e9-8196-24ff7d0a2a37.png)

**Comment by Lothrazar** [comment]
Yea it seemed like a waste to punnish the user and scan the ENTIRE network just for clicking on a recipe. because it has to scan again anyway when you actually craft.

If there was a way to make this work imagine performance would suffer

**Comment by Lothrazar** [comment]
works as intended for now and everyones used to it in 1.12 anyway
