### ISSUE TITLE
Storage network master causing massive tps lag (25ms/t)

### ISSUE THREAD

**Issue by RedBlockCreator** [PrinceOfAmber/Storage-Network#198]
Minecraft version & Mod Version: 1.12.2 1.7.7

Single player or Server: Server

Describe problem (what you were doing / what happened):
Storage Network causing massive tick lag on server with 100+ small storage crates installed.
(about  25ms/t) I am not sure how you made the mod but I am assuming it is updating its index of items every tick. Maybe try to lower it to once every 20 ticks or make it so it updates its index once when the master is placed and only whenever an inventory has stuff put in it past then?

Crash log (if any):
Doesn't cause a crash, but is extremely tps laggy

**Comment by johnfriedrich** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/4679374/64487837-dfbd2b80-d23f-11e9-870a-764dd4e5c22f.jpg)
extremely laggy is an underestimation. It's catastrophic.
1.12.2-1.7.6

**Comment by Rahmiel** [comment]
Can confirm this issue, was having severe server tps lag, had to get Lag Goggles to find the issue. The server went from 90 ms mean tick time down to 30 after breaking the Storage Network Master. This is kind of game-breaking. Just to note I'm on version mc1.12.2 mod1.7.8

**Comment by Rahmiel** [comment]
Just tested version 1.7.9 in 1.12.2 and it is still consistently creating massive tps lag. This issue is bad, and someone needs to look into it if you care at all about the most actively used version of the mod. I know 1.14 is out and such, but this is completely game-breaking for multiplayer use.

**Comment by Rahmiel** [comment]
Figured out the issue, noticed others did not put this here either. I believe the issue is with any type of large storage chest. This issue has been noted a lot in SkyFactory 4, the issue is anytime you connect a single super large inventory (I.E. Filing Cabinet or Colossal Chest) to a network. The issue gets even more interesting, since the size of the inventory and item count, both matter. Say for example I have 100,000 items in one 5x5x5 Colossal Chest, which will cause horrendous lag, but if I put the same 100,000 items in a 3x3x3 Colossal Chest, the lag is much less with a difference of close to 40 ms per tick WHICH IS A LOT. I'm not sure if this is fixable or just an intrinsic bug with this type of storage system (because a lot of people complain it happens with Refined Storage and AE2 as well).

**Comment by RedBlockCreator** [comment]
We noticed it with storage crates from Actually Additions

**Comment by zetix** [comment]
Is there any other storage mod in Sky Factory 4 without this issue?

**Comment by nogamenofun98** [comment]
MC: 1.12.2
Modpack version: Roguelike Adventures and Dungeons R.A.D. - 1.37
simple network version: SimpleStorageNetwork-1.12.2-1.7.10

in RAD (roguelike adventure) modpack, when storage link cable connect to huge colossal chest like 5x5x5 diamond level, the storage network master show potential empty slot is 21,000. When the colossal chest is connected to the network, whatever item i take out from the network via storage request table or remote, it will cause server to spike lag. 

If i disconnect the colossal chest from the network, it show potential empty slot with 5000, then i try take out item from the network, it become very fast and responsive. 

![image](https://user-images.githubusercontent.com/9070825/80273836-5db73f80-8708-11ea-84d2-0f53dbf39329.png)


if i separate that huge chest to another network, then the speed to take out item become faster, but still can feel the slowness, previously is like need 2 second to take out item, now need 1 second to take out item.
![image](https://user-images.githubusercontent.com/9070825/80273962-7e33c980-8709-11ea-85e7-62a24c451244.png)

**Comment by Lothrazar** [comment]
90% of the ticks reported in tile master are literally it **waiting** for the inventories to respond.  Which is shown in the red list above.  SMeltery took 6k to respond , ItemPump took 4k, etc.    This is why lag goggles is terrible for debugging mods, and sampler is much better

Thanks for all the details, to change this it would need a rewrite. and the mod already had a rewrite for 1.14 + so for 1.12 this is the way it is

**Comment by Exaelitus** [comment]
This happens on LAN also.   @Lothrazar you mentioned to resolve this you would need to "rewrite" and there already was a rewrite for 1.14...  Does that mean this issue is better in 1.14+?   Thank you.

**Comment by Daedrew** [comment]
Uma coisa que percebi tbm, é q os cabos de import e export do sistema tbm causam mto lag, ainda mais se tiverem upgrade de speed

**Comment by DomezTheDragon** [comment]
this is generally an issue for all versions, and i have tested, the same storage holding items, and simple storage network is always the laggiest, AE2 on the otherhand is snappy and instant, little to no lag
