### ISSUE TITLE
[REQUEST] compatibility with other mods

### ISSUE THREAD

**Issue by TheSexyYeti** [PrinceOfAmber/Storage-Network#199]
I love your mod. I personally think your unlimited wireless overworld and dimensional access is the best out of any mod. The only problem is I can't use this in combination with my favorite storage method from Refined Storage. Is there any way to make this mod compatible with mods like Refined Storage, Applied Energistics 2, or at least with the EZ Storage?. Or even better add storage solutions to your mod that have upgradable storage capacity.

**Comment by TheSexyYeti** [comment]
Never mind man. I just found out it works with the Ender-Rift mod.

**Comment by Lothrazar** [comment]
currently compatible with any mod correctly implementing the inventory capabilities of their blocks. for other compatibility see https://github.com/Lothrazar/Storage-Network/issues/72
