### ISSUE TITLE
1.11.2-1.0.0 Client crash when using clicking search on request table

### ISSUE THREAD

**Issue by kreezxil** [PrinceOfAmber/Storage-Network#2]
https://pastebin.com/MxPAZMZm

Steps:

1. Place Storage Master
2. Place some cable
3. Place request table next to a chest
4. click request table
5. click on search box
6. profit (crash) :(

Will cross post to jei because of implication in the crash report

**Comment by PrinceOfAmber** [comment]
Looks like it only works with a specific version of JEI .  so i will fix that but also add some safety logic to prevent failures like this crashing the game, and a config to disable it fully

**Comment by kreezxil** [comment]
thank you. I really want it for my colonial packs as your textures are more of that time period than ez storage 2, plus your mod or rather this mod provides AE2-like functionality.

**Comment by PrinceOfAmber** [comment]
Fixed in latest release, check it out and let me know if anything else breaks

**Comment by kreezxil** [comment]
Will do rusty on Sunday. Thank you so much.
