### ISSUE TITLE
[1.14.3] blocks when broken don't give drops.

### ISSUE THREAD

**Issue by ProsperCraft** [PrinceOfAmber/Storage-Network#200]
Minecraft version & Mod Version:
1.14.3  Forge .51
SimpleStorageNetwork-1.14.3-0.0.2.jar

Single player or Server:
Server

Describe problem (what you were doing / what happened):
When you break blocks from this mod, you don't get the items as a drop.

**Comment by Lothrazar** [comment]
This is why im glad i put out a test build, doing so much creative testing i forgot this isnt built in by default anymore
