### ISSUE TITLE
[1.14.3] opening the Storage request table it forces holding right mouse 

### ISSUE THREAD

**Issue by ProsperCraft** [PrinceOfAmber/Storage-Network#201]
Minecraft version & Mod Version:
SimpleStorageNetwork-1.14.3-0.0.2.jar
Forge .51

Single player or Server:
Server

Describe problem (what you were doing / what happened):
opening Storage Request Table forces you to hold down right click using the items that activate with right click(mine and slash torch in the offhand, or mine and slash staff shoot.

**Comment by Lothrazar** [comment]
so do you mean it places a torch at the same time when it opens?
