### ISSUE TITLE
[1.14.3] Feature request - JEI integration.

### ISSUE THREAD

**Issue by ProsperCraft** [PrinceOfAmber/Storage-Network#202]
Minecraft version & Mod Version:
SimpleStorageNetwork-1.14.3-0.0.2
forge .51

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Unable to + click recipes from jei into the Storage request table.

**Comment by Lothrazar** [comment]
This will be coming soon, but unless im looking in the wrong place Mezz doesnt have a maven for 1.14.x  yet 

https://modmaven.k-4u.nl/mezz/jei/

**Comment by Zelif** [comment]
The link you are using is an mirror that I guess he might not keep updated :D 
He does have a 1.14.3 found here:
**The URL:**
https://dvs1.progwml6.com/files/maven/mezz/jei/jei-1.14.3/

Is not allowed to be browsed but can be used to point to. 
**Issue:**
https://github.com/mezz/JustEnoughItems/issues/1624

**Example:** 
https://dvs1.progwml6.com/files/maven/mezz/jei/jei-1.14.3/maven-metadata.xml

**Comment by Lothrazar** [comment]
Gave this another attempt for 1.14, its really close i must have overlooked something
, not sure what i am doing wrong
https://github.com/mezz/JustEnoughItems/issues/1689

**Comment by Shadows-of-Fire** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/blob/1.14/build.gradle#L50
