### ISSUE TITLE
[1.14.3] Feature request - scroll bar so you can see your items.

### ISSUE THREAD

**Issue by ProsperCraft** [PrinceOfAmber/Storage-Network#206]
Minecraft version & Mod Version:
1.14.3
SimpleStorageNetwork-1.14.3-0.0.3

Single player or Server:
Server

Describe problem (what you were doing / what happened):
When you look in a storage request table you can't scroll to the see the items in your network, only search for them.

![8def77c8e198b61879c99be97bd2dab1](https://user-images.githubusercontent.com/4427684/61487378-027b4400-a963-11e9-9146-4e0467024663.png)

Would love to have a scroll bar so you can browse all items.

**Comment by Lothrazar** [comment]
mouse wheel fix https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/2744209
