### ISSUE TITLE
[1.14.3] Major Dupe Bug

### ISSUE THREAD

**Issue by litjohn50** [PrinceOfAmber/Storage-Network#207]
Minecraft version & Mod Version:
1.14.3-0.0.4

Single player or Server:
Server

Describe problem (what you were doing / what happened):
You can dupe any time, stackable or not by just clicking items in and out of your storage fast. (seems to be prominent on lower tps servers).

Picture:  http://prntscr.com/ohse4y

Video of how to: https://gyazo.com/aaa80a6fd13a65ebeacd65286f637265

**Comment by ProsperCraft** [comment]
Players are finding the Storage Network is duplicating blocks.
SimpleStorageNetwork-1.14.4-0.0.8
forge-1.14.4-28.0.40

**Comment by VeloxAzo** [comment]
Reproducing this bug is very simple, and does not require the item to be stackable. It becomes easier at low TPS thus incentivizes players to attempt to lag servers. 

It also works the other way around and can delete items if you're not careful when using the storage at low TPS.

**Comment by Lothrazar** [comment]
So at about 22 seconds in, are you just spam clicking and it happens right away, it looks like . 

Can you replicate it using a network using only vanilla chests?  I am trying to isolate if its purely a TPS lag issue, or if its a mod compatibliity issue, or mabye even both. 

GIf is just my test in single player .. but this is all you need to do, just left click very fast?  
![207](https://user-images.githubusercontent.com/621529/62677101-ecf5aa80-b961-11e9-8f8a-3548a9f22723.gif)

**Comment by VeloxAzo** [comment]
I'll get you some more screenshots of my setup and a video in a sec.
I use a rapid fire key on my mouse to spam click, and my network uses vanilla chests and a mix of filter + normal nodes.

**Comment by VeloxAzo** [comment]
https://i.imgur.com/kRB0ziu.png
https://i.imgur.com/CItb8Np.png

The bottom chest on the first set is set to priority -1. The rest of the chests have no filter set and only the ones shown have filter links. 

https://gfycat.com/MagnificentInbornIrishwolfhound

I believe merely the act of me spamming those blocks caused a TPS drop on this multiplayer server. It was a solid 20 for all players in the overworld before I started, and 15 for them right after the gif ends. It promptly shot back up to 20 again. The server is inconsistent with its TPS so I can't be 100% sure of it. 

_Edit:_
Modpack is [The Adventures of Halk](https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk)

https://gfycat.com/FaroffAltruisticGander

In this gif, I recreate the dupe in single player. It occurs during lag spikes. 

I just pasted a schematic of my storage setup from the server into single player. Here is a copy: 

https://cdn.discordapp.com/attachments/525550992574513152/608919635785547786/storage_test.nbt

**Comment by Lothrazar** [comment]
ive got the code running server  for testing whats the best way to lag it out and slow it down

**Comment by ProsperCraft** [comment]
Good question, perhaps using a command block to place a giant field of spawners, or hoppers looping items in to eachother, or use a command to spawn a million bats? not sure, we are always fighting lag not trying to produce it :)  Could also turn up the tick rate that is a thing now.

**Comment by VeloxAzo** [comment]
Install lycanites on the server, get a friend to fly around generating chunks, have them chunkload every lycanites dungeon they find.

**Comment by ProsperCraft** [comment]
That would especially work if you set the Lycanites dungeons to spawn every chunk instead of every 16 chunks.
