### ISSUE TITLE
Search box not always finding modded item

### ISSUE THREAD

**Issue by Knito58** [PrinceOfAmber/Storage-Network#208]
Minecraft version & Mod Version: MC 1.14.3, Forge 27.0.50, SSN 1.14.3-0.0.5
Single player or Server: SSP

Describe problem (what you were doing / what happened):
I have the mod "Lite Conversion" installed which introduces a "transmutation stone" which is in store.

Storage Request Table: Try to find such a stone.

Search string: "trans" -> no reaction at all <== BUG!! Should clear out "non-trans-es"
Search string: "@trans" -> nothing found (clears all items in overview box = correct result)
Search string: "#trans" -> no reachtion at all <== BUG
Search string: "stone" -> found within other blocks = correct
Search string: "@lite" -> found as expected (working! Yay!)

Visible Name of searched item: "Transmutation Stone"
Internal Name: liteconversion:trans_stone

Both the names contain "trans" and the search should have terminated successfully on first try.
As I often do not remember the mod name correctly my searches have a high rate of failing although the item is in store. Failing a search request happens rather often and I took this example to help improve the search routines.

**Comment by Knito58** [comment]
Bug test suggestion: Function doesStackMatchSearch()
Maybe "stack.getDisplayName()" already returns a string and the "toString()" after that is too much in some cases - depending on the items mod. I'm not coding MC mods so I don't know nothing.

**Comment by Knito58** [comment]
Ok meanwhile it's Forge 28.1.26 and Simple Storage Network 0.0.13 and the error persists:
Trying to find simple storage cables only works with "@sto". It would be nice if the mod would find its own things....

Otherwise: It is THE storage mod of choice. Wether or not the search works correctly. The things are "in" and can be found after fumbling around.

**Comment by NielsPilgaard** [comment]
It would be nice if the search was for display name instead of internal name, it's a bit counter intuitive at the moment.

**Comment by Lothrazar** [comment]
search in 1.16+ has been resolved to work on display name as expected in 1.12.2 and so on. 1.14.4 has been retired
