### ISSUE TITLE
funkyness with real filing cabinet

### ISSUE THREAD

**Issue by MasterSloth1** [PrinceOfAmber/Storage-Network#209]
Minecraft version & Mod Version:
Minecraft - 1.12.2
Forge - forge-14.23.5.2838
Simple storage networks - 1.12.2-1.7.8.jar
Real filing cabinet - 1.12-0.2.0.15.jar

Single player or Server:
server but no sponge

Describe problem (what you were doing / what happened):
i have a diamond chest with a import cable connected, set to 
![2019-08-04_10 50 49](https://user-images.githubusercontent.com/34207969/62417520-cf94b800-b6a5-11e9-83f8-a94bd13716e2.png)
this is my whole setup
![2019-08-04_10 52 03](https://user-images.githubusercontent.com/34207969/62417526-f05d0d80-b6a5-11e9-8e3d-f6bb5c1d61d8.png)

the network master can see all connected cables
the storage link cable settings
![2019-08-04_10 46 52](https://user-images.githubusercontent.com/34207969/62417538-28645080-b6a6-11e9-8934-8e11cd7729a5.png)

the actual issue is the request table cannot see all items in all the cabinets, also the import cable isnt importing items but inserting items into the cabinets via a item conduit works perfectly.
![2019-08-04_10 46 47](https://user-images.githubusercontent.com/34207969/62417560-a6c0f280-b6a6-11e9-8f38-d5bed23e476f.png)
![2019-08-04_10 47 23](https://user-images.githubusercontent.com/34207969/62417561-b4767800-b6a6-11e9-83a2-de224d27dd4c.png)

**Comment by MasterSloth1** [comment]
breaking and replacing the network master has fixed it, it can now see everything, as for the importing items it will only import items if the first item in the chest has a place to go so for example a iron sword has no where to go and its in the first slot of the diamond chest and i have a bone in the second slot the bone will just sit there until the iron sword is moved out of first

**Comment by Lothrazar** [comment]
From your last comment sounds not too bad.  Playing on my end with latest filecabinet version it works ok, might have been on their end anyway :)
