### ISSUE TITLE
Enhancement: Ignore damage field on import filter

### ISSUE THREAD

**Issue by krwminer** [PrinceOfAmber/Storage-Network#21]
I am trying to filer tools/armor that may be damaged. The problem is I want all of that armor/tool type. The import filter seems to be strict about the damage field. Is there any option you can provide to ignore the damage field?

**Comment by PrinceOfAmber** [comment]
Yeah for sure ill look into this

**Comment by PrinceOfAmber** [comment]
I think there might be a better way to do this. looking back in hindsight. Ill leave it for now but if it stops working let me know
