### ISSUE TITLE
Items Deleted When Putting Them In System

### ISSUE THREAD

**Issue by TheRJaBee** [PrinceOfAmber/Storage-Network#210]
Minecraft version & Mod Version:
1.12.2-1.7.8

Single player or Server:
Server

Describe problem (what you were doing / what happened):
When you have more then a stack of an item and you remove all of said item from the system then click it back in it will delete some of the item.  Through some testing I think this may be related to using chests from the Iron Chests  mod.  This issue does not seem to always happen nor does it seem to happen with all items or when there is a stack of less of an item.

Crash log (if any):
N/A

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
Can you make a screen shot or GIF or video of this happening maybe.  if it happens with a vanilla chest then problem exists in storage-network for sure https://www.screentogif.com 

I tried doing this lots of times "When you have more then a stack of an item and you remove all of said item from the system then click it back in it will delete some of the item."   I had a bunch of mods installed here , storage drawers, collossal chests, AA, barrels etc
![210](https://user-images.githubusercontent.com/621529/62675453-fb40c800-b95b-11e9-980f-eb77b089d6f2.gif)

**Comment by Lothrazar** [comment]
stale and cannot replicate
