### ISSUE TITLE
Major dupe bug on servers, maybe on single player too

### ISSUE THREAD

**Issue by Mixu78** [PrinceOfAmber/Storage-Network#211]
Minecraft version & Mod Version: MC-1.12.2     SSN-1.12.2-1.7.8

Single player or Server: Server

Describe problem (what you were doing / what happened): Spam-clicking an item onto a place where it won't appear duplicates it. Such as taking item d and spam-clicking it onto one of the x-slots will dupe it, however spam-clicking item d onto item d's slot while the slot has a stack in it will not dupe.

(sample grid:)x=empty, o & d=items
o d x x
x x x x

**Comment by VeloxAzo** [comment]
Duplicate of #207

**Comment by kohlth** [comment]
Hi mixu 👋

**Comment by Lothrazar** [comment]
just getting a fix ready for this. will be 1.7.9

**Comment by Lothrazar** [comment]
Can you try this fix? Tracked it down with some help on discord https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/2783512

**Comment by LemADEC** [comment]
is that still reproduced?

**Comment by Mixu78** [comment]
Didn't notice you made a fix until LemADEC commented here, it no longer happens in said fix.
