### ISSUE TITLE
[1.7.6] Bug: Item placed in network but cannot be retrieved

### ISSUE THREAD

**Issue by jarquafelmu** [PrinceOfAmber/Storage-Network#213]
# Minecraft version & Mod Version:
Minecraft 1.12.2
Simple Storage Network 1.7.6
Forge 14.23.5.2838

# Single player or Server:
Sky Factory 4 private server (2 people)

# Describe problem (what you were doing / what happened):
We have the storage network hooked up to BDSM's Crates, and normally items that don't have a spot just can't be placed into the network. However, my friend was able to accidentally put a ball of Industrial Foregoing's Pink Slime into the network. It shows as there being 12 pink slime in the network but we can't find it in any chest and it cannot be removed from the network when clicked on.

![Annotation 2019-08-13 191950](https://user-images.githubusercontent.com/5807272/62987897-5dd41100-bdff-11e9-8419-e2c27185fc5e.jpg)

**Comment by Lothrazar** [comment]
closing due to stale version, works as intended in 1.8.2+
