### ISSUE TITLE
Storage Request Table settings are reset upon chunk reloading

### ISSUE THREAD

**Issue by Revvilo** [PrinceOfAmber/Storage-Network#214]
#### Minecraft version & Mod Version:
- Minecraft 1.14.4
- Simple Storage Network: 0.0.9
- Forge: 28.0.55

#### Single player or Server:
Lan Single Player

#### Describe problem (what you were doing / what happened):
Reloading a chunk (by going away from it and coming back) doesn't seem to retain the NBT of the block and resets things like the sort order and direction back to default.

**Edit**: Actually this doesn't seem to be related to the chunk actually unloading and reloading on the server, but rather the _client_ unloading and reloading the chunk. My friend was standing right at the Request Table and I teleported a large distance away, then returned, and the terminal was reset again.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/2846523
