### ISSUE TITLE
Error after loading.

### ISSUE THREAD

**Issue by HonxY** [PrinceOfAmber/Storage-Network#216]
Minecraft version & Mod Version:
1.14.4-0.0.10

Single player or Server:
after loading.

Describe problem (what you were doing / what happened):
It says "Simple Storage Network (storagenetwork) encountered an error during the load_registeries event phase
Block{null} has property: up with invalidly named value: ınventıry

Crash log (if any):
[latest.log](https://github.com/Lothrazar/Storage-Network/files/3566550/latest.log)

**Comment by Lothrazar** [comment]
Hi, thanks for the log . Is it still a problem in 0.0.13

**Comment by Lothrazar** [comment]
resolved
