### ISSUE TITLE
[1.14.4] Request table crash

### ISSUE THREAD

**Issue by ScrambledGamer** [PrinceOfAmber/Storage-Network#217]
Minecraft version & Mod Version:
Minecraft: 1.14.4
Forge: 28.1.6
Simple Storage Network: 0.0.12

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
Crash when opening the request table

Crash log (if any):
https://pastebin.com/Vh9qiZCW

**Comment by ScrambledGamer** [comment]
Doesn't happen in version 0.0.11

**Comment by Knito58** [comment]
Didn't upload my crashlog to pastebin as it seems to be exactly the same. Other than ScrambledGamer's Forge version is mine on 28.1.1. Going back to version 0.0.11.

**Comment by dddema** [comment]
I still have the problem in 0.0.11 too

**Comment by Lothrazar** [comment]
Fixed in 0.0.13
