### ISSUE TITLE
Disconnected from a server due to apiarist backpack from forestry

### ISSUE THREAD

**Issue by MrDracoboy62** [PrinceOfAmber/Storage-Network#219]
Minecraft version & Mod Version:
minecraft 1.12.2 with Simple Storage 1.12.2 - 1.7.9

Single player or Server:
On a multiplayer server

Describe problem (what you were doing / what happened):
I tried to retrieve my apiarist backpack (from forestry 1.12.2-5.8.2.394) and suddenly the serv disconnect me with an Internal Exception

Crash log (if any):
not any crash report, just a message :
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes.

I think the data about my bees in the backpack are too heavy for the storage, i can just take them from the storage, but not with the remote or with the request table, there were more than 50 bees in this backpack (all with genetics modifications)

**Comment by Lothrazar** [comment]
"I think the data about my bees in the backpack are too heavy for the storage" 

After looking into this and how lots of other mods store backppack type items, theres not mcuh i can do. IF the NBT data inside an item is too large this just hits that native integer limit.  

Some storage bags store things differently, like without NBT. but this is just a limitation of the game data
