### ISSUE TITLE
Deletion of 1 Stack by double-click in Storage Request Table

### ISSUE THREAD

**Issue by Karatemango** [PrinceOfAmber/Storage-Network#220]
Minecraft version & Mod Version:
MC: 1.14.4
Forge: 28.1.1.0
Mod-Version: 1.14.4-0.0.13

Single player or Server:
Booth

Describe problem (what you were doing / what happened):
1. Have low tps and/or high ping to server.
2. double click a slot in the Storage Request Table which contains more than a stack of the item type in the slot.
3. you pick up a single stack but 2 stacks get taken out of the Network

It's similar to the dupebug which got fixed recently but in reverse
![gif](https://user-images.githubusercontent.com/44937309/65360162-21b27e00-dbff-11e9-87ba-67830c7bd2c3.gif)

**Comment by Lothrazar** [comment]
1.14.4 has been retired, issue resolved in 1.16.5+
