### ISSUE TITLE
Simple Request Table forgetting sorting 

### ISSUE THREAD

**Issue by Seilican** [PrinceOfAmber/Storage-Network#222]
Minecraft version & Mod Version:
1.14.4
0.0.13

Single player or Server:
official Minecolony's getting started server 

Describe problem (what you were doing / what happened):
every time i open the Request Table it reset's the sort by number of item's in the inventory to by name

Crash log (if any):
no crash just buging me over and over

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by strikerrocker** [comment]
Also forgets sorting in Storage Request Table

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/2846523
