### ISSUE TITLE
Crash if chunk load Procesing Cable

### ISSUE THREAD

**Issue by ghost** [PrinceOfAmber/Storage-Network#226]
Minecraft version & Mod Version:

Mc 1.2.2           Mod 1.7.6    (Mod pack Sky factory 4 V.4.0.8)

Single player or Server:

Server

Describe problem (what you were doing / what happened):

Procesing cable keep crashing anny player on server if chunk loaded , processing cable used with auto crafter from Cyclic mod  (used for autocraft essence infernium prudentium suprenium etc...)

Owner fix the problem by removing cable  ( 2 of 6 câbles)

Crash log (if any):

[crash-2019-10-09_21.47.26-client.txt](https://github.com/Lothrazar/Storage-Network/files/3709193/crash-2019-10-09_21.47.26-client.txt)

or

https://pastebin.com/Ut37dBdi

**Comment by Lothrazar** [comment]
Was marked as cannot replicate in 2019 on an old version.  Hopefully was just a fluke.  Please reopen new issue if it happens again, also could be reported to modpack tracker
