### ISSUE TITLE
No cables connect to Storage Network Manager (v1.14.4-0.0.13)

### ISSUE THREAD

**Issue by BubbaVB** [PrinceOfAmber/Storage-Network#228]
Minecraft version & Mod Version:
v1.14.4-0.0.13

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
I am unable to get any of the cables to connect to the Storage Network Manager.  Here is a picture showing what I describe.
[https://imgur.com/a/6XxrP8Q](url)

Crash log (if any):
No crashlog

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by BubbaVB** [comment]
Update!  I found out shortly after this post that if you place the cables 1st then the Storage Network Manager it will connect.  Otherwise they will not connect.

**Comment by marios-andr** [comment]
@BubbaVB I tried what you suggested but unfortunately when I place down the Storage Network Manager next to the cable it will just break.

**Comment by Lothrazar** [comment]
I think its a visual only issue, they connect in the network but not in graphics. 

And sometimes in 1.14 you have to move the master over one block if it wont place. Still some issues to work out

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/2846523
