### ISSUE TITLE
Storage Network and Thermal Dynamics (1.12)

### ISSUE THREAD

**Issue by Griffin224** [PrinceOfAmber/Storage-Network#23]
Had a number of crashes concerning what I thought was Thermal Dynamics, mod author says it is Storage Networks causing the issue so I am posting the crash log here.
[crash-2017-07-30_19.01.08-server.txt](https://github.com/PrinceOfAmber/Storage-Network/files/1186189/crash-2017-07-30_19.01.08-server.txt)

**Comment by PrinceOfAmber** [comment]
Ok ill check this out. thanks

**Comment by PrinceOfAmber** [comment]
In the latest version this shouldnt crash the game.  Im catching the exception and printing it to the log and added some safeguards.  So this should be patched now, let me know if it happens again. (log was from SimpleStorageNetwork-1.12-1.0.10, latest is version 1.0.13)

Based on the log, im not sure exactly where the fault is from storage network.   I looked at Thermal source code as well.  What i think happens is

Thermal Dynamics block called "BlockDuct" tries to get metadata property of blocks nearby
One of those blocks is storage network
Storage then goes "My block doesnt have this metadata property, im a very simple cable, so what you are trying to do is invalid".  It would be like trying to find all 16 different wool colours out of a piece of stone. Well thats not going to work, its stone and not wool, it doesnt have 16 variants.

But at least now if it happens again it wont crash
