### ISSUE TITLE
[1.14.4] not grabbing correct enchanted book from network or search for certain enchanted boots

### ISSUE THREAD

**Issue by raziel23x** [PrinceOfAmber/Storage-Network#230]
Minecraft version & Mod Version:1.14.4 0.0.13

Single player or Server:Both

Describe problem (what you were doing / what happened):
When pulling from the network you cannot grab the enchanted book you pick you automatically pick up the first book from the network not the one you wanted and you cannot search for enchanted books by name

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by TheDeviantCrafter** [comment]
All of the enchanted books have the same name. You can search the tooltip with a hashtag. `#fortune` would show fortune books for example.

The system appears to be grabbing the right enchanted book for me when grabbing items from the remote. Are you automatically extracting items?

**Comment by raziel23x** [comment]
I am using the Colossal Chests mod and have the system connected to the Diamond Colossal Chest i tried it both with the remote and from the actual crafting terminal
