### ISSUE TITLE
Server CPU Issues

### ISSUE THREAD

**Issue by SirHoward** [PrinceOfAmber/Storage-Network#233]
Minecraft version & Mod Version: 

1.12.2, any version of the mod

Single player or Server: 

Server

Describe problem (what you were doing / what happened): 

Server CPU is going to over 90% after a while. reinstalling the mod heps, but only for a few hours.

Crash log (if any):

no crashes at all

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
Any logs or data to indicate this mod is the cause and not any of the others? A sample or something? https://www.curseforge.com/minecraft/mc-mods/sampler

**Comment by Lothrazar** [comment]
90% of the ticks reported in tile master are literally it waiting for the inventories to respond. This is why lag goggles is terrible for debugging mods, and sampler is much more accurate.  

Working as intended
