### ISSUE TITLE
More Console Spam, might be related to client hangs.

### ISSUE THREAD

**Issue by kreezxil** [PrinceOfAmber/Storage-Network#234]
Minecraft version & Mod Version:
1.14.4 - 0.0.13

Single player or Server:
server [World of Dragons - A New Age](https://www.curseforge.com/minecraft/modpacks/world-of-dragons-a-new-age)

Describe problem (what you were doing / what happened):

Console is loaded with the following on the client:
```
[07:37:20] [Client thread/WARN]: Unknown custom packet identifier: storagenetwork:main_channel
[07:37:20] [Client thread/WARN]: Unknown custom packet identifier: storagenetwork:main_channel
[07:37:20] [Client thread/WARN]: Unknown custom packet identifier: storagenetwork:main_channel
```
I think it's a possible cause of odd client crashing when grabbing stuff out of the storage network.
Crash log (if any):
No crash log, the client just hung hard, no debug.log either, there is this latest log, you can jump down line 47800 to see these lines that show up around the time of the client hang.

report | paste
--- | ---
latest.log | https://gist.github.com/kreezxil/b39acb06c89c513372a2a14ea3c3368b

**Comment by Lothrazar** [comment]
Yeh this is no big deal. forge has this new dumb thing where they force us to do



    ctx.get().setPacketHandled(true);

at the end so ill clean this up

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/2846523
