### ISSUE TITLE
Import cable won't work in blacklist mode

### ISSUE THREAD

**Issue by ChellieH** [PrinceOfAmber/Storage-Network#236]
Minecraft version & Mod Version: 1.12.2 - 1.7.8

Single player or Server: Single player

Describe problem (what you were doing / what happened): I have a chest connected to the SSN with an import cable. The SSN is connected to a compact machine with a storage link cable that has a filing cabinet inside (also connected with a storage link cable). If I whitelist items they will import into the storage network but if I have the import cable set to blacklist nothing (or items not in the chest) it will not import anything. It initially imported 1 stack but then stopped importing.

**Comment by Lothrazar** [comment]
I blacklisted grass blocks. It imported from the chest all the stuff that is not the grass block.  Working as intended in 1.7.9 
![import blk](https://user-images.githubusercontent.com/621529/71325384-c9f70d80-24a0-11ea-8cd8-b1585a3c16af.gif)
