### ISSUE TITLE
Storage request table

### ISSUE THREAD

**Issue by Dinoriders** [PrinceOfAmber/Storage-Network#237]
Minecraft version & Mod Version: 1.12.2  & 1.12.2 - 1.7.8

Single player or Server: Server

Describe problem : Storage request table won't open

Crash log (if any): https://pastebin.com/saarDFSY

**Comment by Lothrazar** [comment]
Seems like cause was due to outdated FastWorkbench version.  WOrks with latest versions of all mods  

Good luck let me know if theres anything else :)
