### ISSUE TITLE
The remote glitches sometimes

### ISSUE THREAD

**Issue by Alyaqdhans** [PrinceOfAmber/Storage-Network#239]
![Screenshot (72)](https://user-images.githubusercontent.com/58079015/69432960-25c06080-0d54-11ea-8fa2-8741da9fb83e.png)

Minecraft version & Mod Version: 1.12.2

Single player or Server: Single player

Describe problem (what you were doing / what happened): adventuring and suddenly when i open the remote it shows blank space, no items appear..

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by AlyaqdhanZ** [comment]
I think it's a mods conflict..
does the iron chests mod do that?

**Comment by Oddlybird** [comment]
Minecraft & version 1.12.2, single player, putting together a modpack.

I've seen this happen several times in the past, but today I got a strange one that skips in and out -- while inside the same dimension, the overworld.

In this map, if I'm within around 250-some blocks south of my storage system, the three remotes (simple, advanced and upgraded, but not the 64-block short range one) work perfectly.  If I go a dozen more blocks away, all three infinite distance remotes blank out, and stay that way.  ...until I head a dozen blocks back north towards the storage system, where they abruptly start working again.

There is another storage system elsewhere in the same overworld, far southwest, and I have some spare remotes for both storage systems stored in the one that's glitching out.  I don't know if either of those facts are related or important.

I have a backup copy of the map saved, but I don't know if it would even load without the gigantic list of half-customized mods.

**Comment by AlyaqdhanZ** [comment]
I get that glitch on other dimensions (twilight, nether end...etc)
when I enter the dimension it works fine but after couple blocks of walkng it does that..
I also check latest update but the glitch still exist please fix it, and thank you.

**Comment by AlyaqdhanZ** [comment]
I removed "BetterFPS" and "Optifine" mods and the problem got fixed.

**Comment by Alyaqdhans** [comment]
I fixed mine by doing this, get "FTB Utilities mod" and go on claimed chunks section top left inventory that looks like a map (shift click the chunk) to make the chunk where is your storage loaded, hopefully it will be fixed.
