### ISSUE TITLE
Constant "crashes" when opening remote.

### ISSUE THREAD

**Issue by Griffin224** [PrinceOfAmber/Storage-Network#24]
I will try to open my remote and the game logs me out and tells me "A fatal error has occurred, this connection is terminated."

![ssn crash](https://user-images.githubusercontent.com/17104244/29180162-e789eb40-7dc4-11e7-934d-4bcd6ff3526f.png)

This only happens when I use the remote and no other time. (Happened with both remotes, original and upgraded.)

**Comment by krwminer** [comment]
You might want to provide more information. Crash logs if any. At least what mods you are using so it can be replicated easier.

**Comment by PrinceOfAmber** [comment]
This has never happened to be but id like to dig in deeper and try to fix it.  I have used it in single player and multiplayer both, and have seen people on servers use it in twitch stream.

You should have logs such as /logs/latest.log and also a /crashlogs/ folder  .

**Comment by PrinceOfAmber** [comment]
@Griffin224 has this happened again? did you find the crash log file?  What modpack is it in if any?  was it server or client?

**Comment by Griffin224** [comment]
Did not completely crash the game, just the client and would boot me off the server. Started a new server with my nephew and have had zero issues.
