### ISSUE TITLE
CTD - Client NPE

### ISSUE THREAD

**Issue by Flatts3000** [PrinceOfAmber/Storage-Network#241]
Minecraft version & Mod Version:
1.14.4 | 0.1.0

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Client CTD whenever transitioning to the nether.

Crash log (if any):
https://pastebin.com/dhPJWPfN

**Comment by Lothrazar** [comment]
This is an iron jetpacks crash, no simple storage in log

at com.blakebr0.ironjetpacks.handler.KeybindHandler.onClientTick(KeybindHandler.java:125) ~[?:2.0.2] {re:classloading}
