### ISSUE TITLE
Import more than first slot

### ISSUE THREAD

**Issue by gabrjel90** [PrinceOfAmber/Storage-Network#242]
Minecraft version & Mod Version:
1.12.2-1.7.8

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
Having an issue with import cable where it takes only the first slot of the inventory. Ex. I have a chest full of sticks that i want to bring  in the network and into another chest. Import cable will bring first slot (top left) and than stop. If i manually move another stack in that position it moves it but it doesnt empty any other slot.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
It does import more than the first slot. as soon as first slot is empty it moves on.    as shown in gif below it works as intended

If the chest is filling up faster than the network can import there are speed upgrades you can get. or maybe distribute it among more containers.

GIF recorded in 1.12.2-1.7.9 

![import 242](https://user-images.githubusercontent.com/621529/71326499-b489df80-24b0-11ea-88b8-39bbf39903d3.gif)
