### ISSUE TITLE
Lock the slot in which the "Storage Remote" lies

### ISSUE THREAD

**Issue by maksim789456** [PrinceOfAmber/Storage-Network#243]
When you open ui, you can just throw out "Storage Remote". I propose to block the slot so that you can't interact with it.
![dGBFeldvMS](https://user-images.githubusercontent.com/8225008/71449031-d0b2a880-275e-11ea-83ae-dfde98bf1f75.gif)

**Comment by Lothrazar** [comment]
is this in 1.14?

**Comment by maksim789456** [comment]
Yes

**Comment by Lothrazar** [comment]
i change so it closes the screen if you pick it up like that
