### ISSUE TITLE
Crash when opening the grid

### ISSUE THREAD

**Issue by th4umiel** [PrinceOfAmber/Storage-Network#244]
Minecraft version 1.12.2 & Mod Version SimpleStorageNetwork-1.12.2-1.7.9

Single player

Crash when trying to open the terminal/grid

Crash log (if any):

https://pastebin.com/9BgWMXjV

**Comment by Lothrazar** [comment]
In newer versions of simple storage network you need to either uninstall fastworkbench or update to newest version minmum 1.7.0

Your log had
        | LCHIJA | fastbench               | 1.6.0                    | FastWorkbench-1.12.2-1.6.0.jar    

https://www.curseforge.com/minecraft/mc-mods/fastworkbench/files/2838777

**Comment by th4umiel** [comment]
Thanks! Checking now and eventually closing the issue ASAP
