### ISSUE TITLE
German Search

### ISSUE THREAD

**Issue by wuffi-steel** [PrinceOfAmber/Storage-Network#245]
Minecraft version & Mod Version:
MC 1.14.4 Forge 28.1.111

Cannot search in German for this version.
SimpleStorageNetwork-1.14.4-0.2.0.jar

I have to search for the English words through JEI
Can I change it somewhere? Config?

Thanks

**Comment by Lothrazar** [comment]
Can you send some screenshots or examples? I think if normal names are translated such as "dirt" in german you should be able to search for translations

**Comment by wuffi-steel** [comment]
![D313D19C-6AC1-4681-ADDA-E114DB2A4FB4](https://user-images.githubusercontent.com/23581228/71965622-5410d700-3200-11ea-96e2-59a16a6b431a.png)

**Comment by wuffi-steel** [comment]
![2020-01-08_12 32 46](https://user-images.githubusercontent.com/23581228/71978735-6436af80-321c-11ea-9c32-dee773591468.png)
![2020-01-08_12 33 05](https://user-images.githubusercontent.com/23581228/71978747-67ca3680-321c-11ea-802d-ce63c4229ef4.png)
![2020-01-08_12 32 38](https://user-images.githubusercontent.com/23581228/71978751-6a2c9080-321c-11ea-9ba7-a759dea5c099.png)
![2020-01-08_12 32 29](https://user-images.githubusercontent.com/23581228/71978755-6bf65400-321c-11ea-929f-ef987b125618.png)

**Comment by bluebear94** [comment]
I think the interface currently searches by item ID, not item name. For instance, I have to type `kabel` instead of `cable` to search for cables (I play in English), because the various cables have the word spelt as `kabel` in their item IDs.

**Comment by Lothrazar** [comment]
1.14.4 has been retired, issue resolved in 1.16.5+
