### ISSUE TITLE
1.15.1 Crash when placing storage request table or a storage inventory

### ISSUE THREAD

**Issue by Yamza** [PrinceOfAmber/Storage-Network#246]
Minecraft version & Mod Version:
1.15.1
Forge: 30.0.35
storagenetwork@1.15.1-0.2.1

Single player or Server:
Able to reproduce several times on server, once in single player. May need to place and replace a few times.

Describe problem (what you were doing / what happened):
Connecting a storage request table or a storage inventory to a connected network causes a crash
Example setup: https://i.imgur.com/4W7cqKl.png
https://i.imgur.com/JjwvUeD.gifv

Crash log (if any):
https://s.yoosk.pl/7vozt

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
should fix https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/2857534

**Comment by Yamza** [comment]
Seems to be working fine now. Thank you!
