### ISSUE TITLE
Cannot Import Reciepes from JEI into Request Table

### ISSUE THREAD

**Issue by volrathy** [PrinceOfAmber/Storage-Network#247]
Minecraft version & Mod Version: 1.15.1 / 0.2.2

Single player or Server: Single Player

Describe problem (what you were doing / what happened):

1. Open Up Storage Request Table
2. Look for Reciepe in JEI
3. There is no + symbol you cannot craft from that you have to do it manually

**Comment by winnetrie83** [comment]
I can report the same issue. Exactly same versions and issue discription.

**Comment by Lothrazar** [comment]
Yep added the patch for this https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/2864119
