### ISSUE TITLE
Not sure if issue or enhacement? Link cables - 1.5.2

### ISSUE THREAD

**Issue by winsrp** [PrinceOfAmber/Storage-Network#251]
Putting down a link cable (of any type) only connects to a single storage unit.

E.g. 

I put 1 chest, leave one empty space and put another chest, in the middle empty space I place a link cable, but it only connects to a single chest, and not even the one I wanted XD... Is there a way to have the connector connect to both chests? is this something already on the mod and not working or something that could be an enhancement?

First time using this mod, since I had it with refined storage and his very angry programmer... =/, and this mod just works with everything I use it, except that one thing XD.... and slime balls on the remote recipe.. that is just mean, you could have used blaze rods or something.

Love the mod, keep the good work.

**Comment by winsrp** [comment]
If I remove one of the chests and put it back in place, the connector will actually change to look like if connected both chests, but the contents are not read.

![image](https://user-images.githubusercontent.com/13665046/74040682-c7397480-4989-11ea-8bc2-8b469225c868.png)

**Comment by freitagdavid** [comment]
I believe that's a purposeful limitation of the mod.

**Comment by winsrp** [comment]
seems odd that things do connect then when you place them second? don't you think?

**Comment by KollinsPlays** [comment]
I've always thought it was limited to 1 connection per cable, being that it's called simple storage and all . FYI you can swap which one it points at with most mod's wrenches. Even RS and AE don't actually do multiple connections per i/o connector, they just use multipart to get more than one i/o connector into the same blockspace.

**Comment by winsrp** [comment]
would be cool if it could take all surrounding chests with a single connection.

**Comment by Lothrazar** [comment]
Each one only actually connects to one chest, but the visuals are broken so in that picture its showing both as you said, so this is the bug. 

Recipes can always be changed with a data pack or craftweaker.

An enhancement could be a 'multi cable' where it actually can connect everywhere, i wonder how difficult that is.

**Comment by winsrp** [comment]
well sounds like a nice challenge! =D

**Comment by Lothrazar** [comment]
Finally got around to fixing this .  one chest per connection still but the visual bug is gone.  Mulit-link is more work than i thought so still have to brianstorm on that a bit https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/2915071
