### ISSUE TITLE
skyfactory 4 simple configuration

### ISSUE THREAD

**Issue by egornovivan** [PrinceOfAmber/Storage-Network#252]
Minecraft version & Mod Version: 1.12.2 SkyFactory 4 - 4.1.0 & SimpleStorageNetwork-1.12.2-1.7.8.jar

Single player or Server: single

Describe problem (what you were doing / what happened):
![15811235805050](https://user-images.githubusercontent.com/60801856/74076688-9d408a80-4a3b-11ea-904a-5e6f7f22fe65.png)
![15811237236340](https://user-images.githubusercontent.com/60801856/74076689-a03b7b00-4a3b-11ea-82c6-12755a1d7b16.png)

Crash log (if any):
saves 
[saves.zip](https://github.com/Lothrazar/Storage-Network/files/4173592/saves.zip)

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
Thanks  for the report.  Lag goggles is notoriusly inacurate as  it only shows where the time is spent waiting, not where the code is actually running.

For example. if An import cable is connected to machine X and tries to import items, if machine X takes 200 ticks to respond to the networks request to give items, that shows 200 ticks in TileMaster, even though it was doing literaly nothing except just waiting.

While working with the devs of Sky factory, and specifically BDS, Filling Cabinets, we found and fixed many lag issues by using the Sampler mod, this creates an NPS file that is much more in depth.
https://www.curseforge.com/minecraft/mc-mods/sampler

**Comment by Lothrazar** [comment]
90% of the ticks reported in tile master are literally it waiting for the inventories to respond. This is why lag goggles is terrible for debugging mods, and sampler is much more accurate.  

Working as intended
