### ISSUE TITLE
Duplicating Emerald Dank Box

### ISSUE THREAD

**Issue by geleugim** [PrinceOfAmber/Storage-Network#253]
Minecraft version & Mod Version:
1.12.2
DankNull-1.12.2-1.7.89
SimpleStorageNetwork-1.12.2-1.7.10

Single player or Server:
Server

Describe problem (what you were doing / what happened):
If a dank docking station is connected to a storage link
When I try to undock an emerald box I might get two instead.  Does not happen every time.  But I turned 1 into 13.

Crash log (if any):
no crash from this.

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

I am running the mod pack MC.Eternal.  I am not sure if this is a Dank or SSN issue.

Thank you.

**Comment by geleugim** [comment]
This might be an issue with Dank and not SSN.

https://github.com/p455w0rd/DankNull/issues/241

**Comment by Lothrazar** [comment]
The network simply uses the capability interface to interact with items, so im not sure if bug is on just one mod or both but it seems unlikely that the network would have an issue

**Comment by geleugim** [comment]
The issue can be replicated without SSN, I believe this should be closed.  Thank you!
