### ISSUE TITLE
storage table not working properly

### ISSUE THREAD

**Issue by thill19** [PrinceOfAmber/Storage-Network#255]
Minecraft version & Mod Version: 1.12.2 & 1.12.2.1.7.10

Single player or Server: both

Describe problem (what you were doing / what happened): when i have multiple request tables on the same controller it doesn't let me open one of them. after i make a remote i have to remove all the tables and use remotes only. also happens when i don't even have a remote hooked up to the system. it closes the gui after it being open only milliseconds

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
SO you use one of the request tables but it auto closes right away?

Thats a strange situation, not sure why remotes would trigger this.

I built a few networks and cant replicate this.  Maybe try breaking the master block and putting it back on the network somewhere else 

recording 
![255](https://user-images.githubusercontent.com/621529/75612486-af609680-5ad8-11ea-9f01-f760be950839.gif)

**Comment by Protheus** [comment]
SimpleStorageNetwork-1.12.2-1.7.10 (Added to E2E 1.77)

I  have an import cable connected to an ender chest. When it is connected and I open the storage request table similar thing as above happens.

WHen I break the ender chest the table works fine.

The import has 1 stack and the rest is speed upgrades. When using the remote allis working fine.

**Comment by thill19** [comment]
yeah ive noticed it only happens when i link a new ender chest with a stack upgrade then 3 speed upgrades in an import cable

**Comment by Nonsanity** [comment]
I had the same problem (Storage Request Table closing a moment after it is opened) with two Tables on the same network. The problem seems to be the result of having two network branches coming off of difference sides of the Master block. If, instead, the Master block has a cable on only one side and all Tables are attached to that cable, everything works fine.
