### ISSUE TITLE
Config Suggestions

### ISSUE THREAD

**Issue by RageMachine985** [PrinceOfAmber/Storage-Network#258]
Suggestion:

Heyo! Right now I'm scouting out mods to add into a certain very large modpack and this one seems almost perfect!

The only issues it'd have before it comes up for inspection are with the config right now, our devs would really appreciate it if we had the ability to toggle/disable certain blocks and items individually from existing and if there were a configurable limit to the amount of chests that can be linked up to one storage network master at a time. That and compatibility with varied commodities crates and barrels would be really nice!!

If we had that we'd just have to make our own texture redo to fit the packs theme and it'd be amazing! 
Thanks a ton for your work!! :D  (We're in 1.12.2 btw)

**Comment by Lothrazar** [comment]
Limiting the number of connections to a network Sound be easy enough to add.

On the comment of "disable certian blocks", you can use this config to block an inventory from connecting, is that what you mean 


`    # Disable these blocks from ever being able to connect to the network, they will be treated as a non-inventory. [default: [extrautils2:playerchest]]
    S:BlacklistBlocks <
        extrautils2:playerchest
     >`

**Comment by RageMachine985** [comment]
That sounds awesome! And no I meant being able to disable/toggle items from being crafted or used in the mod through the config, i.e. disabling the remotes from use or certain variants of storage cables from being used. Just for balancing and preference sake.

**Comment by Lothrazar** [comment]
Ill look into the disabling itemsconfig thing, but it might be faster on your end to disable recipes and hide from JEI in craft tweaker :) 

If varied commodities https://www.curseforge.com/minecraft/mc-mods/varied-commodities does not work, its almost certainly on their end, they need to make sure their inventories use the "Capabilities" system.  

Compact storage for a while had a similar issue, in that situation someone made an addon mod, so check the source of that for more info
https://www.curseforge.com/minecraft/mc-mods/compatchedstorage

**Comment by RageMachine985** [comment]
Will do, thanks a million!!
