### ISSUE TITLE
[1.15.2] Server rejecting conections- java.lang.NullPointerException: null         at com.lothrazar.storagenetwork.capabilities.CapabilityConnectable.serializeNBT

### ISSUE THREAD

**Issue by ProsperCraft** [PrinceOfAmber/Storage-Network#259]
Minecraft version & Mod Version:
1.15.2
SimpleStorageNetwork-1.15.2-0.2.4

Single player or Server:
Server

Describe problem (what you were doing / what happened):
The server quit accepting connections from clients, on looking at the console, this is what I found.

[latest.log](https://github.com/Lothrazar/Storage-Network/files/4333257/latest.log)
Crash log (if any):
Stacktrace in console
https://gist.github.com/ProsperCraft/e51c7928a735ca80ca131ed23628c086
[debug.log](https://github.com/Lothrazar/Storage-Network/files/4333256/debug.log)

**Comment by Lothrazar** [comment]
I pushed an update for this in 0.3.0 can you confirm if the fix worked

**Comment by ProsperCraft** [comment]
We have not had the issue lately, will re-open if it crops up again, thank you.
