### ISSUE TITLE
Nothing happens when right clicking storage request table

### ISSUE THREAD

**Issue by tta52495** [PrinceOfAmber/Storage-Network#260]
Minecraft version & Mod Version: 1.12.2 mod version tested on both 1.7.8 and 1.7.10

Single player or Server: Single-player

Describe problem (what you were doing / what happened): I added the mod into the 1.12 DW20 pack and whenever I set up a system and right click on the storage request table, nothing happens.  It doesn't pop up at all.  It triggers an error in the log every time I right click it.  It was working fine for me on Skyfactory 4 so I'm guessing it's some kind of mod incompatibility.  

Crash log (if any):https://pastebin.com/sS5NR5ey Not a crash log but a copy of the error it triggers.  

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by tta52495** [comment]
I figured my issue out, simple storage networks is broken by the fast workbench mod https://www.curseforge.com/minecraft/mc-mods/fastworkbench which is included in the DW20 pack.

**Comment by Lothrazar** [comment]
yep try again with FWB updated
