### ISSUE TITLE
Search issue in 1.14.4

### ISSUE THREAD

**Issue by makandz** [PrinceOfAmber/Storage-Network#261]
I noticed the search issue was fixed in this version https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/2869008 but for 1.15.2, will this ever get ported over to 1.14.4?

**Comment by IrishBread** [comment]
will 1.14.4 be getting a update!

**Comment by Lothrazar** [comment]
Yes i will pull back some of the 1.15 fixes into 1.14, i realize people still have modpacks and worlds invested in that version.  I will try for within the week, if not remind me here again

**Comment by makandz** [comment]
> I will try for within the week, if not remind me here again

Bump just in case you forgot :)

**Comment by Lothrazar** [comment]
1.14.4 has been retired, issue resolved in 1.16.5+
