### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by crylrz** [PrinceOfAmber/Storage-Network#262]
This is a good mod , I want to let more people know about it and use it. MCBBS(https://www.mcbbs.net/)is the biggest Minecraft forum in China.I will indicate information about this mod(its original author,original address,etc)on MCBBS.Would you agree with me?
Thanks a lot.

**Comment by Lothrazar** [comment]
Yes for sure i would love it if you talked about this mod and shared its existence.  ❤️ 

I ask that you always link back to the official files page which has all most recent official downloads https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files 

And also link here for an problems .


If you can find someone who knows how to translate the language and work with JSON files we can work together to add foreign language support in a zh_cn.lang file https://github.com/Lothrazar/Storage-Network/tree/trunk/1.15/src/main/resources/assets/storagenetwork/lang
