### ISSUE TITLE
Storage Remote (all) not working after ~200 blocks and across dimensions for the advanced

### ISSUE THREAD

**Issue by leRanger7** [PrinceOfAmber/Storage-Network#264]
Minecraft version : 1.12.2 
Mod Version : 1.7.10

Single player

None of the different remotes works after 200 blocks or across dimensions for the advanced. 
I tried moving the network storage master, changed the cables,... Nothing changed.
It's not saying that I'm to far away, just doesn't load what's in the chest and can't put anything in.

**Comment by Lothrazar** [comment]
Is your master network block in a Chunk-loaded area? Such as with a chunk loading block within another mod, or in the spawn chunks?

The network does not self-load, so if that part of the world gets unloaded then its offline

**Comment by leRanger7** [comment]
Yes, thank you it works now. I didn't think of that.

**Comment by Moshkown** [comment]
I have the same issue but the solution doesn't fix it for me. Also, I have used it without Chunkloaders for weeks without any issues.
