### ISSUE TITLE
How do I create the .jar file?

### ISSUE THREAD

**Issue by 60VoltTransistor** [PrinceOfAmber/Storage-Network#265]
How do I build this mod, what I mean by this is if I wanted to edit how this mod behaves like adding unlimited range to the wireless storage remote, how could I create the .jar file with those edits made so that I can use that for myself, I wouldn't release the mod, I would just modify it so that certain features that I would like to see implemented can be implemented. I couldn't figure out how to contact you directly but this is the best that I could find.

**Comment by Lothrazar** [comment]
Same as any other forge-gradle mod

on windows you do

./gradlew build
