### ISSUE TITLE
Only the basic remote is able to be crafted 

### ISSUE THREAD

**Issue by Chaos473** [PrinceOfAmber/Storage-Network#266]
Minecraft version & Mod Version:
MC - 1.14.4 
Custom ModPack - Forge version - 28.2.3

Single player or Server:
Server

Describe problem (what you were doing / what happened):

Only the basic remote with no crafting and a limited distance can be crafted. After much solo editing, I have been unable to see the remotes able to be crafted. (Do not appear in JEI). Is there something I am missing in the config or is this new with 1.14.4? Kinda on the end of the ropes here so any help is appreciated! My friends would love to use the advanced remote just like in 1.12.2.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
Yes the 1.14 port is not complete.  
It was only a few days ago that I managed to get a second remote added to 1.15.2 , so now 1.15 has the basic remote and a crafting grid remote

**Comment by Chaos473** [comment]
Oh that would make sense, thank you for your speedy response. And as
always, thanks for providing such a great mod! Best of luck for your future
work.

**Comment by Lothrazar** [comment]
1.14.4 has been retired, issue resolved in 1.16.5+
