### ISSUE TITLE
Crafting doesnt update Container inputs

### ISSUE THREAD

**Issue by mcenderdragon** [PrinceOfAmber/Storage-Network#267]
1.14.4
SimpleStorageNetwork-1.14.4-0.2.0.jar

Single player or Server:
SInglerplayer

Describe problem (what you were doing / what happened):
I crafted stuff using the Storage Request Table and when the items from the connected storage where used the display did not update to the correct amount, alias I crafted and while the items got consumed the display did not update.

**Comment by Lothrazar** [comment]
same comment here applies . also mc1.14 is basically complete https://github.com/Lothrazar/Storage-Network/issues/450#issuecomment-1178542985

**Comment by mcenderdragon** [comment]
a config option for this might be interesting in the future also I understnat that you dont wan tto update 1.14 anymore , but 2 years ago 1.14 was latest :P
