### ISSUE TITLE
Remote problem

### ISSUE THREAD

**Issue by Alyaqdhans** [PrinceOfAmber/Storage-Network#270]
Minecraft version & Mod Version: 
1.12.2

Single player or Server: 
Single player

Describe problem (what you were doing / what happened): 
You shouldn't be able to place remote on the storage when you open the remote, fix it please.

Suggestion: Make the remote unmovable when you open it.

**Comment by Lothrazar** [comment]
Yep, this was fixed in an old version, not sure which version you have but just update the mod

When you open a remote, **that exact remote that you opened with** cannot be shift clicked or picked up to be moved into the network .

**Comment by Alyaqdhans** [comment]
Actually this problem doesn't exist in vanilla but it does in modded minecraft.
Idk if there's a conflict but there's one remote that's ok it was "Simple Storage Remote" if that helps to figure out what's the difference between them.
I'm using the latest update for the mod in 1.12.2 btw.

**Comment by Alyaqdhans** [comment]
I found the mod what causing the problem, it's "FastWorkbench"
