### ISSUE TITLE
Filtered Import Cable doesn't drop upgrades when broken

### ISSUE THREAD

**Issue by Nifusion** [PrinceOfAmber/Storage-Network#271]
Minecraft version & Mod Version:
1.15.2 0.3.2

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
Basically the title. Place filtered import cable. Add a speed or stack upgrade. Break cable. No drops.

Similar to https://github.com/Lothrazar/Storage-Network/issues/44 but for 1.15.2

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/2985634
