### ISSUE TITLE
Smarter sorting

### ISSUE THREAD

**Issue by IngmarBitter** [PrinceOfAmber/Storage-Network#272]
Minecraft version 1.12.2 & Mod Version 1.12.2-1.7.6, Server, as configured in Sev Tech, particularly the version here: https://www.technicpack.net/modpack/atlantica-st.1616640

For the storage request table and storage remote, can the top four rows in the inventory view (what we see without scrolling) be smarter? 

Rows 1,2,3:  upon opening the gui are filled with the 27 most recently retrieved and/or crafted items.
Row 4: upon opening filled with the 9 most recently added to the the storage system items (those already in Rows 1,2,3 are skipped to avoid repeats).
All four rows are sorted by mod, and within that by item ID, but applied twice, once for Rows 1,2,3 and once for Row 4.

When an item is shift clicked into storage, then Row 4 updates accordingly (the new item appears if it was not already there, or otherwise its item count updates, and if it was not there yet, then the most recently added item is removed.

When an item is retrieved from storage out of those 4 rows (or was crafted), nothing changes in the GUI, but the most recently retrieved/crafted timestamp is updated.

When an item is retrieved from a row further down after scrolling, then the retrieved/crafted timestamp is updated and the oldest of the 27 items in Row 1,2,3 is replaced with this one and then the sorting reapplied.

When the display selection was changed  based on a filter search string, then the matches are shown sorted by mod and then item ID.  The smart sorting from above is disabled till the search box is cleared.

The goal is to have those items in immediate view that are most likely going to be used in the next use or crafting action, and to have their locations within the display grid change as little as possible while the user interacts with the GUI. The described smart sorting promises to accomplish those two goals. 

PS: I'd be happy to help with the implementation of this idea

**Comment by Lothrazar** [comment]
Thanks for the awesome suggestion, i was interested at the time and it still sounds neat. for 1.12 its locked down as long term support but ill keep it on the idea list for 1.18 features. tracking the timestamps might get a bit heavy, not sure tho.  if anyone sees this things are happening in discord https://discord.lothrazar.net/
