### ISSUE TITLE
1.12.2 Crash when shift click

### ISSUE THREAD

**Issue by Jennifercutixx** [PrinceOfAmber/Storage-Network#273]
Minecraft version & Mod Version: 1.12.2

Single player or Server: Singleplayer

Describe problem (what you were doing / what happened):
was testing the mod and when i shoft clicked an item into the main terminal just the terminal that shows the blocks it crashed the game

Crash log (if any):
It didn't save the latest log since it crashed bc the game didn't respond

**Comment by Lothrazar** [comment]
even when the game doesnt respond there is usually something either in logs or crash reports after the game finishes exiting.

I have been shift clicking items into it for months with no issues. but by all means if it happens again please open a new issue 
![pic](https://user-images.githubusercontent.com/621529/85931776-aa8bd380-b87b-11ea-83b9-13b03f9ba70d.png)
