### ISSUE TITLE
Mass crafting from remote causes lag spike?

### ISSUE THREAD

**Issue by Dragonhatch1** [PrinceOfAmber/Storage-Network#274]
Minecraft version & Mod Version:
1.12.2 
Mod Version: 1.12.2-1.7.10.jar

Single player or Server:
Singleplayer with Lan Open

Describe problem (what you were doing / what happened):
when i set a recipe and shift click multiple stacks out of it, the game/remote will begin to lag and it takes several seconds for it to catch up depending on how many stacks i created.

Crash log (if any):
No crash, just continuously being laggy and unresponsive

**Comment by 62Storm** [comment]
We are having the same issue on our server. Crafting (either with the remote or on the network table) causes the most lag spikes, but now even just removing items from simple storage is causing lag ticks. It's throttling our whole server.

**Comment by Lothrazar** [comment]
if the inventories linked are poorly optimized or laggy, that will slow everything down.  Also you can try installing this to improve things https://www.curseforge.com/minecraft/mc-mods/fastworkbench
