### ISSUE TITLE
Better automation

### ISSUE THREAD

**Issue by techwiz78** [PrinceOfAmber/Storage-Network#275]
Allow processing cables to call other processing cables, allowing nested crafting of complex items that are annoying to craft individually

**Comment by techwiz78** [comment]
In addition, let export cables call processing cables, so when it tries to keep an item in stock it can make it, rather than wasting tons of resources or running out

**Comment by Lothrazar** [comment]
aside from processing cables as they exist in 1.12 no automation is currently planned. PR's welcome
