### ISSUE TITLE
Storage Remote Problem in 1.12.2

### ISSUE THREAD

**Issue by KashMon3y** [PrinceOfAmber/Storage-Network#276]
Minecraft version & Mod Version:
Minecraft 1.12.2
Simple Storage Network 1.7.10

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
The problem is occurring with the remotes. The problem is that some of the items that I have in the Storage Network are not fully appearing when using the remote from far away. For example, I have 64 sticky pistons in one of my chests that is linked to the storage network, when I travel far away and use the remote the 64 sticky pistons only appears as 5 sticky pistons and on some occasions, there are no sticky pistons at all when I try to search it up using the remote. The distance that this problem seems to be occurring is close to 260 blocks away from the Storage Network. I have tested this with all four of the remotes, and aside from the basic remote, the other three remotes are all displaying this problem. 

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
Please make sure everything is in a loaded chunk.  Spawn chunks are always loaded by default https://minecraft.gamepedia.com/Spawn_chunk  , or you can look up 'chunk loader' mods.
If the cables cross a chunk boundry and the chest or link cable is unloaded, that part is unreachable.  Or if the entire network is unloaded the remotes wont open
