### ISSUE TITLE
Upgraded Storage Remote stops working after +/- 100 blocks for the Network Master

### ISSUE THREAD

**Issue by Moshkown** [PrinceOfAmber/Storage-Network#277]
Minecraft version & Mod Version:
1.12.2

Single player or Server:
Server, R.A.D.

Describe problem (what you were doing / what happened):
We have been using the storage system for weeks now without any issues. Went 8000 blocks away and everything worked fine, without chunkloaders or someone near the Network Master.

But now suddenly that changed, I can't use the Remote after +/- 100 blocks and have to walk 10 blocks back for it to work again after it failing (when I only move 1 block at a time). I have tried every solution I could find and none of them work for me.

To be clear, I have now put a Chunk Loader next to the Master Network, I've crafted a new remote, I've removed chest/beds that were recently placed, I've let myself die, I've replaced the Master Network on a different coordinates, I've removed Optifine. The frustrating thing is that this issue came out of nowhere after the system having worked perfectly for weeks. I wasn't changing anything to the system aswell when it started happening

**Comment by Moshkown** [comment]
To be clear, I have no put a Chunk Loader next to the Master Network, I've crafted a new remote, I've removed chest/beds that were recently placed, I've let myself die, I've replaced the Master Network on a different coordinates, I've removed Optifine. The frustrating thing is that this issue came out of nowhere after the system having worked perfectly for weeks. I wasn't changing anything to the system aswell when it started happening

**Comment by Alyaqdhans** [comment]
Try using "FTB Utilities mod" and go on claimed chunks section top left inventory that looks like a map (shift click the chunk) to make the chunk where is your storage loaded, hopefully it will be fixed.

**Comment by Lothrazar** [comment]
Aly is correct, also See https://github.com/Lothrazar/Storage-Network/issues/276
