### ISSUE TITLE
Repeated lag from crafting messages

### ISSUE THREAD

**Issue by someaddons** [PrinceOfAmber/Storage-Network#278]
Minecraft version & Mod Version:
1.15.2
 SimpleStorageNetwork-1.15.2-0.3.2.jar

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Caught some lag ticks, all happening frequently~ each 10sec or so, all above 500ms. Appears to be crafting/Recipe messages related
https://spark.lucko.me/#ofQftrxhDg

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
I clicked on the link you gave and expanded all the items.  The link you provided says its coming from Mekanism, so im not sure why it was reported here?   https://github.com/mekanism/Mekanism/issues


i took a screenshot  of your linked website after opening it all up
![2020-06-21 17_08_17-Profile at 3_53PM 5_9_2020](https://user-images.githubusercontent.com/621529/85238301-f0f7b300-b3e1-11ea-9a43-4e73e559c6b6.png)
