### ISSUE TITLE
Master Tile not Found closes GUI

### ISSUE THREAD

**Issue by klugemonkey** [PrinceOfAmber/Storage-Network#279]
I'm running the RAD modpack on 1.15.2 with the 1.12.2-1.7.10 version on a multi-player server.

I have a storage network, works fine for a single person.  When I have two Storage Request Tables in a network, and players are in both, the interface closes if someone is already using.

Even weirder, when I connect a furnace to the network using two Storage Import Cables and a Storage Export Cable, and feed it some Wood logs on the top, and Sticks from the side it imports properly, smelts, and exports properly.  But the smelting is not constant, I think because of the sticks, so the furnace goes on and off.

But anyway, when I have this setup, when I go into the Storage Request Table, it closes after a second, just like there was another user in the interface.

Furthermore, in the logs there is a message from [storagenetwork] that says "Container closing, master tile not found".  No crashes occur, but functionality is impaired.

My expectation is that multiple users should be able to use separate Storage Requests Tables simultaneously as well as when other import/export Cables are attached to the network.

Any help would be appreciated.

**Comment by Midnex** [comment]
This also happens when connected to Tinkers Construct Casting Basins and other blocks. Makes it virtually unusable.

**Comment by Lothrazar** [comment]
If main tile is not in a loaded chunk the network will fail, this is unavoidable

**Comment by staviq** [comment]
https://i.imgur.com/uPwYm7Y.jpg
https://i.imgur.com/YfEM43K.jpg

This problem does not seem to have anything to do with chunkloading.

My whole base is like 12x12 blocks, right on the screenshot you can see my entire storage network, my base and all neighbouring chunks are chunkloaded.

There is a vanilla chest, right in the very center of the screnshot, if i connect it to to the network, i cannot open the interface. If i disconnect it it works again.

I tested on 1.7.10, 1.7.11, and 1.8.0

The only diffrence seems that on the never version there is no message on the console ob neither side.

**Comment by staviq** [comment]
Please reopen, the mod is completly unusable with this bug.

**Comment by Jeffmagma** [comment]
I have this problem as well, the storage request table causes this issue but the storage remotes don't. My entire storage system is currently in a 2x5 area so I am sure it is all chunkloaded as well

**Comment by Freakous** [comment]
I created an account just to bring this up, this is NOT due to it being outside of a loaded chunk. I have been trying to use this mod in Sky Factor 4 and it is completely unplayable, you CAN'T be pouring ore from a tinker's construct building while using this mod, it just will not function. It keeps giving the same Container closing, master tile not found error in the server command console despite me placing them right next to the inventory panel and smelter right next to each other. Do not close this bug, it is an issue, and not intended.
