### ISSUE TITLE
Exporter only works sometimes

### ISSUE THREAD

**Issue by jerry2478** [PrinceOfAmber/Storage-Network#281]
Minecraft version & Mod Version:
15.2 0.3.2

Single player or Server:
server

Describe problem (what you were doing / what happened):
Exporter does not work consistently. Exports sometimes and some item but not others. I have one set to export seeds and beetrooot seeds, this only exports seeds. The one I have set up for ore works sometimes. The coal and infernium seeds does not work.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
I have been testing with coal, different seed types, slabs, stairs, blocks, etc.  So far the import moves consistently.  its slow by default without upgrades.

How big is your network?  Is it possible the master network node is in an unloaded chunk or something?

**Comment by Lothrazar** [comment]
I found a bug with the Import button ("letter I") that was messing up the filter, im guessing that must be the cause.  it was filtering in and out items that werent shown in the filter slots

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/2985634
