### ISSUE TITLE
Deleting Items

### ISSUE THREAD

**Issue by EdwinTheNuke** [PrinceOfAmber/Storage-Network#282]
Minecraft version & Mod Version:
Minecraft 1.12.2 Simple Storage 1.12.2-1710 Playing on Journey Across The Void

Single player or Server:
Single

Describe problem (what you were doing / what happened):
Items dropped or shift clicked into either the storage request table or the trans dimensional storage remote are deleted unless I have a designated storage for them,  I have 60 filing cabinets, 2 small crates and 2 large crates connected with the large crates having priority over the small crates,  It started happening after I connected the large crates,  

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by EdwinTheNuke** [comment]
I replaced the large crates with small ones again,  Still deleting,  I broke and replaced the storage connectors to the crates,  Still deleting.  I rebooted my machine.  Still deleting.

**Comment by EdwinTheNuke** [comment]
It doesn't always delete the objects just nearly always,
83 Storage Cables
65 Storage Link Cables
9 Storage Export Cables
7 Storage Import Cables
1 Storage Request Table

**Comment by EdwinTheNuke** [comment]
Storage Link Cable Connections:
60 Filing Cabinets - (priority 0) - Real Filing Cabinet
-49 with 8 folders
-1 with 4 folders
-10 empty
4 Small Storage Crates - (priority 25, 30, 35 40) - Actually Additions
1 Storage Container with 9 Storage Crates in it - (priority 0) - BDS&M

**Comment by EdwinTheNuke** [comment]
I swapped out the crates for memory chests and it still happens.  If I put something in the crafting area and clear the grid it is not deleted.

**Comment by Lothrazar** [comment]
Thanks for all the detailed info.  Are you using https://www.curseforge.com/minecraft/mc-mods/fastworkbench ? 

Also It sounds like a bug with one of the connected containers, is there a way to narrow it down to only one mod
