### ISSUE TITLE
Suggestion: A block/interface that lets other mods see the network as a valid inventory.

### ISSUE THREAD

**Issue by ajsnarr98** [PrinceOfAmber/Storage-Network#283]
Suggestion: Make storage network master block a valid inventory (or add a block that works like this) so that the items in the system can be accessed by other mods.

I am an experienced java programmer (albeit not with minecraft mods and I might be able to help with this issue if needed).

**Comment by Lothrazar** [comment]
I would love some help with this. I have accepted many pull requests from other modders to this repository.



Basically a chest has the ItemStack handler capability.  so the Main network node would have to output this capability and somehow wrap every stack in the network into this capability

**Comment by ajsnarr98** [comment]
~~Doesn't TileMain somewhat already provide this capability through the getStacks() method? Would making the inventory accesible be as simple as implementing the `IItemHandler, IItemHandlerModifiable, INBTSerializable<NBTTagCompound>` interfaces?~~

~~Would one need to implement a different interface that returns a ItemStackHandler object with the inventory wrapped inside it?~~

~~What interface would make a block an inventory?~~

Edit: I went and looked back at docs and I think I figured it out.

**Comment by ajsnarr98** [comment]
https://github.com/Lothrazar/Storage-Network/pull/287

**Comment by Lothrazar** [comment]
This is on the way to 1.16.  two blocks, one acts as input only like a hopper, and another block that is the interface. refined storage item External Storage connector plugs into it and connects both ways . just like the PR but on another block insetad of the TileMain

**Comment by Lothrazar** [comment]
test videos https://twitter.com/lothrazar/status/1330239257877880832

**Comment by ajsnarr98** [comment]
sweet!
