### ISSUE TITLE
Export cable fills inventories with only one item type from filter

### ISSUE THREAD

**Issue by AngleWyrm10** [PrinceOfAmber/Storage-Network#285]
The export cable that exports from the network into an inventory just keeps on filling the inventory with a single item type from the filter for as long as that item is available to the network.

**Steps to reproduce**
- Put a double-chest filled with cobblestone and one stack of torches onto a network with an _import_ cable
- Put a single chest on the network with an _export_ cable
- Set the _export_ cable filter to accept both cobblestone and torches

**Suggestion** 
Export items the inventory is out of (or lowest on) first, or a keep-a-stack-here button on the filter, or some sort of round-robin button on the filter GUI so it will do them all.

Note this may be related to issue #281

---
Minecraft v1.12.2, Simple Storage Network v1.12.2-1.7.10

**Comment by Lothrazar** [comment]
https://github.com/Lothrazar/Storage-Network/issues/281 is resolved
