### ISSUE TITLE
Doesn't support the chest tag/oredict and only supports basic vanilla chests when crafting the inventory cables.

### ISSUE THREAD

**Issue by Divineaspect** [PrinceOfAmber/Storage-Network#286]
Minecraft version & Mod Version:
1.15.2 - 1.1.0

Single player or Server:
Both

Describe problem (what you were doing / what happened):
Doesn't support the chest tag/oredict and only supports basic vanilla chests when crafting the inventory cables.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/2990699
