### ISSUE TITLE
Mod Conflict

### ISSUE THREAD

**Issue by Alyaqdhans** [PrinceOfAmber/Storage-Network#288]
Minecraft version & Mod Version:
-1.12.2
-Latest mod version

Single player or Server:
-Single player

Describe problem (what you were doing / what happened):
-There's a mod conflict with "Fast WorkBench", the problem is I can shift click the opened remote and move it around, it happens for all of the remotes except one "Simple Storage Remote".

-This problem doesn't exist without "Fast WorkBench".

**Comment by Lothrazar** [comment]
version of both mods not listed. also this dependency is optional, it is not required. with latest forge and latest of both mods is up to you
