### ISSUE TITLE
Lag Spike then server crash

### ISSUE THREAD

**Issue by Griffin224** [PrinceOfAmber/Storage-Network#29]
Keep getting huge lag spikes then a server crash, happens every ten or so minutes.
[crash-2017-08-28_11.12.01-server.txt](https://github.com/PrinceOfAmber/Storage-Network/files/1257260/crash-2017-08-28_11.12.01-server.txt)
there is the crash file.

**Comment by PrinceOfAmber** [comment]
Hey, sorry i havent replied in so long. 


I am looking into this now this week.  Aiming for a release by friday if not sooner

**Comment by PrinceOfAmber** [comment]
Does your network cross chunk boundaries? Is it connected to lots of things? any pipes that are really long? Just trying to mirror my test case so it matches yours.  Releasing a version tonight and then anther this weekend if i have to.  I dont know if ive covered 100% of the cases though

**Comment by PrinceOfAmber** [comment]
No updates and appears fixed.  many new versions have been out since this version anyway
