### ISSUE TITLE
Charcoal duplication through processing cable

### ISSUE THREAD

**Issue by LeonardoStrik** [PrinceOfAmber/Storage-Network#291]
Minecraft version & Mod Version:
1.12.2 - 1.7.8
I am playing on SF 4 and therefore have FastFurnace installed,  I don't know whether this is relevant.

Single player or Server:
Singleplayer

Describe problem (what you were doing / what happened):
 When using the processing cable to automate charcoal production in a furnace, as such:
![2020-07-22_13 00 34](https://user-images.githubusercontent.com/61874207/88168898-6641e800-cc1b-11ea-9fb6-e5678e71916b.png)
When I put oak logs in the chest, they are exported to the furnace as expected. However, an equivalent amount of coal is immediately created in the chest, while the logs are still processing in the furnace. Thhus, the charcoal is duped, and made with 0 processing time.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
could be a modpack issue. closed as old stale versions. trying to keep 1.12 feature complete for consistency, new issues always welcome. seems to be working as intended on latest branch.
