### ISSUE TITLE
[1.16.1] Receipe Broken

### ISSUE THREAD

**Issue by BedrockLegends** [PrinceOfAmber/Storage-Network#292]
Minecraft version & Mod Version:
1.16.1
32.0.75
1.0.0

Single player or Server:
Both

Describe problem (what you were doing / what happened):
Broken recipe
![2020-07-22_17 49 12](https://user-images.githubusercontent.com/48525410/88237059-0ad82000-cc44-11ea-91c8-5bf118eb103a.png)

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
Doesnt seem very broken. actually even in your picture its not broken so  i dont even know what is up 
![292](https://user-images.githubusercontent.com/621529/90721247-37944d00-e26d-11ea-9887-64e8ada38fef.gif)
