### ISSUE TITLE
Rendering Screen Crash

### ISSUE THREAD

**Issue by TobyTech28** [PrinceOfAmber/Storage-Network#294]
**Minecraft version & Mod Version:**

Minecraft Version: 1.16.1
Mod Version: 1.16.1-1.0.0

**Single player or Server:**

Both on Single Player and Server

**Describe problem (what you were doing / what happened):**

Any time I try to use anything from the mod it freezes and crashes the game. I will be able to craft some cables and place them or open the storage request table for a few seconds and then it crashes. I'm not smart enough or even know what to look for in the crash report. It seems to say something about the GUI. I have added the mod into an already made pack called Valhelsia 3 - 1.16 Version 3.0.7 along with some other mods. I have Included all crash logs and other mods. The mod pack can be found on the twitch launcher.

**Extra Mods:**
[Extra Mods.zip](https://github.com/Lothrazar/Storage-Network/files/4977073/Extra.Mods.zip)

**Crash Reports:**
[crash-2020-07-25_02.02.49-client.txt](https://github.com/Lothrazar/Storage-Network/files/4977066/crash-2020-07-25_02.02.49-client.txt)
[crash-2020-07-25_02.14.29-client.txt](https://github.com/Lothrazar/Storage-Network/files/4977067/crash-2020-07-25_02.14.29-client.txt)
[crash-2020-07-25_02.20.12-client.txt](https://github.com/Lothrazar/Storage-Network/files/4977068/crash-2020-07-25_02.20.12-client.txt)
[crash-2020-07-25_02.34.05-client.txt](https://github.com/Lothrazar/Storage-Network/files/4977069/crash-2020-07-25_02.34.05-client.txt)
[crash-2020-07-25_22.33.36-client.txt](https://github.com/Lothrazar/Storage-Network/files/4977070/crash-2020-07-25_22.33.36-client.txt)

I have taken out the mod and everything works fine with all the other added mods I will update if other mods make the game crash also. Thank you for reading and thank you very much if you try to help me!

**Comment by moolchand-danny** [comment]
I am also experiencing this problem. Same NoSuchMethodError crash. I've attached my log as well for proof. 
[crash-2020-07-25_23.12.01-client.txt](https://github.com/Lothrazar/Storage-Network/files/4977090/crash-2020-07-25_23.12.01-client.txt)

**Comment by Mowmaster** [comment]
Also encountered this issue on my server. (client crash, sane render screen issue)

**Comment by Stiftoad** [comment]
Also encountered this one heres mine:
https://gist.github.com/Stiftoad/8dd560444dc440f8faeba8ffe22d55ad
