### ISSUE TITLE
game crash when connect the wire from the chests to the system and open the crafting GUI [1.16.1]

### ISSUE THREAD

**Issue by KhanhPham05** [PrinceOfAmber/Storage-Network#297]
Minecraft version & Mod Version:
1.16.1-1.0.0

Single player or Server:
Single

Describe problem (what you were doing / what happened):
on the title

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Stiftoad** [comment]
Same problem on server.
Client crashes but not the Server.

Dont know exactly if its the gui or trying to store items

https://gist.github.com/Stiftoad/8dd560444dc440f8faeba8ffe22d55ad

**Comment by Knito58** [comment]
https://pastebin.com/pAdf3hNj

New world, new storage system.

**Comment by krlsmnk** [comment]
Same issue here. 1.16.1 brand new creative single player superflat world. 
Crashes client when right clicking the Storage Request Table. 
Crash report mentions a text rendering issue. 

[crash-2020-08-02_23.52.22-client.txt](https://github.com/Lothrazar/Storage-Network/files/5017428/crash-2020-08-02_23.52.22-client.txt)
