### ISSUE TITLE
Shift clicking recipe from JEI into SSN crafting table causes server disconnect

### ISSUE THREAD

**Issue by TheDarkPreacher** [PrinceOfAmber/Storage-Network#30]
Using version 1.12-1.0.14. Shift clicked a recipe from JEI into the crafting table interface, got the following message after being disconnected from the server: https://imgur.com/a/Hh2C8

No other players effected that were on the server as well. Playing on the AllTheCreators server.

**Comment by PrinceOfAmber** [comment]
Do you have anything from the crash-logs folder or /logs/ folder? on server or client?

Sounds like a client side crash if its just you.   In my quick tests it doesnt happen on my localhost desktop server so a log would be great 👍

**Comment by TheDarkPreacher** [comment]
I'll check and see if there is a log, and get you a pastebin link for it.

**Comment by TheDarkPreacher** [comment]
Found the log, and the error that caused the clientside disconnect from the
server. Line 143 of this paste: https://pastebin.com/4DdLg506

On Tue, Sep 19, 2017 at 1:53 AM, The DarkPreacher <thedarkpreacher@gmail.com
> wrote:

> I'll check and see if there is a log, and get you a pastebin link for it.
>

**Comment by TheDarkPreacher** [comment]
Not sure if this is something that should be worried over, but on server startup, we get this: https://pastebin.com/47DdsGdb

same version as the one that is causing the client disconnect for me.

**Comment by PrinceOfAmber** [comment]
thanks for the logs

For the one on startup, the one where it goes cofh.thermaldynamics.block.BlockDuct.func_176201_c(BlockDuct.java:109)

Basically storage network gets a "oh a block nearby changed" event, and tries to see of those blocks can connect to the network, and of course catch any errors.    But then somehow, some way, some code in Thermal Dynamics is also trying to go "oh this is a thermal dynamic duct, get the metadata and block state of it" so of course Minecraft goes "hey thermal this metadata is invalid; this storage network block does not HAVE a blockstate for that integer that wont work" .  Not sure whose at fault but ill but some links around here.   for future reference.
https://github.com/CoFH/ThermalDynamics/blob/3d5f288c51590d7f60f0476fdc0b20d7ee389a03/src/main/java/cofh/thermaldynamics/block/BlockDuct.java#L63

https://github.com/PrinceOfAmber/Storage-Network/blob/master/src/main/java/mrriegel/storagenetwork/AbstractBlockConnectable.java#L18

https://github.com/PrinceOfAmber/Storage-Network/issues/23

**Comment by Blatts12** [comment]
The same with Real Filing Cabinet

**Comment by PrinceOfAmber** [comment]
Fixed in previous version but forgot to update issue. Latest build is 1.2.2
