### ISSUE TITLE
Crash in gui when typing in search bar

### ISSUE THREAD

**Issue by astocky** [PrinceOfAmber/Storage-Network#300]
Minecraft version & Mod Version:
1.16.1, Forge 32.0.108, SSN 1.16.1-1.0.0

Single player or Server:
Single

Describe problem (what you were doing / what happened):
Tried to search in gui and it locked up then crashed

Crash log (if any):
https://pastebin.com/UHrbm5Rg

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by krlsmnk** [comment]
Having the same problem. Any time I access the storage terminal, it crashes the client.

**Comment by HiddenGhost121** [comment]
Same here, every time I try and scroll over the terminal interface the game crashes and says it had trouble rendering the screen. Although this does not happen when I have Optifine installed, but that comes with its own visual glitches too like chest, arms, mekanism cables, botania's guide book, and applied energetics facades showing as black and purple textures

**Comment by artimadours** [comment]
Crashing for me too. here is the crash report.

---- Minecraft Crash Report ----
// There are four lights!

Time: 8/23/20 10:49 AM
Description: Rendering screen

java.lang.NoSuchMethodError: net.minecraft.client.gui.screen.Screen.renderTooltip(Lcom/mojang/blaze3d/matrix/MatrixStack;Ljava/util/List;IILnet/minecraft/client/gui/FontRenderer;)V
	at com.lothrazar.storagenetwork.gui.NetworkWidget.drawGuiContainerForegroundLayer(NetworkWidget.java:231) ~[?:1.16.1-1.0.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.request.GuiNetworkTable.func_230451_b_(GuiNetworkTable.java:130) ~[?:1.16.1-1.0.0] {re:classloading}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at com.lothrazar.storagenetwork.block.request.GuiNetworkTable.func_230430_a_(GuiNetworkTable.java:80) ~[?:1.16.1-1.0.0] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:327) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:951) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.108.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$465/993023654.call(Unknown Source) [forge-1.16.1-32.0.108.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.lothrazar.storagenetwork.gui.NetworkWidget.drawGuiContainerForegroundLayer(NetworkWidget.java:231)
	at com.lothrazar.storagenetwork.block.request.GuiNetworkTable.func_230451_b_(GuiNetworkTable.java:130)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:122)
	at com.lothrazar.storagenetwork.block.request.GuiNetworkTable.func_230430_a_(GuiNetworkTable.java:80)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:327)

-- Screen render details --
Details:
	Screen name: com.lothrazar.storagenetwork.block.request.GuiNetworkTable
	Mouse location: Scaled: (638, 337). Absolute: (1277.000000, 675.000000)
	Screen size: Scaled: (1280, 720). Absolute: (2560, 1440). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Artimadours'/1174927, l='ClientLevel', x=78.87, y=77.00, z=-115.23]]
	Chunk stats: Client Chunk Cache: 729, 484
	Level dimension: minecraft:overworld
	Level spawn location: World: (160,90,-64), Chunk: (at 0,5,0 in 10,-4; contains blocks 160,0,-64 to 175,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1537192 game time, 56469 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:446)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:598)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$465/993023654.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1210146712 bytes (1154 MB) / 5829558272 bytes (5559 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 16
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9216m -Xms256m -XX:PermSize=256m
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.108.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.108
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		Uppers-0.3.0.jar Uppers {uppers@0.3.0 DONE}
		SilentMechanisms-1.16.1-0.8.1+62.jar Silent's Mechanisms {silents_mechanisms@0.8.1+62 DONE}
		KleeSlabs_1.16.1-9.0.0.jar KleeSlabs {kleeslabs@9.0.0 DONE}
		sleeping_bags-1.16.1-1.0.3.jar Sleeping Bags {sleeping_bags@1.16.1-1.0.3 DONE}
		ForgeEndertech-1.16.1-7.0.1.0-build.0008.jar Forge Endertech {forgeendertech@7.0.1.0 DONE}
		XaerosWorldMap_1.10.1_Forge_1.16.1.jar Xaero's World Map {xaeroworldmap@1.10.1 DONE}
		CTM-MC1.16.1-1.1.1.4.jar ConnectedTexturesMod {ctm@MC1.16.1-1.1.1.4 DONE}
		CookingForBlockheads_1.16.1-9.0.2.jar Cooking for Blockheads {cookingforblockheads@9.0.2 DONE}
		Controlling-7.0.0.3.jar Controlling {controlling@7.0.0.3 DONE}
		Placebo-1.16.1-4.1.3.jar Placebo {placebo@4.1.3 DONE}
		dankstorage-3.8.jar Dank Storage {dankstorage@3.8 DONE}
		citadel-1.2.0.jar Citadel {citadel@1.2.0 DONE}
		darkerloadingscreen-2.1.jar Darker Loading Screen {darkerloadingscreen@2.1 DONE}
		Powah-1.16.1-2.2.0.jar Powah {powah@2.2.0 DONE}
		rangedpumps-0.8.jar Ranged Pumps {rangedpumps@0.8 DONE}
		WitherSkeletonTweaks-1.16.1-5.0.0.jar Wither Skeleton Tweaks {wstweaks@5.0.0 DONE}
		Bookshelf-1.16.1-6.3.20.jar Bookshelf {bookshelf@6.3.20 DONE}
		guardvillagers-1.16.1-1.1.1.jar Guard Villagers {guardvillagers@1.1.1 DONE}
		u_team_core-1.16.1-3.1.3.170.jar U Team Core {uteamcore@3.1.3.170 DONE}
		buildinggadgets-3.5.1.jar Building Gadgets {buildinggadgets@3.5.1 DONE}
		DarkUtilities-1.16.1-4.0.3.jar Dark Utilities {darkutils@4.0.3 DONE}
		Apotheosis-1.16.1-4.1.2.jar Apotheosis {apotheosis@4.1.2 DONE}
		ironshulkerboxes-1.16.1-5.0.1.jar Iron Shulker Boxes {ironshulkerbox@1.16.1-5.0.1 DONE}
		MekanismGenerators-1.16.1-10.0.9.432.jar Mekanism: Generators {mekanismgenerators@10.0.9 DONE}
		StoneChest-1.16.1-1.0.1.jar Stone Chest {stonechest@1.0.1 DONE}
		JustEnoughResources-1.16.1-0.11.1.93.jar Just Enough Resources {jeresources@0.11.1.93 DONE}
		shetiphiancore-1.16-3.8.0.jar ShetiPhian-Core {shetiphiancore@3.8.0 DONE}
		MysticalAgradditions-1.16.1-4.0.0.jar Mystical Agradditions {mysticalagradditions@4.0.0 DONE}
		refinedstorage-1.9.2.jar Refined Storage {refinedstorage@1.9.2 DONE}
		structure-gel-api-1.16.1-1.2.1.jar Structure Gel API {structure_gel@1.2.1 DONE}
		industrial-foregoing-1.16.1-3.0.5-7e692e4.jar Industrial Foregoing {industrialforegoing@3.0.5 DONE}
		useful_backpacks-1.16.1-1.11.2.74.jar Useful Backpacks {usefulbackpacks@1.11.2.74 DONE}
		torchmaster-2.3.2-alpha.jar Torchmaster {torchmaster@2.3.2-alpha DONE}
		resourcefulbees-1.16.1-0.3.8a.jar Resourceful Bees {resourcefulbees@1.16.1-0.3.8a DONE}
		endertanks-1.16-1.9.0.jar EnderTanks {endertanks@1.9.0 DONE}
		BiomesOPlenty-1.16.1-11.0.0.395-universal.jar Biomes O' Plenty {biomesoplenty@1.16.1-11.0.0.395 DONE}
		MekanismAdditions-1.16.1-10.0.9.432.jar Mekanism: Additions {mekanismadditions@10.0.9 DONE}
		Lollipop-1.16.1-3.0.0.jar Lollipop {lollipop@3.0.0 DONE}
		ironfurnaces-1.16.1-2.1.1.jar Iron Furnaces {ironfurnaces@2.1.1 DONE}
		simplefarming-1.16.1-1.3.2.jar Simple Farming {simplefarming@1.16.1-1.3.2 DONE}
		curios-FORGE-1.16.1-3.0.0.2.jar Curios API {curios@FORGE-1.16.1-3.0.0.2 DONE}
		Botania-1.16-402.jar Botania {botania@1.16-402 DONE}
		gardenofglass-1.4.jar Garden of Glass {gardenofglass@1.4 DONE}
		Patchouli-1.16-39.jar Patchouli {patchouli@1.16-39 DONE}
		EndReborn [0.7.5].jar End: Reborn {endreborn@0.7.5 DONE}
		elevatorid-1.16.1-1.7.3.jar Elevator Mod {elevatorid@1.16.1-1.7.3 DONE}
		Runelic-1.16.1-1.0.6.jar Runelic {runelic@1.0.6 DONE}
		MekanismTools-1.16.1-10.0.9.432.jar Mekanism: Tools {mekanismtools@10.0.9 DONE}
		AI-Improvements-1.16.1-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		trashcans-1.0.3-mc1.16.1.jar Trash Cans {trashcans@1.0.3 DONE}
		BetterBurning-1.16.1-2.0.2.jar BetterBurning {betterburning@2.0.2 DONE}
		FastLeafDecay-v23.jar FastLeafDecay {fastleafdecay@v23 DONE}
		QuantumStorage-1.16.1-5.2.0.jar QuantumStorage {quantumstorage@NONE DONE}
		Cyclic-1.16.1-0.6.1.jar Cyclic {cyclic@1.16.1-0.6.1 DONE}
		BetterAdvancements-1.16.1-0.1.0.100.jar Better Advancements {betteradvancements@0.1.0.100 DONE}
		inventorysorter-1.16.1-18.0.0.jar Simple Inventory Sorter {inventorysorter@18.0.0 DONE}
		SimplyJetpacks2-1.16.1-2.3.0.1.jar Simply Jetpacks 2 {simplyjetpacks@1.16.1-2.3.0.1 DONE}
		forgeautofish-1.0.5-1.16.1.jar AutoFish for Forge {forgeautofish@1.0.5 DONE}
		Cucumber-1.16.1-4.0.2.jar Cucumber Library {cucumber@4.0.2 DONE}
		GooglyEyes-1.16.1-9.0.0.jar GooglyEyes {googlyeyes@9.0.0 DONE}
		jei-1.16.1-7.0.1.10.jar Just Enough Items {jei@7.0.1.10 DONE}
		metalbarrels-3.2b.jar Metal Barrels {metalbarrels@3.2b DONE}
		the-conjurer-1.16.1-1.0.8.jar The Conjurer {conjurer_illager@1.0.8 DONE}
		Abnormals-Core-1.16.1-2.0.2.jar Abnormals Core {abnormals_core@2.0.2 DONE}
		Buzzier-Bees-1.16.1-2.0.1.jar Buzzier Bees {buzzier_bees@2.0.1 DONE}
		Mekanism-1.16.1-10.0.9.432.jar Mekanism {mekanism@10.0.9 DONE}
		Upgrade-Aquatic-1.16.1-2.0.1.jar Upgrade Aquatic {upgrade_aquatic@2.0.1 DONE}
		excavation-1.5.1.jar Excavation {excavation@1.5.1 DONE}
		Extra-Boats-1.16.1-1.4.1.jar Extra Boats {extraboats@1.4.1 DONE}
		Waystones_1.16.1-7.1.1.jar Waystones {waystones@7.1.1 DONE}
		Clumps-6.0.0.4.jar Clumps {clumps@6.0.0.4 DONE}
		appliedenergistics2-8.0.0-beta.1.jar Applied Energistics 2 {appliedenergistics2@8.0.0-beta.1 DONE}
		NaturesCompass-1.16.1-1.8.5.jar Nature's Compass {naturescompass@1.16.1-1.8.5 DONE}
		SimpleStorageNetwork-1.16.1-1.0.0.jar Simple Storage Network {storagenetwork@1.16.1-1.0.0 DONE}
		BasicNetherOres-1.16.1-5.1.0.jar Basic Nether Ores {bno@5.1.0 DONE}
		charginggadgets-1.1.1.jar Charging Gadgets {charginggadgets@1.1.1 DONE}
		japanese_food_mod-1.16.1-1.0.4-fixed.jar japanese_food_mod {japanese_food_mod@1.16.1-1.0.4-fixed DONE}
		JEITweaker-1.16.1-1.0.1.2.jar JEI Tweaker {jeitweaker@1.0.1.2 DONE}
		PackingTape-1.16.1-0.9.6.jar Packing Tape {packingtape@0.9.6 DONE}
		iChunUtil-1.16.1-9.0.0.jar iChunUtil {ichunutil@9.0.0 DONE}
		mininggadgets-1.4.1.jar Mining Gadgets {mininggadgets@1.4.1 DONE}
		endercompass-3.0.jar Ender Compass {endercompass@3.0 DONE}
		CraftTweaker-1.16.1-7.0.0.23.jar CraftTweaker {crafttweaker@7.0.0.23 DONE}
		extradisks-1.16.1-1.3.1.jar Extra Disks {extradisks@1.3.1 DONE}
		forge-1.16.1-32.0.108-universal.jar Forge {forge@32.0.108 DONE}
		Waddles-1.16.1-0.8.7.jar Waddles {waddles@1.16.1-0.8.7 DONE}
		Bones-1.16.1-1.3.2.jar Bones {bones@1.16.1-1.3.2 DONE}
		simpletomb-1.16.1-1.0.0.jar Example Mod {simpletomb@1.16.1-1.0.0 DONE}
		scuba-gear-1.16.1-1.0.1.jar Scuba Gear {scuba_gear@1.0.1 DONE}
		MiniCoal2-1.16.1-0.0.2-universal.jar MiniCoal 2 {minicoal2@{{version}} DONE}
		MysticalAgriculture-1.16.1-4.0.2.jar Mystical Agriculture {mysticalagriculture@4.0.2 DONE}
		ironchest-1.16.1-11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 DONE}
		forge-1.16.1-32.0.108-client.jar Minecraft {minecraft@1.16.1 DONE}
		theoneprobe-1.16-3.0.1-beta.jar The One Probe {theoneprobe@1.16-3.0.1-beta DONE}
		swingthroughgrass-1.16.1-1.5.1.jar SwingThroughGrass {swingthroughgrass@1.16.1-1.5.1 DONE}
		MouseTweaks-2.13-mc1.16.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		titanium-1.16.1-3.0.4.jar Titanium {titanium@3.0.4 DONE}
		ImmersiveEngineering-1.16.1-3.2.0-115.jar Immersive Engineering {immersiveengineering@1.16.1-3.2.0-115 DONE}
		EasierSleeping-1.16.1-1.0.2.jar Easier Sleeping {easier_sleeping@1.0.2 DONE}
		compactores-1.16.1-3.0.0.jar Compact Ores {compactores@3.0.0 DONE}
		SilentLib-1.16.1-4.7.0+58.jar Silent Lib {silentlib@4.7.0+58 DONE}
		AdLods-1.16.1-4.0.0.0-build.0007.jar Large Ore Deposits {adlods@4.0.0.0 DONE}
		Xaeros_Minimap_20.20.1_Forge_1.16.1.jar Xaero's Minimap {xaerominimap@20.20.1 DONE}
		rats-6.0.5-1.16.1.jar Rats {rats@6.0.5 DONE}
		ftb-backups-2.1.1.6.jar FTB Backups {ftbbackups@2.1.1.6 DONE}
		lava-monster-1.16.1-1.0.7.jar Lava Monster {lava_monster@1.0.7 DONE}
		FastWorkbench-1.16.1-4.2.0.jar FastWorkbench {fastbench@4.2.0 DONE}
		AutoRegLib-1.6-43.jar AutoRegLib {autoreglib@1.6-43 DONE}
		Quark-r2.2-260.jar Quark {quark@r2.2-260 DONE}
		StorageDrawers-1.16.2-8.1.0.jar Storage Drawers {storagedrawers@1.16.2-8.1.0 DONE}
		enderchests-1.16-1.7.0.jar EnderChests {enderchests@1.7.0 DONE}
		DoubleSlabs-1.16-3.3.3.jar Double Slabs {doubleslabs@3.3.3 DONE}
		structurize-0.13.44-ALPHA.jar Structurize {structurize@0.13.44-ALPHA DONE}
		minecolonies-0.13.163-ALPHA-universal.jar Minecolonies {minecolonies@0.13.163-ALPHA DONE}
		FastFurnace-1.16.1-4.1.1.jar FastFurnace {fastfurnace@4.1.1 DONE}
		hunterillager-1.16.1-1.0.3.jar HunterIllager {hunterillager@1.0.2 DONE}
		AppleSkin-mc1.16.1-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		solcarrot-1.16.1-1.9.7.jar Spice of Life: Carrot Edition {solcarrot@1.16.1-1.9.7 DONE}
		BackTools-1.16.1-9.0.0.jar Back Tools {backtools@9.0.0 DONE}
		betterbedrockgenerator-1.16.1-0.1.0.jar Better Bedrock Generator {betterbedrockgenerator@0.1.0 DONE}
		refinedstorageaddons-0.7.jar Refined Storage Addons {refinedstorageaddons@0.7 DONE}
		CosmeticArmorReworked-1.16.1-v1b.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.1-v1b DONE}
		SoundFilters-0.14_for_1.16.jar Sound Filters {soundfilters@0.14_for_1.16 DONE}
		overloadedarmorbar-5.0.0.jar Overloaded Armor Bar {overloadedarmorbar@5.0.0 DONE}
	Patchouli open book context: n/a
	Launched Version: forge-32.0.108
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.06, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor

**Comment by hron84** [comment]
Same.

**Comment by Lothrazar** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/3060680
