### ISSUE TITLE
storage becomes transparent

### ISSUE THREAD

**Issue by loonywolf** [PrinceOfAmber/Storage-Network#301]
Minecraft version & Mod Version: 16.1.1  

Single player or Server: single 

Opening the UI and clicking the J button  makes all the Storage become transparent,(strangle it still works can open the inventory,  still has  a collision box  )
seems to happen In Forge 13.0. 108 and its last version too 
its the new version of the Mod  1.0.0 
ps looks like a great mod i want to sort all my mess with this one, i hope theirs a  fast fix for this 
looks like a fun mod :) 

Loonywolf

**Comment by aj410** [comment]
I have the same issue.. except it is all entities, not just chests, including cows, my character, mobs etc
