### ISSUE TITLE
Expand Inventory View

### ISSUE THREAD

**Issue by Syndrome1986** [PrinceOfAmber/Storage-Network#302]
It would be great if there was a way to expand the inventory view window to better be able to see what is in the network without needing to search. If that is already there and I missed it then my apologies.

**Comment by Lothrazar** [comment]
in new minecraft (1.16, maybe 1.15) there are new tables and remotes that remove the crafting grid so the view goes all the way down. 

Is this what you mean? Or do do you mean making it super wide out to the left?

**Comment by Lothrazar** [comment]
Closed due to no response. as per previous comment is already implemented
