### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by NordicGamerFE** [PrinceOfAmber/Storage-Network#303]
Minecraft version & Mod Version:
1.12.2-1.7.11

Single player or Server:
Server
Modpack Ocean Outlast
Describe problem (what you were doing / what happened):
There is a dupe https://drive.google.com/file/d/1LOIqihlWjM6Kf3BIRtZk45qRr8mAqgRm/view

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/3116527
