### ISSUE TITLE
Quark Chest Compatability

### ISSUE THREAD

**Issue by Mystogrigen** [PrinceOfAmber/Storage-Network#304]
Minecraft version & Mod Version: 
Minecraft 1.16.1
Forge: 32.0.108

Single player or Server: Singleplayer

Describe problem (what you were doing / what happened): I can't craft the link cable with the wooden chests from quark. The recipe requires a vanilla chest. I can craft it with a vanilla chest, but none of the quark versions.

Crash log (if any): N/A

Ore dict for the chest component? forge:chests/wooden

**Comment by Lothrazar** [comment]
Converted to using forge tags for most recipes in next release :)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/3060680
