### ISSUE TITLE
Gui crash when opening storage network

### ISSUE THREAD

**Issue by CaptMir** [PrinceOfAmber/Storage-Network#306]
Minecraft version & Mod Version: minecraft 1.12.2, Mod version 1.7.10 & 1.7.11 (Updated to see if it fixed the issue)

Single player or Server: server

Describe problem (what you were doing / what happened): opened the storage gui and it crashed the game also crash with storage remote (not ever time though)

Crash log (if any):
https://paste.gg/p/anonymous/2a3a4231c90243218d83c871fb6a139c

**Comment by Lothrazar** [comment]
this is a fastbench problem seen by  at mrriegel.storagenetwork.gui.fb.GuiFastNetworkCrafter.sortItemStacks(GuiFastNetworkCrafter.java:283) , but i see you already have newest installed  FastWorkbench-1.12.2-1.7.3.jar .  You can disable fastbench by uninstalling it or disabling it in this config.

B:allowFastWorkBenchIntegration=false


Also, it seems almost like a 'timsort' mod might be doing something, but unclear
java.util.TimSort.mergeLo(TimSort.java:773)
