### ISSUE TITLE
[1.16.1] OpenGL error or crash when accessing network

### ISSUE THREAD

**Issue by DonutCatDev** [PrinceOfAmber/Storage-Network#307]
Minecraft version & Mod Version:
1.16.1 and 1.16.1-1.0.0

Single player or Server:
Both

Describe problem (what you were doing / what happened):
With Optifine enabled, accessing the network through either of the tables or the network remotes causes OpenGL error 1283(stackoverflow) and causes all entity-blocks like beds and chests to become invisible along with all player models and held items.
With Optifine disabled, accessing the network causes a total crash to desktop. 
Tested with no other mods enabled with the same results. 

Crash log (if any):

[debug.log from Optifine OpenGL errors with no crash](https://github.com/Lothrazar/Storage-Network/files/5259467/debug.log)
[Crash log from crash without Optifine](https://github.com/Lothrazar/Storage-Network/files/5259479/crash-2020-09-22_02.25.30-client.txt)

**Comment by Lothrazar** [comment]
fixed in latest version :) https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/3071526
