### ISSUE TITLE
Server Crash 1.16.3

### ISSUE THREAD

**Issue by ClaudiusMinimus** [PrinceOfAmber/Storage-Network#309]
Minecraft version & Mod Version:
Minecraft: 1.16.3
Mod version: 1.16.2-1.1.0

Single player or Server: Server

Describe problem (what you were doing / what happened):
I tried to place a Storage Request Table on the Storage Network Root and the server crashed.

Crash log (if any):
https://pastebin.com/a009TVuL

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by ClaudiusMinimus** [comment]
It also crashed when I tried to right click a remote on the Storage Network Root

**Comment by AlphaWarrior1331** [comment]
same

**Comment by Lothrazar** [comment]
fixed in latest version :) https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/3071526
