### ISSUE TITLE
Hands and Block Breaking Animation not appearing after closing the access and crafting interface

### ISSUE THREAD

**Issue by MoreKerosine** [PrinceOfAmber/Storage-Network#310]
Minecraft version & Mod Version: 1.16.1 version 1.0.0

Single player or Server: Single Player

Describe problem (what you were doing / what happened): I opened a storage crafting interface that was attached to a root and no chests or pipes. After I closed the GUI, my hands wouldn't render and the block breaking animation would not occur. Everything else worked as normal. This happened multiple times, and closing and reopening the world doesn't fix it. The only way to fix the glitch is closing minecraft entirely. I have checked to see if the glitch occurs under any other circumstances other than the one described

**Comment by Lothrazar** [comment]
fixed in latest version :) https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/3071526
