### ISSUE TITLE
Search Broken in 1.16.3

### ISSUE THREAD

**Issue by ClaudiusMinimus** [PrinceOfAmber/Storage-Network#311]
The search function is not working as shown in the screenshots. I had basalt bricks in my inventory and when I searched for it, nothing showed up. This happens for anything searched for.

Minecraft version & Mod Version:
Minecraft: 1.16.3
Mod version: 1.16.2-1.1.0

Single player or Server: Server

![2020-09-25_10 37 43](https://user-images.githubusercontent.com/17887664/94293480-8e9bda80-ff1b-11ea-90b8-a33cd9aed183.png)

![2020-09-25_10 37 55](https://user-images.githubusercontent.com/17887664/94293494-93608e80-ff1b-11ea-9522-34dc4009a246.png)

**Comment by Lothrazar** [comment]
Thanks for reporting. 1.1.1 has a fix https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/3060930
