### ISSUE TITLE
Suggestion: allow link cable segments to link to multiple containers

### ISSUE THREAD

**Issue by WrongWeekend** [PrinceOfAmber/Storage-Network#312]
Currently a link cable segment can only connect itself to a single container. Allowing each segment to connect to multiple containers from multiple sides would be particularly helpful for creating a more compact storage network.

**Comment by Lothrazar** [comment]
1.12 or 1.16?

**Comment by Lothrazar** [comment]
out of scope for mod, planning to keep it simple.

this would add lag and complexity that we dont need :)
