### ISSUE TITLE
Link Cables Incapable of connecting with Bibliocraft Bookcases

### ISSUE THREAD

**Issue by Char022** [PrinceOfAmber/Storage-Network#313]
Minecraft version & Mod Version:
Minecraft 1.12.2
BiblioCraft[v2.4.5] 
SimpleStorageNetwork-1.7.11
Single player or Server:
I encounter the same problem on both single player and server.
Describe problem (what you were doing / what happened):
The storage link cables (or any of the other cables) do not connect to the Bibliocraft Bookcases. I have surrounded the bookcases entirely with the cables and tried all of the configurations of the bookcase. I have tried hoppers, and hoppers are able to work with the bookcases (Both vanilla hoppers as well as the wooden hoppers from Tinker's Construct, so it isn't mods in general)

![image](https://user-images.githubusercontent.com/41021864/95343466-91d18780-0886-11eb-9fe2-b0b2b1d072a7.png)

**Comment by Lothrazar** [comment]
that is fully in control of the other mod. bibliocraft can add the inventory capability and it would trigger a connection. or someone could make a third party addon mod to add it to bibliocraft tile entities. but bibliocraft is setting it up differently right now
