### ISSUE TITLE
Export cables with Operation Upgrades causing a lot of TPS lag (1.12.2)

### ISSUE THREAD

**Issue by fzzyhmstrs** [PrinceOfAmber/Storage-Network#315]
Minecraft 1.12.2, SSN 1.7.10

Single Player, with the MC Eternal modpack

I have a setup where 8 or so export cables feed into a blob of factorizers from Thermal Expansion, via some chests and pipes etc. The factorizer outputs then feed into import cables. The export cable have operation upgrades to leave certain amounts of the filtered item in the network (exporting when [item] > 64). This setup, when connected, drops my TPS from a solid 20 to about 10-13. Unlinking this setup specifically from the network fixes all TPS lag. TPS lag confirmed to be the Storage Master block with laggoggles, much worse than the next worse us/t reading, when the setup is connected to the network..

I'm not familiar with the code of the mod, but my suspicion is that the operation upgrade + export cable is polling the network for a quantity of [item], possibly every tick. Going through the items in the network every tick, possibly twice with the upgrade, seems excessive since the network only seems to transfer once a second or so.

Attached screenshots described below. It is noted that laggoggles readings can flucuate quite a lot based on exact things that are happening during profiling.

- the setup without any other info. Export cables feed into a chest, which feeds into a pile of factorizers. The factorizers feed into import cables.
![setup-blank-screen](https://user-images.githubusercontent.com/72876796/96025359-00808900-0e23-11eb-8146-8d0bf91f6578.png)

- the laggoggles report with the setup disconnected from the overall network. Note that I think laggoggles is multiplying the results by 100 for some reason. at about 10-13 TPS I'm averaging something like 85,000 us/t total.
![laggoggles-setup-disconnected](https://user-images.githubusercontent.com/72876796/96025470-2a39b000-0e23-11eb-96e9-0e9d07e068f2.png)

- the laggoggles report after connecting the network back up to the setup
![laggoggles-setup-connected](https://user-images.githubusercontent.com/72876796/96025494-31f95480-0e23-11eb-9e62-81eee4202f44.png)

- the laggoggles report with the export cables connected (the cables are mostly isolated top to bottom by the factorizers
![laggoggles-export-only](https://user-images.githubusercontent.com/72876796/96025519-39b8f900-0e23-11eb-8683-c62cba87656f.png)

- the laggoggles report with the import cables connected
![laggoggles-import-only](https://user-images.githubusercontent.com/72876796/96025530-40477080-0e23-11eb-89a0-ca46f5a9d07c.png)

- TPS shown via forge with the setup disconnected
![TPS-setup-disconnected](https://user-images.githubusercontent.com/72876796/96025541-45a4bb00-0e23-11eb-9c80-4bf84262404d.png)

- TPS shown with the setup connected
![TPS-setup-connected](https://user-images.githubusercontent.com/72876796/96025559-4a696f00-0e23-11eb-81b1-da07f3df5542.png)

- the GUI screen showing the setup typical to each of the export cables in this bundle.
![export-cable-setup](https://user-images.githubusercontent.com/72876796/96025584-50f7e680-0e23-11eb-99d4-33854737d8cc.png)

No crashes, just very stuttery mob motion and strange entity behavior due to TPS lag from the above issue.

**Comment by Lothrazar** [comment]
yep as said in other issues, lag goggles isnt very accurate. it often has noticed that the cables are often waiting for the inventories to respond.  1.12 is pretty much feature complete right now, no plans to rewrite everything.   


In future if you get a real java VM snapshot like an .NPS file sampling lag from any source including https://www.curseforge.com/minecraft/mc-mods/sampler , open a new issue i can make small changes
