### ISSUE TITLE
1.16.1 | Version 1.0.0 | Entities stop rendering when storage system is opened 

### ISSUE THREAD

**Issue by vertex235** [PrinceOfAmber/Storage-Network#317]
Minecraft version & Mod Version: 1.16.1 / SimpleStorageNetwork-1.16.1-1.0.0

Single player or Server:
Singleplayer

Describe problem (what you were doing / what happened):
Whenever I open the storage network, all entities (including tile entities) stop rendering. The only known solution I have found is to completely restart minecraft. I have tried reloading textures, reloading chunks, and restarting the world, but none of those fix it. This problem also happens without any extra mods. A bunch of people in the curseforge comments also have the same problem, so it's not just a fluke.

**Comment by Lothrazar** [comment]
Have you tried this in version 1.16 - 1.1.2 ? There were some forge updates that really helped out, and some voxel shape changes

**Comment by zach-v** [comment]
Hi, I know this is a bit after this version. But I am still getting this issue as described. Here's my stack trace:
https://pastebin.com/6FbrdryB

System info:
https://pastebin.com/A3vp6kJT

Just opening the UI for either storage container (crafting and non-crafting) causes this issue. The only compiled versions linked through curse is 1.0.0 for minecraft version 1.16.1. For our current mod pack we need to use this version of minecraft and 1.16.2 is not compatible with prior versions. What can I do to fix this issue?

**Comment by Lothrazar** [comment]
Latest 1.16 versions on curse have this fixed
