### ISSUE TITLE
simplestoragenetwork Not compatible with Overloaded 1.16.3-1.16.4 

### ISSUE THREAD

**Issue by IchigoGames** [PrinceOfAmber/Storage-Network#321]
Minecraft 1.1.6.3 and 1.16.4
SimpleStorageNetwork-1.16.3-1.2.0 also tested SimpleStorageNetwork-1.16.3-1.3.0 
Overloaded-1.16.3-0.0.90
jei-1.16.4-7.6.0.58 tested both jei-1.16.3-7.6.0.51
without jei SimpleStorageNetwork will crash when you open interface. 

Single player or Server:both

this is a issue with overloaded and simplestoragenetworks a compatible issue with the two mods that messed up the text rendering on the storage interface this happens in 1.16.3 and in 1.16.4

video https://www.youtube.com/watch?v=4DqTqrp1cFk&ab_channel=IchigoGames 
log https://www.dropbox.com/s/b4fzyxcur616v6b/debug.log?dl=0

**Comment by IchigoGames** [comment]
ingore the gen i had in my hand i was thinking i needed to power it

**Comment by P3rf3ctXZer0** [comment]
I am a bit lost can see your latest.log as the issue occured? Also it may be a localization bug (though this is my first time seeing anything like this)

**Comment by IchigoGames** [comment]
sure one sec

**Comment by IchigoGames** [comment]
https://www.dropbox.com/s/cux1zuwvwp9o1ue/latest.log?dl=0

**Comment by IchigoGames** [comment]
ill test it by it self in a sec and let you know it it still happens

**Comment by IchigoGames** [comment]
https://pastebin.com/wW81Q4ry well thats odd by it self with no other mods it just crashed

**Comment by IchigoGames** [comment]
oh ok it was due to jei not being in with jei it will crash but that has nothing to do with this issue

**Comment by IchigoGames** [comment]
![image](https://user-images.githubusercontent.com/11888162/99761289-56e48580-2abb-11eb-8a80-9e27cb693aff.png)
it looks like with only this mod and jei it works fine

**Comment by Lothrazar** [comment]
Yeah looks like compatibility. by itself mod is fine, and text looks like not from this mod. thanks

**Comment by P3rf3ctXZer0** [comment]
Do you have quark? It may actually be a cause if I remember correctly

**Comment by IchigoGames** [comment]
yes i do ill test that in a min

**Comment by IchigoGames** [comment]
Tested it without  quark and its still happening so its not that later today ill remove a few mods at a time till i find it

**Comment by P3rf3ctXZer0** [comment]
Start with anything that modifies core files. So anything that has a library mod.

**Comment by Lothrazar** [comment]
For reference, the only text i have should be the tooltips on the buttons, or tooltips when you hover on the text bar.  no just raw text always written

**Comment by IchigoGames** [comment]
Overloaded i know the dev i talk to him all the time so ill let him know as well

**Comment by IchigoGames** [comment]
mods added jei-1.16.4-7.6.0.58 Overloaded-1.16.3-0.0.90 SimpleStorageNetwork-1.16.3-1.2.1 forge 35.1.0 also happens on older or newer forge only added jei due to simplestoragenetworks crashing without it ![image](https://user-images.githubusercontent.com/11888162/99890594-8ebc0c00-2c26-11eb-9429-e29d969522e2.png)

**Comment by IchigoGames** [comment]
without overloaded addded
![image](https://user-images.githubusercontent.com/11888162/99890617-e0649680-2c26-11eb-8922-eac0be923202.png)
to sum this up this is a mod compatibility issues with this mod + overloaded

**Comment by IchigoGames** [comment]
[latest.log](https://github.com/Lothrazar/Storage-Network/files/5578715/latest.log)

**Comment by IchigoGames** [comment]
can some one check this

**Comment by IchigoGames** [comment]
anyone there ?

**Comment by IchigoGames** [comment]
so is this not getting fixed iv talked to cj overloaded dev i know him he says this is a issue on your side

**Comment by P3rf3ctXZer0** [comment]
You need to be able to recreate it with just the devs mod or the offending mods. Otherwise, your barking up the wrong.

**Comment by IchigoGames** [comment]
What are saying you don't fix mod compatibility issues ? thats what this is this + overloaded = issue

**Comment by IchigoGames** [comment]
btw this is even a issue on forgecraft and any modpack with this mod and overloaded in it

**Comment by IchigoGames** [comment]
sorry if you i just noticed i called this mod simple storage was that your issue i meant SimpleStorageNetwork

**Comment by IchigoGames** [comment]
so add this mod + overloaded and jei without jei simple SimpleStorageNetwork will crash when you open storage interface then place that block down open storage interface and you will see the issue.

**Comment by P3rf3ctXZer0** [comment]
The author needs exact versions and video confirmation ... mod authors don't typically just test and issue. I recommend OBS.

**Comment by P3rf3ctXZer0** [comment]
latest.log always helps too ... since the bug is obscure you will need a great deal more detail.

**Comment by IchigoGames** [comment]
iv all ready given exact versions numbers for all the mods used but ok ill make a video

**Comment by IchigoGames** [comment]
https://www.youtube.com/watch?v=4DqTqrp1cFk&ab_channel=IchigoGames the video you requested and the log https://www.dropbox.com/s/jdv8socnxhygmf6/latest.log?dl=0 iv edited the info above to show version numbers for mods used in test can also be seen in video.

**Comment by IchigoGames** [comment]
https://github.com/CJ-MC-Mods/Overloaded/issues/103 just in case its a issue on overloaded side iv reported the same info to them

**Comment by IchigoGames** [comment]
i think with all you got to go on now if thats not a a great deal more detail not sure what is.

**Comment by IchigoGames** [comment]
@P3rf3ctXZer0 anything im missing ?

**Comment by IchigoGames** [comment]
would it be better if close then and open as new issue as its no longer true that this cannot be replicated

**Comment by IchigoGames** [comment]
reuploaded as https://github.com/Lothrazar/Storage-Network/issues/323 to make it easier to-read understand

**Comment by TheUnknownAccount** [comment]
![bug](https://user-images.githubusercontent.com/76206264/106396005-575e9e00-63d3-11eb-816f-1d9d1b416101.png)

**Comment by Lothrazar** [comment]
Fix coming soon 1.3.2

**Comment by cjm721** [comment]
Update from Overloaded side. Figured out what I was doing to cause this. In my localization file during the conversion to json format I created an entry with "" as the key. That is what was showing.
