### ISSUE TITLE
simplestoragenetwork compatible issue with Overloaded Mod 1.16.3-1.16.4

### ISSUE THREAD

**Issue by IchigoGames** [PrinceOfAmber/Storage-Network#323]
Minecraft version 1.16.3 and 1.1.6.4
Forge 35.1.0 when tested in 1.16.4
Forge 34.1.42 when tested in 1.16.3
jei-1.16.4-7.6.0.58 only added jei due to SimpleStorageNetwork crashing without it.
Overloaded-1.16.3-0.0.90 
SimpleStorageNetwork-1.16.3-1.2.1 also tested SimpleStorageNetwork-1.16.3-1.3.0 with the same results

Single player or Server: both

this is a issue with overloaded and simplestoragenetworks a compatible issue that messed up the text rendering on the storage interface this happens in 1.16.3 and 1.16.4

this is what it looks like with just simplestoragenetworks and jei 
![image](https://user-images.githubusercontent.com/11888162/101295409-2141db00-37e3-11eb-898a-97794081d7aa.png)

and this is what it looks like after overloaded is added
![image](https://user-images.githubusercontent.com/11888162/101295415-2dc63380-37e3-11eb-84d8-9846b53c4ead.png)

video https://www.youtube.com/watch?v=4DqTqrp1cFk&ab_channel=IchigoGames

new log https://www.dropbox.com/s/7e7dzhgcwrrwv44/latest.log?dl=0
https://www.dropbox.com/s/b4fzyxcur616v6b/debug.log?dl=0

edit..i uploaded this as a new issue so i could get all the into in one place and make it easier to read-understand

**Comment by IchigoGames** [comment]
just now noticed that log is from after overloaded was remove i will get you one for when i had overloaded and simplestoragenetowrks

**Comment by IchigoGames** [comment]
so you could of fixed this is update but didn't......

**Comment by IchigoGames** [comment]
@Lothrazar

**Comment by Lothrazar** [comment]
you deleted your logs.

Can you post them somewhere thats not dropbox, all i get is "This item was deleted"

**Comment by Lothrazar** [comment]
For example pastebin.com/

**Comment by Lothrazar** [comment]
Just tested this locally.

Doesnt happen with ANY other mod.  Refined storage, AE2, barrels, quark, mystical agriculture, no other mod causes this to happen except for overloaded

**Comment by IchigoGames** [comment]
oh sorry i forgot was the logs was too so i removed a week or so ago

**Comment by IchigoGames** [comment]
but yes in my test only mods used with overloaded simple storage and jei  btw if you use your mod with jei it will crash when you go to open interface

**Comment by IchigoGames** [comment]
well do that test again and send you logs but if you did it it should be the same logs you have

**Comment by IchigoGames** [comment]
Minecraft 1.16.4
Forge 35.1.36 happens on any version that works.
jei-1.16.4-7.6.1.65
Overloaded-1.16.3-0.0.90
SimpleStorageNetwork-1.16.3-1.3.0
logs https://www.dropbox.com/s/uq9iiv62q4zrlrz/latest.log?dl=0
