### ISSUE TITLE
Lag Machine with Storage Drawers

### ISSUE THREAD

**Issue by Divineaspect** [PrinceOfAmber/Storage-Network#324]
Minecraft version & Mod Version:
1.16.4 & 1.16.3 - 1.3.0

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Connecting these two systems produces huge amounts of lag.
Still need to test interfacing through Network Exchange Interface, but it doesn't seem to have a logical connection.

I'm also opening this issue to help others who might manage to successfully search for it.

**Comment by Lothrazar** [comment]
Sounds like storage drawers is still pretty laggy. (i say this, since the lag doesnt exists with chests and other storage mods)


EDIT: related maybe to https://github.com/jaquadro/StorageDrawers/issues/909

**Comment by Lothrazar** [comment]
Got any log files to show evidence of this? or a snapshot? visualvm.github.io/

**Comment by Lothrazar** [comment]
So i set up a network using the drawers like you said .  more in next comment
![2021-01-08_13 07 16](https://user-images.githubusercontent.com/621529/104064262-78f0af00-51b2-11eb-9316-cf705bac5b0b.png)

**Comment by Lothrazar** [comment]
Seems pretty fast to me. adding and removing it takes a split second, no slower than chests 

![so fast](https://user-images.githubusercontent.com/621529/104064612-13e98900-51b3-11eb-843c-52e268eb3b7b.gif)

**Comment by Divineaspect** [comment]
use a storage controller, interact through that with at least 65 drawers

**Comment by Lothrazar** [comment]
network is working as intended. controller is up to controller author
