### ISSUE TITLE
Crash after deleting jei

### ISSUE THREAD

**Issue by OffsetMonkey538** [PrinceOfAmber/Storage-Network#325]
Minecraft version & Mod Version:
1.16.4 & 1.16.3 - 1.3.0

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
So I deleted jei cuz I wanted to use a different mod(can't remember what it was called) and after that when I wanted to open the request table(or whatever it's called) it crashed.

Crash log (if any):
[crash-2020-12-17_15.57.47-client.txt](https://github.com/Lothrazar/Storage-Network/files/5709934/crash-2020-12-17_15.57.47-client.txt)

**Comment by Lothrazar** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/3163007
