### ISSUE TITLE
Export cable on huge network causing massive TPS lag

### ISSUE THREAD

**Issue by magiruuvelvet** [PrinceOfAmber/Storage-Network#327]
**Minecraft version & Mod Version:**

Minecraft 1.16.4-forge 35.1.13
Simple Storage Network: 1.16.3-1.2.1

**Single player or Server:** Singleplayer

**Describe problem (what you were doing / what happened):**

Adding export cables on a huge storage network with 104 link cables and only vanilla double chests causes massive TPS lags (most noticeable using the DoubleDoors mod and massive block lag during mining). As soon as I remove the export cables from the network the TPS is instantly normal again.

I tested with just 1 export cable and it already starts to lag. As I add more export cables to the network the more unresponsive the integrated server gets to a point the game is unplayable. The chests are spread into multiple chunks in case that matters. An interesting thing I also noticed is when I configure the export cable with items it should export it gets even more laggy.

As of now I have disabled all automation because of the lag caused by export cables :(

Import cables for some reason don't seem to cause TPS problems, at least no noticeable ones.

![スクリーンショット_20201228_191130](https://user-images.githubusercontent.com/13280758/103234707-99ae3e80-4940-11eb-9736-da2fff6da6db.png)

EDIT: I found a similar issue #289 describing how export cables are causing problems.

**Comment by Lothrazar** [comment]
Are all the connections on Vanilla chests, or do you have a mix of random 3rd party storage mods?  Some mods can be really slow when inserting into them.

EDIT: just noticed you answered this in the post already
