### ISSUE TITLE
Storage System over several Chunks

### ISSUE THREAD

**Issue by Patrick1417** [PrinceOfAmber/Storage-Network#328]
Minecraft version & Mod Version:
Forge 1.16.4 (35.1.0) Mod Version 1.16.3-1.2.1

Single player or Server:
Server

Describe problem (what you were doing / what happened):

I have built the Storage system in my building and just started do make a new basement around 400 Blocks away. 

But when i connect this new basement with exportcables to the old network it won't work. 
I figured out that i works when somebody is near to the old network. 

Is there a way to fix this problem? Thank you

**Comment by Nenwar** [comment]
sounds to me like your old network ended up in unloaded chunks, try putting a chunk loader in the chunks that the storage network takes up, im not sure if the cables need to be chunk loaded, but the rest of the system sure does need to be

**Comment by Lothrazar** [comment]
Yes, try adding a chunk loader mod.  By design this mod does not load any chunks
