### ISSUE TITLE
crash whilst linking AE2 system and storage network

### ISSUE THREAD

**Issue by Nenwar** [PrinceOfAmber/Storage-Network#329]
Minecraft version & Mod Version:
Minecraft: 1.16.4
Forge: 35.1.13
Simple Storage Network: 1.16.3-1.3.0
Applied Energistics: 8.1.0

Single player or Server:
   Singleplayer

Describe problem (what you were doing / what happened):
   I was attaching an existing applied energistics 2 storage bus connected to my ME system to a network exchange interface from this mod, and suddenly my Minecraft closes

Crash log (if any):

[crash-2020-12-30_06.29.25-server.txt](https://github.com/Lothrazar/Storage-Network/files/5754244/crash-2020-12-30_06.29.25-server.txt)
-

edit- im a dum dum and put the crash report in wrong

**Comment by Nenwar** [comment]
OK so i decided to do a little more testing after the fact, turns out, its not entirely the interaction between SSN and AE2, this crash report appeared after I attached the exchange block to the system with a link cable, i hope this helps with a bit of bug testing or something, perhaps I wasted my time doing this, who knows, maybe it will help

[crash-2020-12-31_20.05.39-server.txt](https://github.com/Lothrazar/Storage-Network/files/5758565/crash-2020-12-31_20.05.39-server.txt)

(Minecraft: 1.16.4
Forge: 35.1.13
Simple Storage Network: 1.16.3-1.3.0)
[crash-2020-12-31_20.34.18-server.txt](https://github.com/Lothrazar/Storage-Network/files/5758584/crash-2020-12-31_20.34.18-server.txt)


this crash report appeared after i did the same thing, but in a fresh Minecraft instance with a fresh install of JEI and simple storage network being the only two mods added

Minecraft 1.16.4
forge 36.1.13
simple storage network 1.16.3 - 1.3.0
JEI 1.16.4-7.6.0.49

[crash-2020-12-31_20.20.46-server.txt](https://github.com/Lothrazar/Storage-Network/files/5758576/crash-2020-12-31_20.20.46-server.txt)


this next crash report occurred after i updated forge to the latest version

Minecraft 1.16.4
forge 36.1.28
simple storage network 1.16.3 - 1.3.0
JEI 1.16.4-7.6.0.49

[crash-2021-01-01_02.26.11-server.txt](https://github.com/Lothrazar/Storage-Network/files/5758578/crash-2021-01-01_02.26.11-server.txt)


and finally, this crash report happened when i  updated JEI to the latest version available, not that i thought it would actually do anything, but i might as well try it, hopefully it helps or something

Minecraft 1.16.4
forge 36.1.28
simple storage network 1.16.3 - 1.3.0
JEI 1.16.4-7.6.0.62


im truthfully not sure those further tests actually say anything different, i didnt read them very closely, but idk, thought i would try it a few times with slightly different environments

**Comment by Lothrazar** [comment]
I will at least add a patch keep the errors safe and handled within the lines mentioned in the log

`	at com.lothrazar.storagenetwork.block.main.TileMain.getConnectablePositions(TileMain.java:516) ~[storagenetwork:1.16.3-1.3.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.TileMain.getStacks(TileMain.java:54)`
	
	
	Blocked by https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4919 for any further in depth testing

**Comment by Lothrazar** [comment]
Partial fix added ,but not complete yet still in progress   https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/3163007
