### ISSUE TITLE
How to lower the Crafting Remote Range

### ISSUE THREAD

**Issue by zachsai** [PrinceOfAmber/Storage-Network#333]
Minecraft version & Mod Version:
1.16.4, 1.3.1
Forge: 35.1.28
Single player or Server: Server

Describe problem (what you were doing / what happened):
How can I change the range of the Crafting Remote from Simple Storage Network?
I can access my inventory at over 2000 blocks, which is pretty broken imo

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by haate** [comment]
As a point of note on this: If your network root is nearby your world spawn, the remote will work from anywhere. This is happening because the area near world spawn is always loaded, unlike the rest of the standard chunks. It will also happen if the root is in a chunk that is permanently loaded via commands or other mods (i.e. the weirding device).

Try moving your network root a bit further out from spawn, if possible.

**Comment by Mollyarty** [comment]
I used the setworldspawn command to increase the range of the remote. I don't want the range to be kilometers, but I couldn't even use the remote 100m away, with the range SO small the remote is pretty useless. At the very least, let us still use it as a crafting table out of range. I made an account just to post this comment. The remote is the thing is was looking forward to with this mod and it took me FOREVER to get the sea lanterns, only to find out that range of the remote is so short it basically always makes more sense to just walk back to your base. PLEASE don't force us to use the tiny, tiny, TINY default range

**Comment by OmenLW** [comment]
> PLEASE don't force us to use the tiny, tiny, TINY default range

To fix this I use ChunkNoGoByeBye which lets you place a block and that block forces the containing chunk to stay loaded all the time. I can then go any distance from the network and the remote works fine.

**Comment by Lothrazar** [comment]
currently range is unlimited, im going to keep that default but add a range CONFG to affect the two main GUI remotes


	# Maximum range of the Storage Remote and Crafting Remote.   -1 means unlimited.
	#Range: -1 ~ 8388607
	remoteMaxRange = -1
	#

**Comment by Tander** [comment]
I set this value to 2000 and getting about 50 blocks radius... What exactly this number means?
```
# Maximum range of the Storage Remote and Crafting Remote.   -1 means unlimited.
#Range: -1 ~ 8388607
remoteMaxRange = 2000```
