### ISSUE TITLE
Storage Request Table dupe glitch

### ISSUE THREAD

**Issue by xaracen-xen** [PrinceOfAmber/Storage-Network#334]
Minecraft Version: 1.16.4
Mod Version: SimpleStorageNetwork-1.16.4-1.3.1
No other mods.
Single Player

Placing a lone Storage Request Table, inputting a crafting recipe, shift click the output, you get the item, and you still have the ability to remove one more resulting item, giving you one extra item.

**Comment by Lothrazar** [comment]
i couldnt find a good fix that didnt break stuff so i put it off.

Realized i can just make the GUI of the table not open if theres no network main attached at all
