### ISSUE TITLE
[1.16.5] missing items, moving root gives alternating results

### ISSUE THREAD

**Issue by Knito58** [PrinceOfAmber/Storage-Network#337]
Minecraft version & Mod Version:

MC 1.16.5
Forge 36.0.1
Simple Storage Network 1.16.4-1.3.1 (latest)

Single player or Server: single

Describe problem (what you were doing / what happened):

I'm missing part of my items in the network. I ended up trying to move the network root around a bit because I thought "Just re-initialize everything by placing it freshly". Amazingly, the results differ according to which
place I put the root. All placements did happen **in the same chunk** according to F3+g and were only a few blocks away from the original placement. All cables are triple checked. That is not the problem. There are also chunkloaders in place. Nothing can explain why moving around the root in the same chunk block by block will always return different results.

Results were:

- nothing at all
- this but not that
- that but not this

A spot where I could place the root and get everything was never found. Last thing I did before this happened:
I updated Java to current version and updated my M$ Win 10 workstation with latest M$ happyness.

Crash log (if any): nope

**Comment by Knito58** [comment]
I started a new world and used only small containers this time. I believe it was a "big number problem". I only used t3 containers from router reborn mod when killing the Storage Network. These containers are infinite (or max int). And several of them holded incredible amounts of items but still were at 0% full.

Too many items. Now in the new world I settled with t1 containers and some barrels from metal barrels mod.
No problem so far.
Probably the error was due to my greeding.

**Comment by Lothrazar** [comment]
yeah, moving the root main node should, as they say, drop all connections to cables / endpoints and restart them when you place a new one, as long as chunks are all loaded and things are moving.   depends if anythings is lagged or hanging up. or not.

I will look up router reborn ? havent seen that mod. and i can test with deep storage drawers and overloaded

**Comment by Knito58** [comment]
I use router reborn item conduits and the t1-3 containers. The conduits are very good for basic charcoal farms. The T1-3-containers come with an item image and count display - no frame needed.
In my opinion the starting setting for the item conduits filter of the router reborn mod is better than in any other mod: It is set to empty whitelist. Which will neither start sucking or pushing anything when placed freshly. Any other mod with filter settings prefers empty blacklist which will immediatly work when a newbie without any background places it.

I'm sure with the t3 containers and a charcoal farm filling some of them you will be able to reproduce the error. I was aware of the error when suddenly some charcoal-powered devices failed. The t3 was very well stuffed with charcoal, but simple storage showed: "U not have any charcoal. Duh."

When I finally found a place for the root where I could see charcoal again, my infinite glass, stone, stonebricks and sticks were gone.

Chunkloaders? Yes. They seem to help increase the problem as they assure that the production setups will always work and will help increasing big numbers.
