### ISSUE TITLE
Weird Text bug with Russian Language

### ISSUE THREAD

**Issue by forebordingsky** [PrinceOfAmber/Storage-Network#338]
Minecraft version & Mod Version: 
MC: 1.16.4 Mod:  1.3.1

Single player or Server: 
Single player

Describe problem (what you were doing / what happened):
Opening Crafting Remote with Russian language cause weird UI bug . Changing Language to English solves the problem.
Screenshot:
![simplestoragenetworkbug](https://user-images.githubusercontent.com/34266698/105766003-a2f7ee80-5f72-11eb-9988-f9df6da9fa16.png)

**Comment by Lothrazar** [comment]
possibly related https://github.com/Lothrazar/Storage-Network/issues/321
