### ISSUE TITLE
Crash with storage drawers

### ISSUE THREAD

**Issue by benbenlaw** [PrinceOfAmber/Storage-Network#339]
Minecraft version & Mod Version:
1.16.5 (MC)
1.3.1 (SS)

Single player or Server:
Server

Describe problem (what you were doing / what happened):
after a server restart world unplayable 

Crash log (if any):

[crash-2021-01-29_20.13.22-server.txt](https://github.com/Lothrazar/Storage-Network/files/5897665/crash-2021-01-29_20.13.22-server.txt)
(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by benbenlaw** [comment]
Stacktrace:
    at net.minecraft.world.World.func_217391_K(World.java:499) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]

**Comment by benbenlaw** [comment]
[crash-2021-01-30_09.23.56-server.txt](https://github.com/Lothrazar/Storage-Network/files/5897674/crash-2021-01-30_09.23.56-server.txt)
seems to happen when a network route is placed with storage drawers connected with link cables

**Comment by Lothrazar** [comment]
error from com.jaquadro.minecraft.storagedrawers.capabilities.DrawerItemRepository.stackResult( 
Similar to other open AE2 issue.  adding handlers
![Uploading 2021-02-03_05.28.15.png…]()

**Comment by Lothrazar** [comment]
Fix coming soon 1.3.2
