### ISSUE TITLE
Export Bus ignoring Blacklist/Whitelist mode

### ISSUE THREAD

**Issue by ThexXTURBOXx** [PrinceOfAmber/Storage-Network#34]
The Export Bus ignores, if it is set on Blacklist or Whitelist. The button in the GUI changes, when you click on it properly, but it still is on Whitelist.

**Comment by PrinceOfAmber** [comment]
K ill check on this thanks!

**Comment by ThexXTURBOXx** [comment]
THank you ^^

**Comment by PrinceOfAmber** [comment]
Almost got a fix ready.

Also im going to add some checkboxes to the filter GUI, it doesnt always seem to work the way a player wants to with ore dictionary matching , or metadata matching.  Damaged armor for example.  So ill let the player toggle some things

**Comment by ThexXTURBOXx** [comment]
Sounds very good, thank you ^^
