### ISSUE TITLE
MacOS cannot start up

### ISSUE THREAD

**Issue by Swedz** [PrinceOfAmber/Storage-Network#340]
**Minecraft version & Mod Version:**
MC 1.16.5 and mod version 1.16.4-1.3.1

**Single player or Server:**
Neither, just initializing.

**Describe problem (what you were doing / what happened):**
The mod failed to initialize on game startup.

**Crash log (if any):**
[crash-2021-02-04_01.37.22-fml.txt](https://github.com/Lothrazar/Storage-Network/files/5923748/crash-2021-02-04_01.37.22-fml.txt)

**Comment by Lothrazar** [comment]
I found the root in your log file 

`{re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}`

Looks like immersiveengineering issue for some reason. along with registry.ConfigRegistry. could not write a config file.  

also try delete storagenetwork.toml and restart
