### ISSUE TITLE
Crash when attempting to use building remote (NoClassDefFoundError)

### ISSUE THREAD

**Issue by LemmaEOF** [PrinceOfAmber/Storage-Network#342]
Minecraft version & Mod Version:
MC 1.16.5, Forge 36.0.22, SSN 1.16.5-1.3.2

Single player or Server:
SP

Describe problem (what you were doing / what happened):
When you attempt to use the building remote (potentially only when Cyclic is not installed), the game will crash with a NoClassDefFoundError on `com.lothrazar.cyclic.item.builder.BuilderActionType`.

Crash log (if any):
https://gist.github.com/Boundarybreaker/4febc89063f5fa6f15555d8e423f014c

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Dhalahk** [comment]
I have the exact same issue it seems, Also I don't have Cyclic. https://paste.ee/p/9xeMX
I tested with only Simple Storage Network installed and the crash still happens.

The second I click the ground with the Builder remote my server crashes and in singleplayer my game crashes. (My log is from singleplayer)
