### ISSUE TITLE
Server crash with cables being connected

### ISSUE THREAD

**Issue by Swedz** [PrinceOfAmber/Storage-Network#344]
Minecraft version & Mod Version: MC 1.16.5, Storage Network 1.3.2

Single player or Server: Server

Describe problem (what you were doing / what happened): My friend placed a link cable into his storage network and the server froze and crashed. Every time the area is loaded it does the same thing. Full on server crash.

Crash log (if any): https://pastebin.com/NuxHH1me

**Comment by Lothrazar** [comment]
Interesting log... error is when its trying to copy the item stack... seems like a memory overload or StackOverflowError ? I can stop int from crashing at least  so it will instead just reject the insert of the stack
