### ISSUE TITLE
Game crashing bug

### ISSUE THREAD

**Issue by 1persON768** [PrinceOfAmber/Storage-Network#35]
When I have Advanced Storage Remote for example at hotbar slot 3 and I open it and try to allocate item to the hotbar slot 3 with number key, it crashes my game.

[crash-2017-10-21_04.32.37-client.txt](https://github.com/PrinceOfAmber/Storage-Network/files/1403700/crash-2017-10-21_04.32.37-client.txt)

**Comment by PrinceOfAmber** [comment]
Looking into a fix now, thanks for being patient
