### ISSUE TITLE
Suggestion: Storage Import Cable can extract items from Player Chest of Extra Utilities 2.

### ISSUE THREAD

**Issue by Phoupraw** [PrinceOfAmber/Storage-Network#350]
I hope Storage Import Cable can extract items from Player Chest of Extra Utilities 2.

**Comment by Lothrazar** [comment]
This is in the config file.  Its blocked by default since it lets you import items from other players.  But you can turn it on.  Just change 

    S:BlacklistBlocks <
        extrautils2:playerchest
     >
     
     to
     
     
         S:BlacklistBlocks <
     >
     
     
     
     in config/storagenetwork.cfg
