### ISSUE TITLE
import cable not working

### ISSUE THREAD

**Issue by Fazzbear21** [PrinceOfAmber/Storage-Network#351]
Minecraft version & Mod Version:
1.12.2

Single player or Server:
single player

Describe problem (what you were doing / what happened):
So i set up the main system and everything works but when i tried to use the import cables nothing works. i switch between white list and black list, tried adding speed upgrades and nothing works

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
Yep, by default the setting has the "Allow-list" showing and the filter is empty so its importing nothing

Switching to "ignore list" will let it import everything in the target chest 

Of course it also only will import if there is room in the network.  If my whole network is three import cable sbut no storage cables, theres no places to put the goods

A setup like this is working in the latest mod version 1.8.2+ . come check out discord if you have other problems/suggestions https://discord.com/invite/uWZ3jf56fV 

![2022-02-20_08 46 54](https://user-images.githubusercontent.com/621529/154853966-0da0b41e-44fe-4a95-8599-0b430cb03398.png)
![2022-02-20_08 46 48](https://user-images.githubusercontent.com/621529/154853968-32676cc1-4334-444c-8ac4-572b8070ce65.png)
