### ISSUE TITLE
[Suggestion] Forge Multipart support

### ISSUE THREAD

**Issue by Monniasza** [PrinceOfAmber/Storage-Network#352]
I'd like to have multipart support because exposed cables in buildings are ugly.
I'd also like an EnderIO conduit for the network, besides multipart, for modularity

Images:
![2021-03-07_11 50 05](https://user-images.githubusercontent.com/37037712/110237319-ba47d580-7f3b-11eb-9b7e-b10017c2305a.png)
![2021-03-07_11 50 11](https://user-images.githubusercontent.com/37037712/110237320-bb790280-7f3b-11eb-95a4-94920ea1e56d.png)
![2021-03-07_11 51 06](https://user-images.githubusercontent.com/37037712/110237321-bb790280-7f3b-11eb-80ea-514666c70f46.png)

**Comment by Lothrazar** [comment]
Forge has never had an official multi-part api.  There was an addon in 1.11/1.12 for a hot minute maybe? that mus be what enderIO used..  

If Forge 1.16+ makes one or a new supported API comes out its worth looking into then i guess

**Comment by Monniasza** [comment]
There's a [CBMutlipart](https://www.curseforge.com/minecraft/mc-mods/forge-multipart-cbe), but it wasn't updated for 1.5 years.
You can look at source code for EnderIO [here](https://github.com/CrazyPants/EnderIO)

**Comment by Lothrazar** [comment]
This doesnt help you at all and im sorry, but first i have to fix lots of bugs and then port to neoforge 1.21.x , and in that environment we can see what multi part mods exist
