### ISSUE TITLE
Import/Export Cables GUI access

### ISSUE THREAD

**Issue by EnderGrimm1** [PrinceOfAmber/Storage-Network#353]
Minecraft version & Mod Version: 1.16

Single player or Server: server

Describe problem (what you were doing / what happened): cannot open Import/Export Cables gui

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by DMCK96** [comment]
I added this mod to the ATM6: To The Skys modpack and this happened there too.

**Comment by Lothrazar** [comment]
Import cable has no GUI. filtered import and export cables do, working on bugfixes this week
