### ISSUE TITLE
1.12 bauble support

### ISSUE THREAD

**Issue by The-Person02** [PrinceOfAmber/Storage-Network#359]
minecraft 1.12.2, baubles i put an image for what slot it could be put on as(and to access it, it could be the same as 1.16, where a player just assigns what button they want)

![slot](https://user-images.githubusercontent.com/81997816/113628493-f6ea1800-9632-11eb-8c1c-904c255d658d.png)

**Comment by Lothrazar** [comment]
curios never worked cleanly with any remote with a 3x3 crafting grid, that always mixed it up and caused dupes.  i can backport baubles for at least the network Collector, so thats coming out soon. 
Unless a non-crafting remote also gets done, idk if thats gonna happen tho right now https://github.com/Lothrazar/Storage-Network/issues/367
