### ISSUE TITLE
Storage drawers in unloaded chunk not accessible

### ISSUE THREAD

**Issue by Ash70** [PrinceOfAmber/Storage-Network#36]
I suspect this is beyond your control and is simply how it works, but I'll mention it anyway. Using the advanced remote it can access normal chests without problems, but not storage drawers (controller) when the chunks are unloaded.

**Comment by PrinceOfAmber** [comment]
Yeah, storage networks have their own system, I'll take a look but it might not work out.  Best thing might be just adding a chunkloader.

**Comment by Ash70** [comment]
I guessed as much; no worries.
I did notice however that having a network with only a storage drawer controller (so no other storage types like chests) contained in just one chuck does seem to work.
But like you suggested, I am using chuck loaders now, so it works perfectly with that.
