### ISSUE TITLE
Issues when exporting items from Network.

### ISSUE THREAD

**Issue by Jerome226** [PrinceOfAmber/Storage-Network#360]
**Minecraft version & Mod Version:**
Minecraft: 1.16.5
Mod: SimpleStorageNetwork-1.16.5-1.3.5

**Single player or Server:**
It make lags in Singleplayer, dunno about server.

**Describe problem (what you were doing / what happened):**
When i dump items in my network and i have a funnel connected to a Interface, i just get a huge lag spike.

https://user-images.githubusercontent.com/55724525/114412542-322c9f80-9b7b-11eb-9980-871ff6787a28.mp4

**Crash log (if any):**

**Comment by Lothrazar** [comment]
Fixed the lag from the interface in next version. also if you only need a simple export, the export cable is more efficient
