### ISSUE TITLE
Remote is not working after going 100-200 blocks away  from the network or another dimension

### ISSUE THREAD

**Issue by CalualaMic** [PrinceOfAmber/Storage-Network#364]
Minecraft version & Mod Version:1.16.5 mod-1.3.5

Single player or Server: Single player

Describe problem (what you were doing / what happened): So the problem is exactly what the title says. Today i wanted to try this mod out and when i finished everything i conected the crafting remote. After i entered the nether i couldnt open the remote. Then i entered back in the overworld and i  opened the remote. Then i walked about 200 blocks away from the network and it didnt want to open. Is it because the chunk doesnt want to save/render or what? Please, any help is apreciated.

**Comment by tsheinen** [comment]
it's because the chunk isn't loaded; if you load the chunk somehow (spawn chunks, other mods, etc) it will work

**Comment by CalualaMic** [comment]
> it's because the chunk isn't loaded; if you load the chunk somehow (spawn chunks, other mods, etc) it will work

Yea thanks man ir really helped me. I just nedeed to move the world spawn point. Thank you very much. Have a good day!
