### ISSUE TITLE
Priorities when mixing Simple Cables and Storage Link Cables

### ISSUE THREAD

**Issue by replicaJunction** [PrinceOfAmber/Storage-Network#369]
Minecraft version & Mod Versione
MC 1.12.2
Simple Storage Network 1.12.2-1.8.1

Single player or Server: Both

When mixing Simple Cables and Storage Link Cables, what is the effective priority of the Simple Cables? Will they get the first priority, last priority, or do they have a different behavior?

**Comment by Lothrazar** [comment]
the simple cables, the ones without a GUI have the default priority, so zero 0 .
