### ISSUE TITLE
Would you please add the advanced storage remote to 1.16.5?

### ISSUE THREAD

**Issue by Mrturtle213** [PrinceOfAmber/Storage-Network#370]
Minecraft version & Mod Version:

Single player or Server:

Describe problem (what you were doing / what happened):

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
The crafting remote in 1.16 is identical to the advanced remote in 1.12

Both have unlimited range, cross dimensions, and have a crafting grid, only the name changed

Is there some feature i missed adding?
