### ISSUE TITLE
Removing items from network causes strange rendering behaviour (players turn invis, tile entities turn invis, and more)

### ISSUE THREAD

**Issue by iiiNook** [PrinceOfAmber/Storage-Network#379]
**Minecraft Version:** 1.16.5

**Forge Version:**  36.1.32

**Mod Version:** 1.3.5

**Single Player or Server:** Server

**Describe problem (what you were doing; what happened; what should have happened):** Seemingly randomly, upon removing items from the SSN, most rendered models disappear. Players turn invisible (including self, and player hand), chests disappear, tile entities disappear, mana disappears from mana pools etc, rendering the game unplayable. I'm using this mod in combination with ColossalChests, however I get nothing in the log or anything of use. I'll keep digging and update this report accordingly, but it's an extremely strange bug that me and my friends who are encountering it would like to help fix.

Video/images/gifs (direct upload or link): 
**My PoV (taken at same time)**
https://i.imgur.com/pluE4nQ.jpeg
**Broken PoV**
https://i.imgur.com/xIIPsA5.jpeg

**Comment by Lothrazar** [comment]
closed due to inactivity, cannot replicate with latest forge and mod version
