### ISSUE TITLE
Incompatibility with Advanced Tools when searching in Crafting Remote

### ISSUE THREAD

**Issue by Knito58** [PrinceOfAmber/Storage-Network#384]
Minecraft Version: 1.16.5

Forge Version: 36.2.2

Mod Version: SimpleStorageNetwork-1.16.5-1.4.0

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

com.lothrazar.storagenetwork.item.remote.GuiNetworkCraftingRemote
I gave "sl" to search for slimes in the Crafting Remote. Then the game closed. Server is still running - client was disconnected.

Log file link: https://pastebin.com/cVFGwsep

My guess is that the enchantments of advanced tools create a server hickup. A big glass of water could help but I do not know where to insert it.

**Comment by Knito58** [comment]
Modpack Konitorpack 1.16.5-1.3.0

**Comment by Lothrazar** [comment]
hmm. yeah log says the advancedtools mod is crashing the game. Something about Null Pointer in their Enchantments.  

`    at de.maxhenkel.advancedtools.items.enchantments.ItemEnchantmentBase.getEnchantment(ItemEnchantmentBase.java:69) ~[?:1.16.5-1.0.4] {re:classloading}
    at de.maxhenkel.advancedtools.items.enchantments.ItemEnchantment.func_200295_i(ItemEnchantment.java:18) ~[?:1.16.5-1.0.4] {re:classloading}`   
    
    Comes from here https://github.com/Lothrazar/Storage-Network/blob/7c8f524c04bfa6e90d68d2a01a06f9fed5de9331/src/main/java/com/lothrazar/storagenetwork/gui/NetworkWidget.java#L104 , but enchantment shouldnt be making the display name null. all itemstacks need a non null display name. i think even empty string is not valid?
    
   https://github.com/henkelmax/advanced-tools/issues
