### ISSUE TITLE
Crafting Remote and Remote not consuming right click.

### ISSUE THREAD

**Issue by mactso** [PrinceOfAmber/Storage-Network#386]
Minecraft Version: 
**1.16.5**
Forge Version: 
**36.2.0**
Mod Version: 
**SimpleStorageNetwork-1.16.5-1.4.0.jar**
Single Player or Server:
**Server**
Describe problem (what you were doing; what happened; what should have happened):
**Rightclicking on the crafting remote doesn't consume the right click in some cases:
Bows will ready, modded items in the right hand will get the right click and wait in the background until you exit the remote. 
Waystones react and open the menu while you are also in the storage remote.
Food will be consumed if hungry.**

Notably: Doors, trapdoors, repeaters get the click first and consume the right click before the remote can get it.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
hmm. Yeah with a lever it just flicks the lever and not open.

I tried adding this https://github.com/Lothrazar/Storage-Network/blob/trunk/1.16/src/main/java/com/lothrazar/storagenetwork/item/remote/ItemStorageCraftingRemote.java#L172

TO consume, but it wont even get there, Lever takes over and it doesnt call that. UNless you sneak-click , then yeah this is kindof fixing it

**Comment by mactso** [comment]
I'll test this tomorrow and update.

To my mind, the desired behavior would be that if the remote gets the right click and opens the GUI, then it will consume the right click. 
That way unintended items won't get the right click in the background while the gui is open.
It seems equally logical to either consume or not consume the right click when holding the remote and clicking a clickable item with it- right now it's inconsistent with minecraft items usually getting the click ahead of the remote.

**Comment by mactso** [comment]
Tested this over the weekend and it is indeed fixed!  love the mod.
