### ISSUE TITLE
ATM 7 Crash

### ISSUE THREAD

**Issue by SavageReality** [PrinceOfAmber/Storage-Network#388]
Minecraft Version: 1.17

Forge Version: 37.0.59

Mod Version: 0.0.11

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):

Tried to view the silicon recipe from tiny redstone on JEI while I was in simple storage and the game crashed. I tried a couple of other recipes and it's hit or miss if it crashes or not.

Log file link: https://pastebin.com/mW3iQrpN

Video/images/gifs (direct upload or link):

**Comment by Ocraftyone** [comment]
Ok, so I've been dealing with this problem too and i am here to provide a bit more detail. This seems to be an issue whenever you try to view a recipe in JEI that is not a crafting table recipe. If you try to view how to craft a furnace, you won't have an issue. If you try to view how to smelt raw iron, the game crashes. The following is the provided reason for the crash:

The game crashed whilst mouseclicked event handler
Error: java.lang.ClassCastException: class net.minecraft.world.item.crafting.SmeltingRecipe cannot be cast to class net.minecraft.world.item.crafting.CraftingRecipe (net.minecraft.world.item.crafting.SmeltingRecipe and net.minecraft.world.item.crafting.CraftingRecipe are in module minecraft@1.17.1 of loader 'TRANSFORMER' @7efa3f63)
Exit Code: -1

**Comment by SavageReality** [comment]
Lol I just resorted to opening up my inventory and searching through that.
Seems to not crash when I do that.

**Comment by Ocraftyone** [comment]
Yeah what I tried doing was using the other storage's crafting interface on my storage network through the network exchange interface and discovered another bug with potions LOL

[Link to the issue](https://github.com/Lothrazar/Storage-Network/issues/389)

**Comment by SavageReality** [comment]
Yea, I use both. I use simple to access storage when I'm outside my storage
house and toms when I'm in it. Simple shows me having twice what I actually
do so it's only a depot for me.

**Comment by Lothrazar** [comment]
sadly minecraft1.17.x has been retired, issue resolved in 1.18.2+
