### ISSUE TITLE
Excessive Console Spam with Thermal Dynamics

### ISSUE THREAD

**Issue by mallrat208** [PrinceOfAmber/Storage-Network#39]
Hey there, I've been playing on a custom pack using Storage Network and we've run into an issue with a rather excessive amount of console spam. I did some searching and found your previously closed [issue](https://github.com/PrinceOfAmber/Storage-Network/issues/23) from before when it used to crash. I did however take a poke at looking at the code and I think I see the potential problem.

https://github.com/PrinceOfAmber/Storage-Network/blob/master/src/main/java/mrriegel/storagenetwork/AbstractBlockConnectable.java#L18-L23

You are passing the Storage Network Blockstate into an unknown Block's hasTileEntity check. You should probably be getting the intended BlockState using worldIn and fromPos supplied by neighborChanged

**Comment by PrinceOfAmber** [comment]
👍 https://minecraft.curseforge.com/projects/simple-storage-network/files/2524875
