### ISSUE TITLE
Not able to craft Advanced Storage Remote?

### ISSUE THREAD

**Issue by WesBtrippin** [PrinceOfAmber/Storage-Network#392]
Minecraft Version: 
1.16.5
Forge Version: 
36.2.4
Mod Version: 
1.16.5-1.4.3
Single Player or Server:
Single
Describe problem (what you were doing; what happened; what should have happened):
unable to craft advanced storage remote crafting recipe will not populate in JEI not sure if it was something i did but it doesnt show even trying to craft it manually doesnt work 

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
These are the default recipes in 1.16. (some remotes got renamed/textures changed since 1.12.2 some new ones added)
![default recs](https://user-images.githubusercontent.com/621529/135179637-bde51f1a-8efd-4662-b324-f836590fcf80.gif)
