### ISSUE TITLE
Crash When Items Are Transmitting

### ISSUE THREAD

**Issue by TheMythcaller** [PrinceOfAmber/Storage-Network#395]
Minecraft Version: 1.17.1

Forge Version: 37.0.73

Mod Version: 1.17.1-1.5.0

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened): I was testing out the mod before adding it to my modpack for sure and whenever I connect a chest to the network it crashes the game. If I try to get back on the world it just crashes it again for the same reason. I know that it is transporting things and working correctly because right before the first crash I broke a chest I accidentally connected and items from the source chest popped out.

Log file link: https://gist.github.com/TheMythcaller/112e3c3e1f9109065a4512209ca0226e

Video/images/gifs (direct upload or link): 
![2021-10-14 (1)](https://user-images.githubusercontent.com/92497143/137389802-4a91b723-be56-4f45-80a0-2081f5ff4031.png)

**Comment by Lothrazar** [comment]
sadly minecraft1.17.x has been retired, issue resolved in 1.18.2+
