### ISSUE TITLE
[1.12.2 v1.11.1] Export Cable voids items with stock upgrade 

### ISSUE THREAD

**Issue by VallenFrostweaver** [PrinceOfAmber/Storage-Network#40]
I set a stack of stone to be in the required chest that was attached to a storage network via an export cable with a stock upgrade in it (set to 64 stone). I placed 2 stacks in the main request table interface and it put 63 in the requested chest but voided the remaining.

Additionally, dragging an item to the whitelist/blacklist area and placing the ghost there it will only stay there until I replace the item in my inventory and then the ghost disappears. I have to shift+click to get the ghost to stay.

Additional minor note: the version states 1.12.1-1.11.1 even though this is for 1.12.2.

**Comment by PrinceOfAmber** [comment]
Hey thanks for being patient I am going to start looking at this soon.

**Comment by PrinceOfAmber** [comment]
Yes the 'ghost item' issue,.  It does actually stay there the first time, just if you just close and open the GUI it is actually there , it just becomes invisible, not sure why https://github.com/PrinceOfAmber/Storage-Network/issues/26

I tried this , and i didnt see anything voiding.  I did see stone exporting somewhere else, i just happened to have a different export cable with andestte, but it was using the meta checkbox.

Ill keep testing , maybe making my network bigger.  Ill also try to record some gifs or videos of how things are working for me ,this is a great tool http://www.screentogif.com/

**Comment by PrinceOfAmber** [comment]
Here is a recording of me trying to replicate your issue.  It works for me, but is this the same thing? 

https://i.imgur.com/PkLmLZS.gifv

**Comment by VallenFrostweaver** [comment]
Lemme get you my footage. Holiday is making things challenging atm.

**Comment by PrinceOfAmber** [comment]
Cannot replicate with only storage network, or with modpacks. Closing due to this and due to inactivity.

Feel free to reopen or make a new issue if you have more information.  Latest version is 1.2.2
