### ISSUE TITLE
Remote stops working after I move away from network root.

### ISSUE THREAD

**Issue by ForgetfulGH** [PrinceOfAmber/Storage-Network#401]
Minecraft Version:  1.16.5

Forge Version: 36.2.8

Mod Version: 1.5.0

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened): Crafting remote stops working when I move ~ 100 blocks away from the network root.It doesn't stop immediately,works fine at any range for first few minutes.But after I've been in the area for several minutes,remote stops working and doesn't start again before I teleport near the network root.

Range of the remote in the config file says -1 ~ 82889,anything I have to change there?

**Comment by HalcyonSeas73** [comment]
You need to have the network chunk loaded, using some kind of chunk loading mod.

**Comment by Lothrazar** [comment]
Yep Mojang only keeps the spawn chunks always loaded and not the rest of the world, theres mods that do this https://github.com/Lothrazar/Storage-Network/issues/381
