### ISSUE TITLE
Storage Link Cables don't connect to Compact Chests

### ISSUE THREAD

**Issue by Maratons4** [PrinceOfAmber/Storage-Network#405]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2855

Mod Version: 1.8.2

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
When placing storage link cables next to compact chests (from Compact Storage) the cables don't connect to the chests.

Log file link:
[2021-12-09-2.log](https://github.com/Lothrazar/Storage-Network/files/7688190/2021-12-09-2.log)

Video/images/gifs (direct upload or link): 
![unknown](https://user-images.githubusercontent.com/81237150/145469513-0dae28f2-06e0-4aca-9c92-aa341d4baacb.png)

**Comment by Lothrazar** [comment]
Yep. this is a really old bug that (i guess) never got fixed in the original compact storage mod . in one of the Skyfactory modpacks we had to get this made to made it work https://www.curseforge.com/minecraft/mc-mods/compatchedstorage
