### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Nessuno6** [PrinceOfAmber/Storage-Network#410]
Minecraft Version: 1.16.5

Forge Version: 36.2.19

Mod Version: 1.5.0

Single Player or Server: single player

Describe problem (what you were doing; what happened; what should have happened): I opened the crafting wireless controller, idk his name

Log file link: https://pastebin.com/QEWzVaBy

**Comment by Lothrazar** [comment]
OH looks like it crashes when JEI is not installed.  https://www.curseforge.com/minecraft/mc-mods/jei
If you have this it works fine, but yeah i need to fix it, that mod should be optional not required
