### ISSUE TITLE
Master Tile not Found closes GUI 

### ISSUE THREAD

**Issue by Freakous** [PrinceOfAmber/Storage-Network#424]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2680

Mod Version: 1.7.10

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

I am creating another post regarding this bug because me and the other people in my Sky Factory 4 server are all having this issue, and upon looking up the error in the server console, the only thing I see is a closed issue where owner brushed it aside and said it was working as intended, despite it clearly not.

Anytime that tinkers construct is pouring more than two ingots, and even sometimes only two, it makes the inventory interface in the storage network completely unusable, as it kicks you out after two seconds of looking in the window. You cannot access the inventory panel of the network until the smelter stops pouring ingots, meaning that there is no way to automate ore smelting through tinkers construct.

The only error in the console says "Container closing, master tile not found", despite it being only one chunk away. The mod stated this was simply because master block wasn't loaded in a chunk, but after moving it directly next to the interface and smelter so they were all within a 4x4 radius of one another, it would still give this error.

I loved the concept of this mod because of how much easier it is to implement than Applied Energistics 2 early on in a playthrough, but this makes the mod a broken mess.

**Comment by Lothrazar** [comment]
Yep if the Main/master block is in an unloaded chunk, of course it cannot run, this works as intended.  tile entities dont run in unloaded chunks, this is the same for every minecraft mod.  AE2 also has blocks that dont run in unloaded chunks

Try adding in some Chunk Loaders from other mods or increasing your servers distance .

**Comment by Freakous** [comment]
Are you kidding me Lothrazer. I said it isnt working when the main/master  IS IN THE SAME LOADED CHUNK! You did this last time on the last issue post, you cant just keep sweeping this under the rug
