### ISSUE TITLE
Server Crashes with StackOverflowException (Forge 1.16.5)

### ISSUE THREAD

**Issue by zainh96** [PrinceOfAmber/Storage-Network#427]
Minecraft Version: 1.16.5

Forge Version: 1.16.5

Mod Version: 1.16.5-1.5.1

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Upon inserting a stack into the network, the server sometimes crashes. Unsure about the exact stack insertion which causes the problem

Log file link:
https://paste-bin.xyz/36645

Video/images/gifs (direct upload or link):

**Comment by zainh96** [comment]
Could it be that the server ran out of memory and that there isn't infinite recursion?

**Comment by Lothrazar** [comment]
im working on some changes for this and similar issues. but yeah im curious how big these networks are, like is it 10 chests or 10,000 .
See #415 and #417
