### ISSUE TITLE
Filtered link cable priority not working right.

### ISSUE THREAD

**Issue by Jadan1213** [PrinceOfAmber/Storage-Network#432]
Minecraft Version: 1.18.1

Forge Version: 39.0.79

Mod Version: 1.5.4

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):
Attempting to sort/filter items with a filtered link cable does not work unless setting a NEGATIVE priority. Standard link cables appear to have a priority of "0" which matches the suppose to be highest priority of "0" for filtered link cables.

**Comment by Lothrazar** [comment]
Also related to https://github.com/Lothrazar/Storage-Network/issues/396

**Comment by Lothrazar** [comment]
will be looking at new priority system as a feature in https://github.com/Lothrazar/Storage-Network/issues/396
