### ISSUE TITLE
Curios and modifiers cause a crash

### ISSUE THREAD

**Issue by DoctorMage** [PrinceOfAmber/Storage-Network#440]
Minecraft Version: 1.16.5

Forge Version: 36.2.29

Mod Version: 1.16.5-1.5.2
Other mods involved
curios-forge-1.16.5-4.0.8.1
jei-1.16.5-7.7.1.152
modifiers-0.1.2-forge

Single Player or Server:
Single player

Describe problem (what you were doing; what happened; what should have happened):

When equipping a simple storage netwrok remote from the mod simple storage network
The game will crash due ot gaining a modifier from the mod modifiers

(Current possilbe work around is a script that disables them being curios further testing needed)

Log file link:
[latest.log](https://github.com/Lothrazar/Storage-Network/files/8456674/latest.log)

[Uploading crash-2022-04-09_00.29.14-client.txt…]()

Video/images/gifs (direct upload or link): 
https://streamable.com/di0pkl

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/3863227
