### ISSUE TITLE
Unlimited remote range config not working

### ISSUE THREAD

**Issue by TheRetroGuy1** [PrinceOfAmber/Storage-Network#441]
Minecraft Version: 1.18.2

Forge Version: 40.0.46

Mod Version: 1.6.1

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
I can not get the crafting remote to have unlimited range. I have a modpack that allows me to see my modlist and edit configs from the game, but i cannot edit Simple Storage Network's config from there. When i looked at the config file in the config folder, it says that the range has already been set to -1, so it should be unlimited already, but it's not working. I feel like the fact that i can't edit the config file from in game might have something to do with the fact that the configs that are set are not being followed.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by alexbarnsley** [comment]
@TheRetroGuy1 have you tried force loading the chunks where the network is?

**Comment by Lothrazar** [comment]
works as intended as long as the chunk containing the main network node is loaded https://minecraft.fandom.com/wiki/Spawn_chunk


or like https://www.curseforge.com/minecraft/mc-mods/persistent-bits
