### ISSUE TITLE
Import/Export cables break when Vanilla Furnace toggles its state

### ISSUE THREAD

**Issue by soraphis** [PrinceOfAmber/Storage-Network#442]
Minecraft Version: 1,18.1

Forge Version: 39.1.2

Mod Version: SimpleStorageNetwork-1.18.1-1,6.0

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

I've linked import/export cables to vanilla furnaces. when the furnace stops smelting (block changes from with flames to without flames), the import/export cables break their connection to the furnace

Video/images/gifs (direct upload or link): 

https://user-images.githubusercontent.com/3066582/163466017-e80a499d-c6a2-4abf-9476-f45fa958b6f0.mp4

**Comment by soraphis** [comment]
Ok, they automatically reconnect if there is something to import/export

**Comment by Lothrazar** [comment]
this is resolved in the 1.18.2-1.6.1 version https://imgur.com/YUYmtyG

**Comment by aelfwyne** [comment]
> this is resolved in the 1.18.2-1.6.1 version https://imgur.com/YUYmtyG

I'm using SimpleStorageNetwork-1.19-1.6.4 and am having this same behavior. Export cables keep disconnecting themselves from the vanilla furnaces.

**Comment by bob3r8** [comment]
SimpleStorageNetwork 1.6.5 for Minecraft 1.19.2 still has this problem.
