### ISSUE TITLE
Upgrade to 1.19?

### ISSUE THREAD

**Issue by skelso01** [PrinceOfAmber/Storage-Network#449]
Minecraft Version: 1.19

Forge Version: 

Mod Version: 

Single Player or Server:

Is there a plan to upgrade this great mod to Minecraft 1.19?

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
Yes i will update to 1.19. i have other smaller mods ported already
First im planning to fix bunch of bugs in 1.18 first, get that out, and then port so then i dont have to fix them twice
