### ISSUE TITLE
Crafting doesn't update in 1.16.5

### ISSUE THREAD

**Issue by PaienNate** [PrinceOfAmber/Storage-Network#450]
Minecraft Version: 1.16.5

Forge Version: 36.2.35

Mod Version: SimpleStorageNetwork-1.16.5-1.5.2

Single Player or Server: SinglePlayer,Server(arclight)

Describe problem (what you were doing; what happened; what should have happened):

like #267 , but on 1.16.5. See the gif below:

(I make this gif with other mods, but I make a new game without other mods, its display did not update to the correct amount too.

Log file link:

Video/images/gifs (direct upload or link): 

https://i.imgur.com/fOczBLW.gif

**Comment by Lothrazar** [comment]
..yeah its been like this for quite a while, i checked some old versions. and i dont really want to re-add more lag just to make it spam sync requests every tick.   right now it syncs when things are being imported/exported or when another update triggers it. or when you close/reopen the screen or click somewhere. no item loss or dupe everything maths out as expected

observe here the iron starts at 302 but watch when it updates
![450 thing](https://user-images.githubusercontent.com/621529/177918257-03706446-56d6-485a-8606-64125ad4d0a2.gif)
