### ISSUE TITLE
you dont lose iron while crafting in storage request table

### ISSUE THREAD

**Issue by lordofthetimes** [PrinceOfAmber/Storage-Network#452]
Minecraft Version:  1.16.5

Forge Version:  36.2.34

Mod Version: 
SimpleStorageNetwork-1.16.5-1.5.2

Single Player or Server:
server

Describe problem (what you were doing; what happened; what should have happened):

when you craft items that require iron, you dont lose iron when you craft in storage request table
edit : same with crafting link cable (you dont lose network cable)

Log file link:

Video/images/gifs (direct upload or link): 

![obraz](https://user-images.githubusercontent.com/98896650/177774241-94922fe7-869d-406c-b022-72052c8b8afe.png)
![obraz](https://user-images.githubusercontent.com/98896650/177774282-cc6e2cd8-80f0-4622-b753-040e3d817fc5.png)

**Comment by Lothrazar** [comment]
same as https://github.com/Lothrazar/Storage-Network/issues/450#issuecomment-1178542985
