### ISSUE TITLE
TileConnectable.onChunkUnload can keep chunks loaded

### ISSUE THREAD

**Issue by mezz** [PrinceOfAmber/Storage-Network#46]
I am helping out a server which says chunks are being loaded all the time even without chunk loaders.

It seems like `TileConnectable.onChunkUnload` is causing chunks to stay loaded because it is requesting a tile entity from a chunk that is unloading. I think this is contributing to their issue.

**Comment by PrinceOfAmber** [comment]
Hmmm. yeah for some reason, this tile listens to chunk unload and then calls "refreshNetwork"

This seems counter intuitive i dont know why it would do this.  Maybe its meant to remove itself from the network?  

Ill look into removing this and then load and unload chunks and see if anything breaks

**Comment by PrinceOfAmber** [comment]
There is now a config option to disable this 👍 https://minecraft.curseforge.com/projects/simple-storage-network/files/2524875

**Comment by mezz** [comment]
Hm, if the master block is already unloaded does the network need to be updated when a part of it unloads? Maybe you can just add a check to see if the master block is loaded before trying to grab its tile entity to update the network.
