### ISSUE TITLE
[1.19.2] [Server Start up] Update to Latest version

### ISSUE THREAD

**Issue by Mini-kun** [PrinceOfAmber/Storage-Network#477]
Minecraft Version: 1.19.2

Forge Version: 43.2.3

Mod Version: 1.6.5

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): 
I update my server mods and it wont start doing a Load errors encountred See the crash report below
Plz message me if u want the Latest log file aswell

Log file link: https://pastebin.com/hPJx0g6s

Video/images/gifs (direct upload or link): have none seen as it's not on the singleplayer

**Comment by Wubzzz1337** [comment]
Was going to report the same issue.

**Comment by ProfessorDaen** [comment]
I am having the same issue.  Are there any valid workarounds for this issue outside of downgrading, or an indication this will be solved soon in the main branch?  If I'm reading this correctly it essentially means the current version of SSN is incompatible with multiplayer and would require downgrading Forge to early 1.19.

**Comment by Mrbysco** [comment]
There's a PR #480 That fixes the issue, it just need to get merged and have a new build uploaded to Curse

**Comment by ProfessorDaen** [comment]
Appreciate the response Mrbysco.  How long do these normally take to get merged and rebuilt onto CurseForge, out of curiosity?  We're trying to determine whether we can include SSN in our upcoming server and can't feasibly downgrade past 1.19.2.

Edit: Version 1.6.4 of the mod is looking promising, it doesn't appear to have the same issue as 1.6.5.  This might be the workaround we're looking for.

**Comment by ModernGamingWorld** [comment]
Any Update, I cant progress with testing my server cause this said issue

**Comment by ProfessorDaen** [comment]
> Any Update, I cant progress with testing my server cause this said issue

If it's feasible for you, try downgrading to 1.6.4 until it's solved on the current 1.19.2 version (1.6.5).

**Comment by gitshit** [comment]
This issue has persisted for months now. Anyone trying to run a server using this mods latest version will promptly have their server crash. A very bad state for a mod to be in. 
It appears the PR to patch this (which was swiftly made by @Mrbysco), in addition to other open PRs are not being reviewed. This begs the question; Is this mod abandoned? Can we expect any updates on this?

**Comment by iturdzonyou** [comment]
Got the same issue. SimpleStorageNetwork-1.19-1.6.5.jar loads on startup for 1.19.2

**Comment by Lothrazar** [comment]
as stated above; latest versions have fix for example SimpleStorageNetwork-1.19.2-1.7.0 https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/4582762 :) :)
