### ISSUE TITLE
When shift-click to get a craft of stack items,,, they disappear...

### ISSUE THREAD

**Issue by jonabrv1965** [PrinceOfAmber/Storage-Network#48]
Hello, with the latest version, SimpleStorageNetwork-1.12.2-1.2.0, whenever I shift-click in the request table/remote to get a stack of items, lets say, a stack of 63 oak wood slabs,  the mod does not create any slab and my wood planks inventory is diminished...If I downgrade to 1.1.1 this shift-click gesture works just fine (I get the stack of crafted items in my inventory)....

**Comment by PrinceOfAmber** [comment]
Sorry for the trouble 1.2.0 was meant to be marked as alpha, i have been testing different ways with some modpack developers  to fix huge lag spikes while shift clicking.  1.2.1 has resolved this issue   https://minecraft.curseforge.com/projects/simple-storage-network/files/2524360

**Comment by kreezxil** [comment]
I can confirm this is happening, I think it might be wise to archive this version on CurseForge so that no one will be able to deliberately download it but it would still be available for packs that are currently depending on it.
