### ISSUE TITLE
1.6.5 fails to load on Forge 43.2.0

### ISSUE THREAD

**Issue by naneko** [PrinceOfAmber/Storage-Network#493]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.2.0

**Mod Version:** 1.6.5

**Single Player or Server:** Server

**Describe problem (what you were doing; what happened; what should have happened):** Mod is failing to load on server after updating to 1.6.5 and Forge version 43.2.0 from 43.1.23. My modpack works fine client-side but for whatever reason it doesn't server-side. I have no yet tried running the mod by itself without other mods. 

**Log file link:** https://gist.github.com/naneko/2b3b4fd5d4db2f8147f55e205d8978ff

**Comment by Mrbysco** [comment]
Duplicate of #477

**Comment by naneko** [comment]
Confirmed duplicate
