### ISSUE TITLE
System shows double the actual amount

### ISSUE THREAD

**Issue by Gerritsonn** [PrinceOfAmber/Storage-Network#499]
1.19.2
forge 43.2.0
SimpleStorageNetwork-1.19-1.6.5.jar
Single Player

When opening the simple storage system it says I have twice as much items than I actually have.
Like it says I have 256 stone but when I took it out of the storage it was only 128 stone

**Comment by syntheer** [comment]
That looks like a chest with two links attached to it.

**Comment by HalcyonSeas73** [comment]
Agreed, this is a setup issue, not an SSN issue.
