### ISSUE TITLE
1.11.2-1.0.2 server crash when switching out entity blocks onto already active import/export cables.

### ISSUE THREAD

**Issue by kreezxil** [PrinceOfAmber/Storage-Network#5]
1.11.2-1.0.2 crashes dedicated server Forge 1.11.2 build 2313

Notes:
     had a network in place with a furnace that was accepting two (2) imports and giving one (1) export. Decided it was the wrong item, so knocked out the furnace with a pick axe and put in a double furnace. Apparently it didn't like have a title entity placed on to the already active import/export cables.

crash report:
https://gist.github.com/3385fdaa773715448f410ce819859b67

fml server latest:
https://gist.github.com/de28b7c59fb898b0a66fd68569342de6

**Comment by kreezxil** [comment]
restarted the server so I can go in and give you a screenshot, it shot back with the same error I believe and therefore will not start now.

1.11.2-1.0.2 crashes dedicated server Forge 1.11.2 build 2313

Notes:
     2nd verse same as the first! Henry the eight I am I am ... la la la

crash report:
https://gist.github.com/346331c7e6b4a7b04014438da560de09

fml server latest:
https://gist.github.com/18072d43d7a05a27e6b2c7afe38117c1

**Comment by kreezxil** [comment]
i have an idea that would prevent this, have the import/export cables pop off and fall to the ground if the entity to which they are attached suddenly is no longer attached to them.

**Comment by kreezxil** [comment]
crashes dedicated server Forge 1.11.2 build 2313

Notes:
     must be the double furnace, i put coal in the export cable to indicate that I want to pass that fuel in to the machine then it crashed, I think this is the same crash was before but caused a different way

crash report:
https://gist.github.com/6d2f76f5c9213cfbeb5045643883795c

fml server latest:
https://gist.github.com/e5a02a47f0b04f2ace43e150a5b2c7cd

**Comment by kreezxil** [comment]
crashes dedicated server Forge 1.11.2 build 2313

Notes:
     seems when your mod takes the epic dump that restarting the server becomes impossible.

crash report:
https://gist.github.com/ce62cfda567fa7bb27b1057574f958d5

fml server latest:
https://gist.github.com/783f3ecbbaae8f56fbda67eb997fbd90

thankfully the simple storage mod isn't in my main public released pack.

**Comment by PrinceOfAmber** [comment]
"i have an idea that would prevent this, have the import/export cables pop off and fall to the ground if the entity to which they are attached suddenly is no longer attached to them."

I will if i have to, but hopefully i can get a fix without resorting to this.  It was just tryin to insert into the furnace after it was removed . 

and its remembering its current operation so when server restarts its still trying to do the same thing, so the restart crash logs look like the same exact error in the same spot as the first. 

Ill have a small fix soon

**Comment by PrinceOfAmber** [comment]
adding a second handler so hopefully if this happens again (runtime or startup). it will just log the error and continue going. server im testing on is just running locally so we'll see

**Comment by PrinceOfAmber** [comment]
Try out the latest version 1.0.3 on your server, was working on mine.  Let me know if any other issues come up.  https://minecraft.curseforge.com/projects/simple-storage-network/files/2430054

**Comment by kreezxil** [comment]
I'll let you know tomorrow. Thanks for your great work.
