### ISSUE TITLE
Remote Not working more than 200 blocks away

### ISSUE THREAD

**Issue by AltonSmasher** [PrinceOfAmber/Storage-Network#508]
Minecraft Version: 
1.19.4
Forge Version: 
1.19.4
Mod Version: 
1.19.4
Single Player or Server:
Server
Describe problem (what you were doing; what happened; what should have happened):
I have created my remote and whenever I go more than 200 blocks away it doesn't work even when I do function 3 a to reload chunks. What should have happened is that the remote should have still worked outside of 200 blocks.

**Comment by HalcyonSeas73** [comment]
You need a chunk loader to keep the chunk your network is it loaded. 

Not an issue

**Comment by leozin10mil** [comment]
e como consegue um carregador de blocos ? pois estou na versao 1.16.5 e depois de um determinado numero de blocos o controle nao funciona mais

**Comment by Lothrazar** [comment]
A tip for if you dont have any chunk loader items in the modpack or world, put your network right at worldspawn, as those chunks are always loaded https://minecraft.fandom.com/wiki/Spawn_chunk
