### ISSUE TITLE
1.19.2 Duplication Glitch

### ISSUE THREAD

**Issue by CrazyDev05** [PrinceOfAmber/Storage-Network#511]
Minecraft Version: 1.19.2
Forge Version: 42.2.11
Mod Version: 1.19-1.6.4
Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
I found a duplication glitch.
When one player prepares a crafting recipe, then closes the ui and then two (or more) players open the ui and one takes the crafting result out the other player can also do that.

Video/images/gifs (direct upload or link): 
Clip of two accounts duplicating one iron block.
https://github.com/Lothrazar/Storage-Network/assets/47589149/3abc2fc8-e30d-4cd5-9283-863abdcfc243

**Comment by Lothrazar** [comment]
Thanks for the report! I was able to find and replicate thanks to your video.  Patches have been released, This is no longer possible in the latest updates.
Fixed versions:
1.16.5-1.5.4
1.18.2-1.7.1
1.19.2-1.7.1
1.19.4-1.9.1
1.20.1-1.11.1
available on modrinth or curseforge
