### ISSUE TITLE
Lags whenever I'm in a world

### ISSUE THREAD

**Issue by LichWizard** [PrinceOfAmber/Storage-Network#524]
Minecraft Version: 
1.16.5
Forge Version: 
36.2.24
Mod Version: 
1.16.5
Single Player or Server:
Single player
Describe problem (what you were doing; what happened; what should have happened):
When i load in to any word (Preexisting or newly generated) it lags really badly, and only when i have the mod in my mod folder.

Log file link:
N/A

Video/images/gifs (direct upload or link): 
N/A

**Comment by Lothrazar** [comment]
From this report there is no way to tell if or how it was from this mod, i have no actions i can take from this, not enough info
