### ISSUE TITLE
O controle para de funcionar depois de um determinado numero de blocos

### ISSUE THREAD

**Issue by leozin10mil** [PrinceOfAmber/Storage-Network#525]
Minecraft Version: 1.16.5

O controle para de funcionar depois de um determinado numero de blocos, tem oque fazer?

**Comment by HalcyonSeas73** [comment]
You need a mod that loads chunks, such as [Chunk Loader](https://legacy.curseforge.com/minecraft/mc-mods/chunk-loaders).

**Comment by HalcyonSeas73** [comment]
!not an issue

**Comment by Lothrazar** [comment]
Yes try building the newtork in to the spawn chunks as another alternative https://minecraft.fandom.com/wiki/Spawn_chunk
