### ISSUE TITLE
Can't put upgrades in cables

### ISSUE THREAD

**Issue by h4ppyboy** [PrinceOfAmber/Storage-Network#528]
Minecraft Version: 1.20.1

Forge Version: last

Mod Version: last

Single Player or Server: singleplayer

Describe problem (what you were doing; what happened; what should have happened): Can't open cable gui to put some upgrades

lmb/rmb doesn't help

Log file link:

Video/images/gifs (direct upload or link):

**Comment by crocodiloart** [comment]
![image](https://github.com/Lothrazar/Storage-Network/assets/112916827/acddc242-eaea-4962-b578-14073c59162d)
I canp put a filter item in the operation upgrade inside the export cable
Im playing in an aternos server

**Comment by Lothrazar** [comment]
as others have stated, in my personal testing i can put in upgrades into the system . Thanks for the report!

![as intended](https://github.com/user-attachments/assets/826eed6b-80e7-4051-9861-d89d652d73bf)
