### ISSUE TITLE
simple storage craft jei sync crash 

### ISSUE THREAD

**Issue by thejoyofhogriding** [PrinceOfAmber/Storage-Network#530]
Forge Version: 

Mod Version: 
skyopolis 5
Single Player or Server:
single
Describe problem (what you were doing; what happened; what should have happened):
just got to simple storage quest and gaem crashes everytime you sync jei in the crafting block. restart game a break block to seset settings and works fine as long as no jei snyc

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
Missing mod version and Minecraft version.  Unknown if you are using the latest released mod update for that version.  I tested recently in mc 1.20.1 and mc 1.12 with no issues. ill keep an eye out for this on other versions as well . Thanks for the report
