### ISSUE TITLE
[1.12.2] Silent's Gems recipes don't work in the crafter

### ISSUE THREAD

**Issue by faeldray** [PrinceOfAmber/Storage-Network#54]
Attempting to make tools and weapons from Silent's Gems in the crafter doesn't work (something to do with NBT it seems, see screenshot below). The recipes work fine in a normal crafting table.

Simple Storage Network 1.12.2-1.2.4
Silent's Gems 1.12-2.6.9b-265
Forge 2611

![20180318045056_1](https://user-images.githubusercontent.com/967709/37564648-3077893e-2a68-11e8-8002-ce1cd5b42b77.jpg)

**Comment by PrinceOfAmber** [comment]
Thanks for your patience, looking into this now & this weekend

**Comment by PrinceOfAmber** [comment]
Found a fix in #59 that will apply to this

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2573216
