### ISSUE TITLE
SSN + Reliquary's Tome dupe bug

### ISSUE THREAD

**Issue by Rakosnakak** [PrinceOfAmber/Storage-Network#56]
https://www.youtube.com/watch?v=pKQIVcuJeo0&feature=youtu.be

**Comment by PrinceOfAmber** [comment]
I know this was ages ago, but i assumed that when i put in fixes for similar issues with Pams cooking and IE copper wires and plates it fixed it, but not really https://github.com/PrinceOfAmber/Storage-Network/issues/52 

but i came back and found a fix that will be released soon 
![clay tome](https://user-images.githubusercontent.com/621529/43790634-06bf28f6-9a28-11e8-928e-f3db3e47e658.gif)

**Comment by PrinceOfAmber** [comment]
1.2.8 https://minecraft.curseforge.com/projects/simple-storage-network/files/2599746
