### ISSUE TITLE
My modpack crashes when pams harvest craft

### ISSUE THREAD

**Issue by githpgames** [PrinceOfAmber/Storage-Network#562]
Minecraft Version: 1.12.2

Forge Version: 14.23

Mod Version: 

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened):

I installed pams harvest craft and it crashed the game

Log file link: 
https://pastebin.com/jSUhrxtX

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
you should probably report it to pams harvest craft then . om.supermartijn642.core.registry.Registries$ForgeRegistryWrapper.register(Registries.java:296) is not part of this mod
