### ISSUE TITLE
[1.12.2-1.2.4] Advanced Storage Remote random disconnects

### ISSUE THREAD

**Issue by kreezxil** [PrinceOfAmber/Storage-Network#57]
The regular remote works flawlessly but when you upgrade it to the advanced one so that you can use it from great distances and interdimensionally, it randomly disconnects from the assigned network and requires frequent reassignment.

**Comment by Tr4shM0nk3y** [comment]
Happens to me as well, not even in a different dimenstion, just about 400 blocks away

**Comment by PrinceOfAmber** [comment]
Hey thanks for your patience. Is it maybe chunk unloading? It works fine ot me if base is in spawn chunk? not sure 100% tho

**Comment by PrinceOfAmber** [comment]
No new information has appeared, but i can replicate this when the chunk containing the master controller unloads, i have to assume its that
