### ISSUE TITLE
Storage Network resetting "sorting by" randomly

### ISSUE THREAD

**Issue by Tr4shM0nk3y** [PrinceOfAmber/Storage-Network#58]
The "Sort by" button sometimes randomly changes from sort by amount back to sort by name.

**Comment by PrinceOfAmber** [comment]
Aha. so this is not stored in the "network" each Request table and each Remote stores its own setting

So I setup one table as stort by amount, one as by quantity, and a remote sorting by mod. All three save their settings on world reload, its not network wide.  

I think this clears it up, feel free to reopen or open new if theres an issue
