### ISSUE TITLE
Iron Backpack Upgrade

### ISSUE THREAD

**Issue by 47MarkIV** [PrinceOfAmber/Storage-Network#59]
When upgrading an backpack through the storage request table, the contents of the backpack are lost.
Steps:

Versions: 
Iron Backpacks 1.12.2-3.0.5-6
Simple Storage 1.12.2-1.2.4

1. Craft basic (leather) backpack
2, Put any item into pack
3, Upgrade pack to the iron tier through storage request table
4, Open upgraded backpack and see inventory is missing

**Comment by PrinceOfAmber** [comment]
Thanks for your patience i couldnt get to these right away. I will investigate NBT fixes

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2573216
