### ISSUE TITLE
Cannot remove items using Request Table or Advanced Remote.

### ISSUE THREAD

**Issue by Milesman34** [PrinceOfAmber/Storage-Network#65]
This happened on both older and newest versions of this mod and JEI.

I attempted to remove some blocks from the storage system, but it wouldn't work. I can insert blocks.

Modlist: https://hastebin.com/siqekukewu.md

**Comment by PrinceOfAmber** [comment]
I can get this to happen with items that have NBT data sometimes, or damaged items yeah

**Comment by PrinceOfAmber** [comment]
Hi can you take a picture or something of your network?

I have seen this happen before like on twitch streams and videos of other people, usually they have like 1 or 2 items that get stuck but the rest works fine.

In my tests everything works so its hard to find the issue

![storage](https://user-images.githubusercontent.com/621529/41496449-95b6539c-70f5-11e8-9593-41d80cfe65a1.gif)

**Comment by Milesman34** [comment]
https://gfycat.com/gifs/detail/DisgustingShabbyBalloonfish

The bug doesn't occur with some items for some reason.

**Comment by PrinceOfAmber** [comment]
Thanks for the video, that helps a lot. ill test out making a big complex  network like that.  with lots of modded storage linked in

If you can , can you send your latest .log file, or even your entire /logs/ folder zipped ? There might not be anything helpfull in there but its possible

**Comment by Milesman34** [comment]
https://paste.ee/p/TtFWD

this is latest.log

**Comment by PrinceOfAmber** [comment]
Check this out when you get a chance https://minecraft.curseforge.com/projects/simple-storage-network/files/2573911

**Comment by Milesman34** [comment]
It works now! Thanks for fixing the bug!
