### ISSUE TITLE
inventory desync?

### ISSUE THREAD

**Issue by majijn** [PrinceOfAmber/Storage-Network#68]
after updating to 1.2.6 ive noticed my items take a while to load, both on the crafting block and the advanced remote.
and also now ive been getting weird desync where I cant use my 2x2 crafting grid and if I move items around my inventory, when I try to use them they dont work,but if I use the remote ill see them where I moved them from rather than where I moved them to.
![2018-06-18_21 23 48](https://user-images.githubusercontent.com/18368034/41558795-4cd99e50-7342-11e8-8bc6-d4a20e676dcb.png)
![2018-06-18_21 23 50](https://user-images.githubusercontent.com/18368034/41558800-50665f5e-7342-11e8-8093-c2ccbb982106.png)
![2018-06-18_21 23 53](https://user-images.githubusercontent.com/18368034/41558804-53511178-7342-11e8-83ed-49a222c2882d.png)

**Comment by majijn** [comment]
i downgraded the version of this mod, it fixed the item load lag when looking at my storage network, but im still getting the desync.

which means it's either something else doing it, or something changed that's made it permanent to that world, or it has to do with astral sorcery's latest update, or a mixture of these things,  it doesnt happen in other worlds so I may just have to start anew...sigh.

sorry for bothering you!

**Comment by PrinceOfAmber** [comment]
Thanks Ill look into it.

100% i do notice the initial lag when opening up the table it takes a second 


My 2x2 inventory is fine so thats weird

**Comment by PrinceOfAmber** [comment]
OH yeah i added this bug by accident when fixing this https://github.com/PrinceOfAmber/Storage-Network/issues/65 

But i have a solution in mind so its on the way
