### ISSUE TITLE
Bug with JEI

### ISSUE THREAD

**Issue by IcedCoffeee** [PrinceOfAmber/Storage-Network#70]
I was crafting an advanced storage remote inside my current remote, but when I clicked move items from the recipe in JEI, it moved the remote I was using into itself and closed the screen, essentially deleting the remote and all the items I was crafting with.

**Comment by PrinceOfAmber** [comment]
I couldnt find any way to tell JEI to "hey dont use whats in my hand" so i have to just change the recipe to not use the basic remote when making advanced. i guess 👍

**Comment by PrinceOfAmber** [comment]
1.2.8 https://minecraft.curseforge.com/projects/simple-storage-network/files/2599746
