### ISSUE TITLE
[1.12.2] server lags when players craft stack of anything in adv. remote

### ISSUE THREAD

**Issue by kwpugh** [PrinceOfAmber/Storage-Network#71]
forge-1.12.2-14.23.4.2708-universal.jar
SimpleStorageNetwork-1.12.2-1.2.7.jar

When a player crafts an entire stack of something (e.g. any essence from mystical agiculture) the server noticeably lags and it client side takes several seconds before the result stack to appear.

**Comment by kwpugh** [comment]
Hi,

It happens when attached to IronChests mod and and Storage Drawers.   Never tried vanilla chests since they are so small.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2608694
