### ISSUE TITLE
Advanced remote filtering getting stuck. 

### ISSUE THREAD

**Issue by MuteTiefling** [PrinceOfAmber/Storage-Network#73]
At times it seems the filter gets stuck and won't default back to a blank search. 

For example, I pulled some sacks of holding out of my system and for several hours after that, the search would default back to that search whenever I opened the remote.

Sometimes I could get it to go to back to my default filtering (sort by quantity, not jei linked) but it for a few minutes. Eventually it would revert to the sack search and link to jei.

Note that at no point did I manually search for these sacks in jei. The remote just seemed to remember I had searched for that and revert to it by default. 

Server restarts did not help. I eventually trashed it and cheated in a new one. That fixed it for longer, but it's come back again with a new search. 

Version 1.12.2-1.2.4

**Comment by majijn** [comment]
i've had that happen to me as well, I just cheated in a new remote and deleted the old one to work around it.

**Comment by PrinceOfAmber** [comment]
Yeah im re-working how the JEI filter linking search works, it will be much better in 1.2.8 coming up in future:

it only updates JEI text on a keypress and not every tick;

AND  when you initially open the screen it reads in your current JEI search instead of wiping it

**Comment by PrinceOfAmber** [comment]
1.2.8 https://minecraft.curseforge.com/projects/simple-storage-network/files/2599746
