### ISSUE TITLE
Bug When Shift-Right-Click

### ISSUE THREAD

**Issue by emilienchayer** [PrinceOfAmber/Storage-Network#74]
When I Shift-Right-Click in the storage Request table either the item crafted disappear or it duplicatate ... like a lot. I had like 4k cobblestone and after the bug i had 44k and more because it filled my storage network.
![bug](https://user-images.githubusercontent.com/39675744/41991127-6d0fc9c0-7a12-11e8-9a48-285c86119306.png)

**Comment by PrinceOfAmber** [comment]
What storage blocks was it connected to? Ive had bugs in the past with certain mods but not others.

I tested the same thing with vanilla chests, shift right clicking a recipe

![stone crafty](https://user-images.githubusercontent.com/621529/43808170-a1206dfa-9a60-11e8-98bc-a99d9f55d6b0.gif)

**Comment by jiangzihao** [comment]
@PrinceOfAmber 
Plz use stones in stack in recipe.

**Comment by PrinceOfAmber** [comment]
Not sure which version this was reported on but many things rewritten and fixed  and changed in 1.3 and 1.4.0 out now

Also try with fast bench compatibility all new https://minecraft.curseforge.com/projects/fastworkbench

https://minecraft.curseforge.com/projects/simple-storage-network/files/2617829

if this comes back in similar way or anything else we can do a  new issue no problem
