### ISSUE TITLE
[Suggestion] Interface block

### ISSUE THREAD

**Issue by phill-a** [PrinceOfAmber/Storage-Network#75]
I'd like to suggest a block similar to the ME Interface that allows another entity to interface with the entire item network as if it were one big inventory, sort of like a reverse storage link cable, such that a machine could either push something into the network through that block or pull something out through. I think this would make the mod a lot more powerful since it would allow interaction with mods like ProjectRed Transportation's logistics pipes-like networks for requesting and autocrafting such that one could achieve ME system-like functionality with some ingenuity. I think a concern would be that this overcomplicates the mod, since it's supposed to be a simple inventory system, but I think such a system wouldn't necessarily add AE2-like complexity, just allow for a lot more power with a block that has a rather simple functionality by itself.

**Comment by PrinceOfAmber** [comment]
Yeah i really want to be able to interface with other mods like RF and AE. Im not really sure where to start since I adopted this mod from another author but ill try to do some research.

**Comment by PrinceOfAmber** [comment]
See discussion in https://github.com/PrinceOfAmber/Storage-Network/issues/72

 this is a big feature that i would like to do one day, hopefully
