### ISSUE TITLE
Stack upgrade only moves stack for import

### ISSUE THREAD

**Issue by PraiseSatan** [PrinceOfAmber/Storage-Network#77]
Version 1.2.4 states that the stack upgrade should move an entire stack (64 items) for import and export cables.
However the export cable still has the old behaviour of outputting 2^(2+stack upgrades).
I haven't actually checked the import but assume it is fine.

It appears in the code (storagenetwork/master/TileMaster.java)
The updateExports still has at line 370:
`insert = Math.min(insert, (int) Math.pow(2, tileCable.getUpgradesOfType(ItemUpgrade.STACK) + 2));`
While updateImports has:
` boolean hasStackUpgrade = tileCable.getUpgradesOfType(ItemUpgrade.STACK) > 0;
        int maxInsert = (hasStackUpgrade) ? 64 : 4;
        int insert = Math.min(stackCurrent.getCount(), maxInsert);`

**Comment by PrinceOfAmber** [comment]
1.2.8 https://minecraft.curseforge.com/projects/simple-storage-network/files/2599746
