### ISSUE TITLE
Cant put more than one stack when doing stock upgrade in export cable

### ISSUE THREAD

**Issue by SHsuperCM** [PrinceOfAmber/Storage-Network#79]
Title

**Comment by PrinceOfAmber** [comment]
Yep see #77 stack upgrade will be fixed

In next release, Stack Upgrade will do 64 items per tick and you only need one, (and then you can also add 3 speed upgrades if you want)

**Comment by PrinceOfAmber** [comment]
1.2.8 https://minecraft.curseforge.com/projects/simple-storage-network/files/2599746

**Comment by SHsuperCM** [comment]
Sorry for taking too long, I think you got the issue wrong.. What I'm trying to do is keep more than 1 stack in a container.. Like... Keep 3 stacks of sugar canes in craftingtable(Redstone++) for paper..
