### ISSUE TITLE
1.11.2-1.0.4 client crash when reading opening request table

### ISSUE THREAD

**Issue by kreezxil** [PrinceOfAmber/Storage-Network#8]
https://pastebin.com/VPKBDHJY

**Comment by kreezxil** [comment]
so I removed the interface to the colossal chest and it crashed again

https://pastebin.com/DCF1vrLi

I think the problem is related to JEI being updated.

**Comment by kreezxil** [comment]
apparently you must be enjoying a most spectacular vacation.

**Comment by PrinceOfAmber** [comment]
LOL sorry was working on bugs in my other mods. Looking into this now

**Comment by PrinceOfAmber** [comment]
Also im going to turn on email notifications, for some reason github didnt email me when this was reported like i expected it to

**Comment by PrinceOfAmber** [comment]
Aha, turns out if you update to older JEI this is fixed - jei_1.11.2:4.4.0.283

I will figure out a patch to work with new versions and release 1.0.5 of storage network today or tomorrow

**Comment by PrinceOfAmber** [comment]
Check out the latest fixes!! https://minecraft.curseforge.com/projects/simple-storage-network/files/2435492
