### ISSUE TITLE
Cant search for spesific enchantments on books/items in general I guess

### ISSUE THREAD

**Issue by SHsuperCM** [PrinceOfAmber/Storage-Network#81]
Title

**Comment by PrinceOfAmber** [comment]
Hm.. maybe I could add a checkbox somewhere below the search bar on the main GUI, something like "Search NBT" for enchantments.

**Comment by PrinceOfAmber** [comment]
![2018-08-23_21 06 06](https://user-images.githubusercontent.com/621529/44564565-75ab1480-a718-11e8-892a-41cc99c8ada3.png)
![2018-08-23_21 05 44](https://user-images.githubusercontent.com/621529/44564566-75ab1480-a718-11e8-97be-4813cf78ea71.png)

**Comment by PrinceOfAmber** [comment]
Hah, im a dummy. the # search filter lets you hit tooltips thats an old feature i forgot about.

Mouse over the text box and hold shift and it gives you tips.

Anyway if this wasnt a feature i would have added it so thanks so much for the post!
