### ISSUE TITLE
Some items cannot be extracted from storage via the remote interface

### ISSUE THREAD

**Issue by MuteTiefling** [PrinceOfAmber/Storage-Network#82]
This appears to be happening with a few items. Two of note are the chest pieces for my Galacticraft space suits. My tier 2 and tier 1 chest pieces cannot be extracted from storage by using the remote interface.

To replicate, I insert them into storage and attempt to remove them. no interaction.

I then go to the chest where they're stored and pull them out without any issue. Drop them back in and attempt to extract via the remote = nothing.

**Comment by PrinceOfAmber** [comment]
What version of the mod are you using? In version 1.2.6 there was a fix for something related to this,

https://minecraft.curseforge.com/projects/simple-storage-network/files/2573911

Have you found any other items or is it just that armor?

**Comment by PrinceOfAmber** [comment]
1.2.8 just came out, it should work fine in that version but ill leave this open for now  https://minecraft.curseforge.com/projects/simple-storage-network/files/2599746

**Comment by MuteTiefling** [comment]
I'm on 1.2.4 still. can't confirm if the update fixed this as I'm not able to update my pack right now. 

I have noticed a few other items since that won't come out. My Astral Sorcery Resonating wand and aminotaur axe from twilight forest,

**Comment by PrinceOfAmber** [comment]
Was fixed in 128 i just forgot to close this. Also loooks good on latest version as well https://minecraft.curseforge.com/projects/simple-storage-network/files/2608694
