### ISSUE TITLE
Crash after opening request table [ crash with new versions of JEI ]

### ISSUE THREAD

**Issue by Blatts12** [PrinceOfAmber/Storage-Network#88]
https://paste.dimdev.org/igidawifuj.mccrash

**Comment by kellixon** [comment]
MC 1.12.2. Forge 14.23.4.2750. SimpleStorageNetwork 1.2.8
https://gist.github.com/kellixon/5fdb29ebe063de5136f71eb70a924fe5

**Comment by LemADEC** [comment]
DUP of #91 : downgrade your JEI version

**Comment by PrinceOfAmber** [comment]
Looks like yeah this might require an old JEI version.

If thats the only issue,  Ill update storage network to 1.3.0 and fix it to work o newest JEI

**Comment by LemADEC** [comment]
Issue was already reported to JEI GitHub here: https://github.com/mezz/JustEnoughItems/issues/1331
=> SimpleNetwork is using internal classes and needs to be updated.

**Comment by kreezxil** [comment]
1.12.2-1.2.9 Still crashes with the latest JEI 214 and 215 installed.

https://pastebin.com/m8NprHyZ

**Comment by PrinceOfAmber** [comment]
@LemADEC  thanks for the update, looks like i will upgrade to new API in the 1.3.0 release

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2608694

**Comment by mezz** [comment]
Please use the stable API, you can set the filter from there: https://github.com/mezz/JustEnoughItems/blob/3330e8711830ae837aeb234c26a2963b99048e36/src/api/java/mezz/jei/api/IIngredientFilter.java#L15-L23

Do not use `mezz.jei.Internal`, it can break any time I make small changes to the mod.

You can compile against just the JEI API using gradle like this in order to avoid using internal classes:
```groovy
repositories {
  maven {
    // location of the maven that hosts JEI files
    name = "Progwml6 maven"
    url = "http://dvs1.progwml6.com/files/maven"
  }
  maven {
    // location of a maven mirror for JEI files, as a fallback
    name = "ModMaven"
    url = "modmaven.k-4u.nl"
  }
}

dependencies {
  // compile against the JEI API but do not include it at runtime
  deobfProvided "mezz.jei:jei_${mc_version}:${jei_version}:api"
  // at runtime, use the full JEI jar
  runtime "mezz.jei:jei_${mc_version}:${jei_version}"
}
```
