### ISSUE TITLE
Crafting does damage tool but don't break them?

### ISSUE THREAD

**Issue by LemADEC** [PrinceOfAmber/Storage-Network#90]
As of SimpleStorageNetwork-1.12.2-1.2.8, with mysticalagriculture-1.12-1.6.12, the Infusion Crystal item gets damaged but never broken while crafting with it:
![image](https://user-images.githubusercontent.com/4776032/44125877-4322cbf0-a035-11e8-878b-71be0a7a0bca.png)

Our storage system is using purely Golden chests from the IronChest mod.
I've not tried with other mods' tools, so it might be a Mystical Agriculture bug?

**Comment by LemADEC** [comment]
The Tiered Crystal mod is an extension to Mystical Agriculture that add more 'tools'. Only the Master crystal is unlimited/unbreakable. We'll add to test with other tools and vanilla crafting table.

**Comment by LemADEC** [comment]
Issue isn't reproduced in a crafting table with intermedium crystal.
Is it because we have a full stack of ingredient vs pulling from the storage?

**Comment by LemADEC** [comment]
Issue isn't reproduced in a storage crafting grid with intermedium crystal when crafting one item at a time.
Issue is reproduced in a storage crafting grid with intermedium crystal when crafting one stack at a time.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2608694
