### ISSUE TITLE
Lag in TileMaster.getAttachedCables()

### ISSUE THREAD

**Issue by LemADEC** [PrinceOfAmber/Storage-Network#92]
As of 1.12.2-1.2.8, LagGoggles reports a average 200 µs load on a single Master block.
WarmRoast confirm there's a CPU load in that single block
![image](https://user-images.githubusercontent.com/4776032/44353890-a4bb4f00-a4a8-11e8-864f-0ec91090d78e.png)
nota: func_175625_s is getTileEntity

From a quick code review:
- both updateImports() and updateExports() calls the same getAttachedCables() with just a different filter. => consider scanning only once, saving the list of all cables and filtering by type in the loop
- getAttachedCables() will call getTileEntity() twice for each cable
=> consider saving the result of first call

Alternately, we could save a WeakReference to all TileEntities in addInventorys() so we only call getTileEntity() when refreshing the network.

**Comment by PrinceOfAmber** [comment]
@LemADEC  latest commit  does this refactor https://github.com/PrinceOfAmber/Storage-Network/commit/86d503ec41b4e513c4eab48f83f236e9764c4fed

**Comment by LemADEC** [comment]
![image](https://user-images.githubusercontent.com/4776032/44388031-65801300-a527-11e8-871a-56dcab75600d.png)
This is a setup with
- 119 storage in 119 Gold chests from IronChests
- 1 import from 1 Diamond chest from IronChests
- 4 exports into 2 Prudentium furnace from Mystical Agriculture.

New code looks much better.
We could pre-allocate the arrays to avoid memory reallocation lag in getAttachedTileEntities() and getAttachedCables().
```java
 List<TileCable> attachedCables = Lists.newArrayList();
```

This can be done in the list constructor like so
```java
 List<TileCable> attachedCables = new ArrayList(links.size());
```
or after construction like so
```java
List<TileEntity> attachedCables = Lists.newArrayList();
attachedCables.ensureCapacity(connectables.size());
```

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2608694
