### ISSUE TITLE
MP Client Crash when using remotes

### ISSUE THREAD

**Issue by KTev** [PrinceOfAmber/Storage-Network#93]
Reported by many users on Discord.

Multiplayer client crashes when accessing inventory using any of the remotes. Cannot recreate in single player mode.

Pack being used is World of Dragons 11.4.101 by Kreezxil
Simple storage network 1.2.9
Forge 14.23.4.2757

https://cdn.discordapp.com/attachments/396850544678797323/481424820676984833/crash-2018-08-21_14.27.17-client.txt
https://cdn.discordapp.com/attachments/396850544678797323/481281266759630868/crash-2018-08-20_21.56.21-client.txt
https://cdn.discordapp.com/attachments/396850544678797323/481281264125607947/crash-2018-08-20_21.44.48-client.txt
https://cdn.discordapp.com/attachments/396850544678797323/481281252889198592/crash-2018-08-20_21.39.18-client.txt

**Comment by rotye** [comment]
Yes, same here.

Crashes when I right click with a remote in my hand. It doesn't matter if it's bound to a network or not, crashes either way. Only happening in my MP world, can't reproduce in singleplayer.

WoD 11.4.101, Forge 14.23.4.2757, Simple Storage Network 1.2.9
[crash report](https://pastebin.com/ebtLcz4C)

**Comment by PrinceOfAmber** [comment]
Are you on new beta versions of JEI?  
This doesnt look like the same crash  but rolling back might help.

https://github.com/PrinceOfAmber/Storage-Network/issues/88


Otherwise have been working on a new 1.3.0 build for the past week did lots of refactoring and cleanup so ill put this on the list as well. aiming for a release by friday or the weeekend

**Comment by PrinceOfAmber** [comment]
Hmm something about reading data from remote
   NBTHelper.setString(itemStackIn, "sort", EnumSortType.NAME.toString());

Ill put in a fix. but does the problem go away of you toss out the old remote and make a new one? just curious

**Comment by rotye** [comment]
JEI version 1.12.2-4.11.1.213, which should work. Also, opening a request table works fine, only the remote causes a crash, so it's definitely a different thing.

No, a completely new remote crashes too, even if it's not bound to a network yet.

**Comment by kreezxil** [comment]
Can you please push this fix, because without it my pack is stuck on JEI build 213.

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2608694

**Comment by KTev** [comment]
Looks to have happened again:

WoD 11.12.109
SSN 1.12.2-1.3.0
Forge 14.23.42760

https://cdn.discordapp.com/attachments/396850544678797323/487425844952694784/crash-2018-09-06_20.13.11-client.txt
