### ISSUE TITLE
JEI Searh doesn't clear when [x] clicked

### ISSUE THREAD

**Issue by KTev** [PrinceOfAmber/Storage-Network#95]
enhancement?

It would be nice if the JEI search was cleared like the SN one does when clicking the x.

https://youtu.be/Qvk2Zg5yLSw

**Comment by larskr96** [comment]
the jei search bar Clears when i click the x

**Comment by PrinceOfAmber** [comment]
Yeah if the JEI buttin is green it should  clear both text boxes. releasing new version soon

**Comment by PrinceOfAmber** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2608694
