### ISSUE TITLE
Storage Request Table deleting items

### ISSUE THREAD

**Issue by calloatti** [PrinceOfAmber/Storage-Network#99]
SimpleStorageNetwork-1.12.2-1.3.0

When crafting items, items are lost when shift clicking crafted item. For example, shift left clicking on the dry rubber in this screen will result in only getting 1 dry rubber instead of 7.

![2018-08-30_06 30 47](https://user-images.githubusercontent.com/12817862/44843308-69462080-ac1e-11e8-8439-972be2e78586.png)

**Comment by LemADEC** [comment]
I can reproduce it with a stack of diamond blocks:
- 6 in storage + 1 in crafting grid will give 63 diamonds (as expected),
- 0 in storage + 7 in crafting grid will give 9 diamonds (lost items).
Same goes with crafting ladders, so it's not specific to shapeless recipes.

**Comment by CharCharthemonkey** [comment]
it also deletes the items on the eport cables too for seeing wats in the storage

**Comment by LemADEC** [comment]
what do you mean @CharCharthemonkey ?

**Comment by PrinceOfAmber** [comment]
Is this similar to a the dupe crashes you were doing? GIF below, is this fixed or are there other ways 
![dupemaybe](https://user-images.githubusercontent.com/621529/45602648-a78d5f00-b9d6-11e8-826b-7996891dd7e4.gif)

**Comment by PrinceOfAmber** [comment]
The system has been rewritten and looks fixed, open a new issue for any problems.

https://minecraft.curseforge.com/projects/simple-storage-network/files/2617829
